dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.8.17'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter'
    implementation 'io.livekit:livekit-server:0.15.0'
    implementation 'software.amazon.awssdk:s3:2.53.3'
    implementation 'software.amazon.awssdk:url-connection-client:2.53.3'
    testImplementation 'com.auth0:java-jwt:4.5.1'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'

    implementation project(':dwp-core')
    implementation project(':dwp-audit')
    implementation project(':dwp-observability')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
