INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n,
    sort_order, behavior_metadata, lifecycle_state)
VALUES
    ('AUTH.BUILT_IN_ROLE', 'DWAION_ADMIN', 'DWAI-ON administrator',
     '{"ko":"DWAI-ON 관리자","en":"DWAI-ON administrator"}', 130,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'DWAION_AGENT_EDITOR', 'DWAI-ON agent editor',
     '{"ko":"DWAI-ON 에이전트 편집자","en":"DWAI-ON agent editor"}', 131,
     '{"roleFamily":"WORKSPACE","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'DWAION_AGENT_PUBLISHER', 'DWAI-ON agent publisher',
     '{"ko":"DWAI-ON 에이전트 게시 책임자","en":"DWAI-ON agent publisher"}', 132,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'DWAION_AUDITOR', 'DWAI-ON auditor',
     '{"ko":"DWAI-ON 감사자","en":"DWAI-ON auditor"}', 133,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'DWAION_EVALUATOR', 'DWAI-ON evaluator',
     '{"ko":"DWAI-ON 평가자","en":"DWAI-ON evaluator"}', 134,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'DWAION_GOVERNANCE_MANAGER', 'DWAI-ON governance manager',
     '{"ko":"DWAI-ON 거버넌스 관리자","en":"DWAI-ON governance manager"}', 135,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'MAIL_ADMIN', 'Mail administrator',
     '{"ko":"메일 관리자","en":"Mail administrator"}', 136,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'MESSAGING_ADMIN', 'Messaging administrator',
     '{"ko":"메신저 관리자","en":"Messaging administrator"}', 137,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'NOTIFICATION_CONTRACT_OWNER', 'Notification contract owner',
     '{"ko":"알림 계약 소유자","en":"Notification contract owner"}', 138,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'NOTIFICATION_OPERATOR', 'Notification operator',
     '{"ko":"알림 운영자","en":"Notification operator"}', 139,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'NOTIFICATION_POLICY_APPROVER', 'Notification policy approver',
     '{"ko":"알림 정책 승인자","en":"Notification policy approver"}', 140,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'NOTIFICATION_TEMPLATE_EDITOR', 'Notification template editor',
     '{"ko":"알림 템플릿 편집자","en":"Notification template editor"}', 141,
     '{"roleFamily":"WORKSPACE","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SPACE_ACCESS_REVIEWER', 'Space access reviewer',
     '{"ko":"Space 접근 검토자","en":"Space access reviewer"}', 142,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SPACE_COMPLIANCE_REVIEWER', 'Space compliance reviewer',
     '{"ko":"Space 컴플라이언스 검토자","en":"Space compliance reviewer"}', 143,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SPACE_GOVERNANCE_ADMIN', 'Space governance administrator',
     '{"ko":"Space 거버넌스 관리자","en":"Space governance administrator"}', 144,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SPACE_TEMPLATE_ADMIN', 'Space template administrator',
     '{"ko":"Space 템플릿 관리자","en":"Space template administrator"}', 145,
     '{"roleFamily":"TENANT","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE')
ON CONFLICT (code_set_key, code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    label_i18n = EXCLUDED.label_i18n,
    sort_order = EXCLUDED.sort_order,
    behavior_metadata = EXCLUDED.behavior_metadata,
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP;
