-- Reconcile every closed database CHECK contract introduced since the last
-- cross-service registry sweep. The service schemas remain authoritative; this
-- migration only projects their exact values into the administrator-only catalog.

SELECT pg_advisory_xact_lock(
    hashtextextended('dwp-platform:system-code-registry', 0));

LOCK TABLE sys_code_sets, sys_code_values, sys_code_bindings
    IN SHARE ROW EXCLUSIVE MODE;

CREATE TEMP TABLE tmp_v322_check_contract_manifest (
    owner_service VARCHAR(80) NOT NULL,
    source_reference VARCHAR(240) NOT NULL,
    allowed_values VARCHAR[] NOT NULL,
    PRIMARY KEY (owner_service, source_reference),
    CONSTRAINT ck_tmp_v322_allowed_values_nonempty
        CHECK (cardinality(allowed_values) > 0)
) ON COMMIT DROP;

INSERT INTO tmp_v322_check_contract_manifest (
    owner_service, source_reference, allowed_values)
VALUES
    ('dwp-approval-server', 'apr_attachment_download_grants.owner_type', ARRAY['REQUEST', 'TASK']::VARCHAR[]),
    ('dwp-approval-server', 'apr_attachment_uploads.av_state', ARRAY['AV_CLEAR']::VARCHAR[]),
    ('dwp-approval-server', 'apr_attachment_uploads.passive_content_state', ARRAY['PASSIVE_ALLOWED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_attachment_uploads.state', ARRAY['AVAILABLE', 'CANCELLED', 'QUARANTINED', 'REJECTED', 'RESERVED', 'SCANNING', 'STORAGE_RECONCILING', 'UPLOADING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_export_jobs.access_level', ARRAY['AUDITOR', 'METADATA', 'PRIVILEGED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_export_jobs.external_attestation_type', ARRAY['KMS_SIGNATURE', 'QUALIFIED_ARCHIVE', 'WORM']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_export_jobs.integrity_status', ARRAY['DIGEST_VERIFIED', 'EXTERNAL_ATTESTED', 'FAILED', 'NOT_EVALUATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_export_jobs.status', ARRAY['COMPLETE', 'FAILED', 'PENDING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_saved_views.lifecycle_state', ARRAY['ACTIVE', 'ARCHIVED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_saved_views.visibility', ARRAY['PERSONAL', 'SHARED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_audit_verification_receipts.result', ARRAY['DIGEST_MISMATCH', 'VERIFIED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_business_calendars.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_commands.operation', ARRAY['CHANGE_CONNECTOR_LIFECYCLE', 'COMPLETE_PROBE', 'PUBLISH_CONNECTOR', 'SAVE_CONNECTOR_DRAFT', 'START_PROBE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_commands.status', ARRAY['SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_heads.connector_type', ARRAY['CUSTOM', 'ERP', 'KAFKA', 'REST', 'SIGNATURE', 'WEBHOOK']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_heads.lifecycle_state', ARRAY['ACTIVE', 'DISABLED', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_probe_runs.probe_kind', ARRAY['READINESS', 'SYNTHETIC_TEST']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_probe_runs.state', ARRAY['FAILED', 'PENDING', 'RUNNING', 'UNKNOWN_REMOTE_OUTCOME', 'VERIFIED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_revisions.idempotency_mode', ARRAY['BODY_HASH', 'HEADER', 'PROVIDER_NATIVE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_connector_revisions.signing_mode', ARRAY['HMAC_SHA256', 'JWS_ED25519', 'MTLS', 'NONE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_events.action', ARRAY['CANCEL_SCHEDULED', 'CREATE', 'KILL_SWITCH', 'REVIEW', 'REVOKE', 'UPDATE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.compliance_state', ARRAY['BLOCKED', 'EVIDENCE_REQUIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.disposition', ARRAY['ACKNOWLEDGED_FINDINGS', 'REMEDIATION_REQUESTED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.identity_separation_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.no_sub_delegation_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.role_snapshot_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.role_sod_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.scope_binding_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_delegation_governance_reviews.time_window_truth', ARRAY['NOT_VERIFIED', 'VERIFIED', 'VIOLATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_assets.asset_type', ARRAY['FORM', 'POLICY', 'TEMPLATE', 'WORKFLOW']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_assets.rollback_disposition', ARRAY['CONDITIONAL', 'IRREVERSIBLE', 'REVERSIBLE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_canary_controls.state', ARRAY['PAUSED', 'RUNNING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_environment_heads.environment', ARRAY['DEVELOPMENT', 'PRODUCTION', 'TEST']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_evidence.evidence_type', ARRAY['ACTIVATION', 'CANARY_HEALTH', 'ROLLBACK']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_evidence.observed_outcome', ARRAY['DEGRADED', 'FAILED', 'HEALTHY', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_packages.rollback_class', ARRAY['CONDITIONAL', 'IRREVERSIBLE', 'REVERSIBLE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_promotions.source_environment', ARRAY['DEVELOPMENT', 'PRODUCTION', 'TEST']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_promotions.status', ARRAY['ACTIVATING', 'ACTIVE', 'APPROVED', 'FAILED', 'PACKAGE_HEAD_RESTORED', 'PARTIAL', 'PENDING_REVIEW', 'ROLLBACK_PENDING', 'SCHEDULED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_promotions.target_environment', ARRAY['DEVELOPMENT', 'PRODUCTION', 'TEST']::VARCHAR[]),
    ('dwp-approval-server', 'apr_deployment_telemetry.observed_outcome', ARRAY['DEGRADED', 'FAILED', 'HEALTHY', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_document_hold_proposals.operation', ARRAY['PLACE', 'RELEASE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_draft_commands.command_type', ARRAY['CREATE', 'DELETE', 'RECOVER', 'RESTORE', 'UPDATE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_dwaion_proposal_handoff_events.delivery_state', ARRAY['COMPLETED', 'DEAD', 'DRAFT', 'PENDING', 'RETRY', 'SENDING', 'TERMINAL']::VARCHAR[]),
    ('dwp-approval-server', 'apr_dwaion_proposal_handoffs.action_key', ARRAY['APPROVAL.REQUEST.CREATE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_dwaion_proposal_handoffs.delivery_state', ARRAY['COMPLETED', 'DEAD', 'DRAFT', 'PENDING', 'RETRY', 'SENDING', 'TERMINAL']::VARCHAR[]),
    ('dwp-approval-server', 'apr_dwaion_proposal_handoffs.next_observation', ARRAY['COMPLETED', 'HANDED_OFF', 'RUNNING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_external_signature_artifacts.artifact_kind', ARRAY['AUDIT_TRAIL', 'CERTIFICATE', 'SIGNED_PDF', 'TSA', 'UNSIGNED_PDF']::VARCHAR[]),
    ('dwp-approval-server', 'apr_external_signature_events.state', ARRAY['CANCELLED', 'CANCEL_PENDING', 'COMPLETED_VERIFIED', 'COMPLETION_PENDING', 'FAILED', 'HANDOVER_PENDING', 'OUT_FOR_SIGNATURE', 'PREPARED', 'UNKNOWN_REMOTE_OUTCOME']::VARCHAR[]),
    ('dwp-approval-server', 'apr_external_signature_requests.state', ARRAY['CANCELLED', 'CANCEL_PENDING', 'COMPLETED_VERIFIED', 'COMPLETION_PENDING', 'FAILED', 'HANDOVER_PENDING', 'OUT_FOR_SIGNATURE', 'PREPARED', 'UNKNOWN_REMOTE_OUTCOME']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_lifecycle_events.action', ARRAY['BRANCH', 'PUBLISH', 'REINSTATE', 'RETIRE', 'REVIEW_REJECT', 'REVIEW_REQUEST', 'UPDATE_DRAFT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_publish_review_requests.request_status', ARRAY['PENDING', 'PUBLISHED', 'REJECTED', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_template_command_receipts.command_kind', ARRAY['CLONE_TEMPLATE', 'IMPORT_PACKAGE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_template_dependencies.dependency_kind', ARRAY['CATEGORY_KEY', 'DATA_SOURCE_PROVIDER', 'ROLE_CODE', 'WORKFLOW_KEY']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_template_versions.lifecycle_state', ARRAY['DRAFT', 'RELEASED', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_template_versions.schema_contract', ARRAY['DWP_APPROVAL_FORM_TYPED_V3']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_templates.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_templates.scope_kind', ARRAY['GLOBAL', 'TENANT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_v3_command_receipts.command_kind', ARRAY['ADD_FIELD', 'ARCHIVE_DRAFT', 'CLONE_DRAFT', 'CLONE_FIELD', 'DELETE_FIELD', 'INSTALL_TEMPLATE', 'REORDER_FIELDS', 'UPDATE_DRAFT', 'UPDATE_FIELD_PROPERTIES']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_v3_lifecycle_events.action', ARRAY['ADD_FIELD', 'ARCHIVE_DRAFT', 'CLONE_DRAFT', 'CLONE_FIELD', 'DELETE_FIELD', 'INSTALL_TEMPLATE', 'REORDER_FIELDS', 'UPDATE_DRAFT', 'UPDATE_FIELD_PROPERTIES']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_v3_versions.compatibility_mode', ARRAY['BACKWARD_COMPATIBLE', 'BREAKING', 'INITIAL', 'STRICT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_v3_versions.schema_contract', ARRAY['DWP_APPROVAL_FORM_TYPED_V3']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_v3_workspaces.lifecycle_state', ARRAY['ARCHIVED', 'DRAFT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_version_material.provenance', ARRAY['AUTHORING_SNAPSHOT', 'LEGACY_CAPTURE_TIME', 'PUBLISH_SNAPSHOT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_form_workspaces.catalog_availability', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_commands.operation', ARRAY['ADD_DIAGNOSTIC', 'CHANGE_STATUS', 'COMPLETE_STAGE', 'CREATE_PLAN', 'CREATE_REPORT', 'OPEN_INCIDENT', 'RECONCILE_PLAN', 'RECORD_DRY_RUN', 'RECORD_POSTMORTEM', 'START_STAGE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_commands.status', ARRAY['SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_diagnostics.diagnostic_kind', ARRAY['CONNECTOR', 'DELIVERY', 'METRIC', 'SUMMARY', 'TRACE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_recovery_plans.plan_kind', ARRAY['MIXED', 'REASSIGN', 'RECONCILE', 'REPLAY']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_recovery_plans.state', ARRAY['BLOCKED', 'COMPLETED', 'DRAFT', 'EXECUTING', 'FAILED', 'PARTIAL', 'UNKNOWN_REMOTE_OUTCOME', 'VALIDATED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_recovery_stages.action_kind', ARRAY['REASSIGN', 'RECONCILE', 'REPLAY', 'VERIFY']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_recovery_stages.state', ARRAY['FAILED', 'PENDING', 'RUNNING', 'SUCCEEDED', 'UNKNOWN_REMOTE_OUTCOME']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_recovery_stages.target_type', ARRAY['APPROVAL_TASK', 'CONNECTOR', 'OUTBOX_EVENT', 'POLICY']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_reports.report_format', ARRAY['EVIDENCE_JSON']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incident_timeline.event_type', ARRAY['DIAGNOSTIC_ADDED', 'OPENED', 'PLAN_CREATED', 'PLAN_VALIDATED', 'POSTMORTEM_RECORDED', 'RECONCILED', 'REPORT_CREATED', 'STAGE_COMPLETED', 'STAGE_STARTED', 'STATUS_CHANGED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incidents.severity', ARRAY['CRITICAL', 'HIGH', 'LOW', 'MEDIUM']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incidents.source_kind', ARRAY['CONNECTOR', 'DELIVERY', 'MANUAL', 'POLICY', 'WORKFLOW']::VARCHAR[]),
    ('dwp-approval-server', 'apr_incidents.status', ARRAY['CLOSED', 'INVESTIGATING', 'MITIGATING', 'MONITORING', 'OPEN', 'RESOLVED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_notification_channel_observations.readiness_state', ARRAY['DEGRADED', 'READY', 'STALE', 'UNAVAILABLE', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_notification_channels.channel_type', ARRAY['EMAIL', 'IN_APP', 'PUSH', 'SLACK', 'TEAMS', 'WEBHOOK']::VARCHAR[]),
    ('dwp-approval-server', 'apr_notification_channels.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_notification_channels.readiness_state', ARRAY['DEGRADED', 'NOT_CONFIGURED', 'READY', 'STALE', 'UNAVAILABLE', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_operation_batches.command_mode', ARRAY['BATCH', 'SINGLE']::VARCHAR[]),
    ('dwp-approval-server', 'apr_operation_batches.operation_type', ARRAY['DELIVERY_DEAD_LETTER', 'DELIVERY_RECONCILE', 'DELIVERY_REPLAY', 'DELIVERY_RETRY', 'TASK_REASSIGN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_operation_items.target_type', ARRAY['APPROVAL_TASK', 'OUTBOX_EVENT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_automation_commands.operation', ARRAY['CANCEL_SCHEDULED_DELEGATION', 'CREATE_DELEGATION', 'EXPORT_POLICY', 'KILL_SWITCH_DELEGATIONS', 'OBSERVE_CHANNEL', 'PUBLISH_POLICY', 'REVIEW_DELEGATION', 'REVIEW_POLICY', 'REVOKE_DELEGATION', 'SAVE_CALENDAR', 'SAVE_CHANNEL', 'SAVE_POLICY_DRAFT', 'SET_POLICY_FREEZE', 'SIMULATE_POLICY', 'UPDATE_DELEGATION']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_automation_commands.status', ARRAY['SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_automation_heads.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_automation_reviews.disposition', ARRAY['APPROVED', 'CHANGES_REQUESTED', 'REJECTED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_automation_simulations.outcome', ARRAY['BLOCKED', 'PASS', 'WARNING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_creation_commands.status', ARRAY['SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_policy_version_source_records.source_kind', ARRAY['LEGACY_CAPTURE_TIME', 'UNRECORDED_HISTORICAL_METADATA']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_information_admissions.operation', ARRAY['REPLY', 'REQUEST_INFO']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_information_commands.operation', ARRAY['REPLY', 'REQUEST_INFO']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_information_commands.status', ARRAY['COMPLETED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_information_rounds.status', ARRAY['OPEN', 'RESPONDED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_sla_timers.kind', ARRAY['BREACH', 'WARNING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_sla_timers.status', ARRAY['CANCELLED', 'CLAIMED', 'COMPLETED', 'PENDING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_stage_runtime.status', ARRAY['APPROVED', 'CANCELLED', 'IN_PROGRESS', 'REJECTED', 'SKIPPED', 'WAITING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_quorum_votes.decision', ARRAY['APPROVE', 'REJECT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_record_purge_objects.state', ARRAY['CLAIMED', 'CONFIRMED', 'PENDING', 'UNKNOWN', 'UNRESOLVED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_record_retention_heads.state', ARRAY['COMPLETE', 'IRREVERSIBLE', 'IRREVERSIBLE_BLOCKED', 'LIVE', 'LOCAL_DB_PURGED', 'OBJECTS_CONFIRMED', 'PREPARED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_dispatch_intents.state', ARRAY['BLOCKED', 'IRREVERSIBLE', 'LOCAL_DB_PURGED', 'QUEUED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_foreign_acknowledgements.outcome', ARRAY['DECLARED_COPIES_DELETED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_foreign_delivery_states.consumer_service', ARRAY['AUDIT', 'NOTIFICATION']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_foreign_delivery_states.state', ARRAY['ACKNOWLEDGED', 'BLOCKED', 'DISPATCHING', 'READY', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_foreign_requests.consumer_service', ARRAY['AUDIT', 'NOTIFICATION']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_managed_execution_events.outcome', ARRAY['BLOCKED', 'CLAIMED', 'RECOVERY_REQUESTED', 'SUCCEEDED', 'UNKNOWN', 'WAITING']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_managed_execution_events.stage', ARRAY['AUTHORITY', 'COMPLETE', 'FINALIZE', 'FOREIGN', 'LOCAL_DB', 'OBJECTS']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_managed_executions.stage', ARRAY['AUTHORITY', 'COMPLETE', 'FINALIZE', 'FOREIGN', 'LOCAL_DB', 'OBJECTS']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_managed_executions.state', ARRAY['BLOCKED', 'COMPLETE', 'READY', 'RUNNING', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_original_command_witnesses.canonical_algorithm', ARRAY['APPROVAL_STEP_UP_TYPED_JSON_SHA256_V1']::VARCHAR[]),
    ('dwp-approval-server', 'apr_retention_original_command_witnesses.operation', ARRAY['CLAIM_RECORD', 'INITIALIZE_POLICY', 'PUBLISH_POLICY', 'SAVE_POLICY']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_directory_commands.operation', ARRAY['ACTIVATE_GROUP', 'DRY_RUN_WORKFLOW', 'OBSERVE_RESOLVER', 'RECORD_USAGE', 'RETIRE_GROUP', 'RETIRE_WORKFLOW', 'SAVE_GROUP', 'SAVE_RESOLVER', 'SAVE_WORKFLOW_CANVAS']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_directory_commands.status', ARRAY['SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_group_members.member_kind', ARRAY['GROUP', 'RESOLVER', 'SUBJECT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_group_usages.usage_kind', ARRAY['DELEGATION', 'ESCALATION', 'POLICY', 'WORKFLOW']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_groups.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_resolver_observations.source_state', ARRAY['HEALTHY', 'STALE', 'UNAVAILABLE', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_resolvers.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_resolvers.resolver_kind', ARRAY['DIRECTORY_GROUP', 'MANAGER', 'ORG_ROLE', 'PROJECT_ROLE', 'STATIC_SUBJECT']::VARCHAR[]),
    ('dwp-approval-server', 'apr_routing_resolvers.source_state', ARRAY['HEALTHY', 'NOT_VERIFIED', 'STALE', 'UNAVAILABLE', 'UNKNOWN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestation_artifacts.renderer_version', ARRAY['DWP_SELF_ATTESTATION_JSON_V1']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestation_commands.operation', ARRAY['CANCEL', 'CONSENT', 'CREATE', 'SIGN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestation_consents.locale', ARRAY['en', 'ko']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestation_events.action', ARRAY['CANCEL', 'CONSENT', 'CREATE', 'SIGN']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestations.signer_kind', ARRAY['SELF_ATTESTATION']::VARCHAR[]),
    ('dwp-approval-server', 'apr_self_attestations.state', ARRAY['ATTESTED', 'AWAITING_CONSENT', 'CANCELLED', 'CONSENTED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_signature_provider_inspections.inspection_kind', ARRAY['KMS', 'WORM']::VARCHAR[]),
    ('dwp-approval-server', 'apr_signature_provider_probe_runs.operation', ARRAY['KMS_PROBE', 'PROBE', 'WORM_INSPECTION']::VARCHAR[]),
    ('dwp-approval-server', 'apr_signature_provider_probe_runs.state', ARRAY['COMPLETE', 'PARTIAL', 'PENDING', 'RUNNING', 'UNKNOWN_REMOTE_OUTCOME']::VARCHAR[]),
    ('dwp-approval-server', 'apr_steps.approval_mode', ARRAY['ALL', 'ANY', 'COUNT', 'PERCENT', 'SEQUENTIAL']::VARCHAR[]),
    ('dwp-approval-server', 'apr_system_sla_source_witnesses.original_classification', ARRAY['CONFIDENTIAL', 'INTERNAL', 'RESTRICTED']::VARCHAR[]),
    ('dwp-approval-server', 'apr_workflow_studio_events.action', ARRAY['DRY_RUN', 'RETIRE', 'SAVE_DRAFT']::VARCHAR[]),
    ('dwp-auth-server', 'auth_product_predicate_policy.owner_service_key', ARRAY['agent', 'approval', 'auth', 'meeting', 'messaging', 'notification', 'payroll', 'people', 'platform', 'space', 'time']::VARCHAR[]),
    ('dwp-auth-server', 'com_emergency_access_principals.verification_method', ARRAY['OPERATOR_ATTESTED', 'RECOVERY_DRILL_COMPLETED']::VARCHAR[]),
    ('dwp-auth-server', 'com_emergency_access_principals.verification_status', ARRAY['NOT_VERIFIED', 'OVERDUE', 'VERIFIED']::VARCHAR[]),
    ('dwp-auth-server', 'com_sso_test_login_receipts.external_probe_state', ARRAY['FAILED', 'NOT_REQUIRED', 'SUCCEEDED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-auth-server', 'com_sso_test_login_receipts.lifecycle_state', ARRAY['BLOCKED', 'FAILED', 'SUCCEEDED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_adoption_events.aggregate_type', ARRAY['INSTALLATION', 'WORKFORCE_ASSIGNMENT']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_installations.external_executor_state', ARRAY['NOT_REQUIRED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_installations.installation_kind', ARRAY['EXTERNAL_SERVICE', 'INTERNAL_AUTH_CONTROLLED']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_installations.lifecycle_state', ARRAY['APPROVED', 'DRAFT', 'ENABLED', 'IN_REVIEW', 'REJECTED', 'SUSPENDED']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_workforce_assignments.external_settlement_state', ARRAY['NOT_REQUIRED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_workforce_assignments.lifecycle_state', ARRAY['ACTIVE', 'APPROVED', 'DENIED', 'EXPIRED', 'PENDING_APPROVAL', 'REVOKED']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_workforce_assignments.principal_type', ARRAY['USER']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_app_workforce_assignments.source_type', ARRAY['INTERNAL_GROUP_PROJECTION', 'TENANT_DIRECT']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_capability_override_changes.desired_state', ARRAY['DISABLED', 'INHERIT']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_capability_override_changes.lifecycle_state', ARRAY['ACTIVE', 'APPROVED', 'DRAFT', 'IN_REVIEW', 'REJECTED', 'REVOKED', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_setting_change_sets.impact_confidence', ARRAY['ESTIMATED', 'EXACT', 'UNKNOWN']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_setting_change_sets.lifecycle_state', ARRAY['APPROVED', 'DRAFT', 'IN_REVIEW', 'PUBLISHED', 'REJECTED', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_setting_change_sets.owner_type', ARRAY['AUTH_POLICY']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_setting_override_changes.desired_state', ARRAY['INHERIT', 'VALUE']::VARCHAR[]),
    ('dwp-auth-server', 'com_tenant_setting_override_changes.lifecycle_state', ARRAY['APPROVED', 'DRAFT', 'IN_REVIEW', 'PUBLISHED', 'REJECTED', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_product_app_resource_mapping.lifecycle_state', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_capability_override_rules.lifecycle_state', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_capability_override_rules.override_mode', ARRAY['ALLOW_DISABLE', 'OWNER_LOCKED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_capability_override_rules.risk_tier', ARRAY['CRITICAL', 'HIGH', 'LOW', 'MEDIUM']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_capability_override_rules.scope_type', ARRAY['TENANT']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_setting_owner_registry.activation_mode', ARRAY['PUBLISH']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_setting_owner_registry.lifecycle_state', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_setting_owner_registry.override_policy', ARRAY['OWNER_LOCKED', 'TENANT_ALLOWED']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_setting_owner_registry.resolution_strategy', ARRAY['TENANT_OVERRIDE_OR_OWNER_DEFAULT']::VARCHAR[]),
    ('dwp-auth-server', 'sys_tenant_setting_owner_registry.value_type', ARRAY['BOOLEAN', 'INTEGER', 'OBJECT', 'STRING']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_chat_retention_evidence.deletion_reason', ARRAY['RETENTION_EXPIRED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_chat_retention_health.health_key', ARRAY['CHAT_RETENTION']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_facilitation_commands.operation', ARRAY['POLL_CLOSE', 'POLL_CREATE', 'POLL_OPEN', 'POLL_VOTE', 'QUESTION_ANSWER', 'QUESTION_ASK', 'QUESTION_DISMISS', 'QUESTION_UPVOTE', 'TIMER_ADVANCE', 'TIMER_PAUSE', 'TIMER_RESUME', 'TIMER_START']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_facilitation_polls.poll_state', ARRAY['CLOSED', 'DRAFT', 'OPEN']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_facilitation_questions.question_state', ARRAY['ANSWERED', 'DISMISSED', 'OPEN']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_facilitation_states.timer_state', ARRAY['COMPLETED', 'IDLE', 'PAUSED', 'RUNNING']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_followup_assertion_replay.action', ARRAY['CREATE', 'READ', 'REASSIGN']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_intelligence_auto_requests.request_state', ARRAY['FAILED', 'PENDING', 'RUNNING', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_invitation_notification_deliveries.delivery_state', ARRAY['ACCEPTED', 'CANCELLED', 'FAILED', 'PENDING', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_invitation_outbox.audience', ARRAY['CURRENT_INVITEES']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_invitation_outbox.delivery_state', ARRAY['CANCELLED', 'DELIVERED', 'FAILED', 'PENDING']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_invitation_outbox.event_type', ARRAY['MEETING_CANCELLED', 'MEETING_RESCHEDULED', 'MEETING_SCHEDULED', 'PREPARATION_MATERIAL_ADDED', 'PREPARATION_MATERIAL_REMOVED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_invitation_responses.response_state', ARRAY['ACCEPTED', 'DECLINED', 'NEEDS_RESPONSE', 'RECONFIRM_REQUIRED', 'TENTATIVE']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_material_retention_evidence.outcome', ARRAY['FAILED', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_material_retention_state.worker_key', ARRAY['PREPARATION_MATERIALS']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_occurrences.exception_state', ARRAY['CANCELLED', 'NONE', 'RESCHEDULED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_participant_disconnects.command_state', ARRAY['DISCONNECTED', 'PENDING', 'RUNNING']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_preparation_commands.operation', ARRAY['AGENDA_REPLACE', 'INVITATION_RESPOND', 'MATERIAL_REGISTER', 'MATERIAL_REMOVE', 'PREPARATION_CHECK']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_preparation_materials.access_verification_state', ARRAY['PENDING_REVALIDATION']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_preparation_materials.classification', ARRAY['CONFIDENTIAL', 'INTERNAL', 'RESTRICTED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_preparation_materials.lifecycle_state', ARRAY['ACTIVE', 'REMOVED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_preparation_materials.reference_provider', ARRAY['CONFLUENCE', 'DWP_FILES', 'SHAREPOINT']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_record_deletion_evidence.deletion_reason', ARRAY['RETENTION_EXPIRED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_record_retention_health.health_key', ARRAY['RECORD_RETENTION']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_record_retention_health.last_failure_code', ARRAY['RECORD_RETENTION_PURGE_FAILED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_commands.operation', ARRAY['CANCEL', 'RESCHEDULE']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_draft_commands.operation', ARRAY['DRAFT_COMMIT', 'DRAFT_DISCARD', 'DRAFT_SAVE']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_draft_commands.result_type', ARRAY['DISCARDED', 'DRAFT', 'MEETING']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_draft_retention_health.health_key', ARRAY['SCHEDULE_DRAFTS']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_drafts.access_scope', ARRAY['INTERNAL', 'INVITED']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_drafts.last_step', ARRAY['DETAILS', 'RECURRENCE', 'REVIEW', 'SCHEDULE']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_schedule_drafts.recurrence_frequency', ARRAY['MONTHLY', 'NONE', 'WEEKLY']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_series.frequency', ARRAY['MONTHLY', 'WEEKLY']::VARCHAR[]),
    ('dwp-meeting-server', 'vm_meeting_templates.template_scope', ARRAY['ORGANIZATION', 'PERSONAL']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_attention_governance_revisions.state', ARRAY['DRAFT', 'PUBLISHED', 'REJECTED', 'SUPERSEDED', 'WITHDRAWN']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_attention_rule_audit_outbox.effect', ARRAY['FOLLOW', 'MUTE', 'PRIORITIZE']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_attention_rule_audit_outbox.event_type', ARRAY['POLICY_LOCKED', 'RULE_CREATED', 'RULE_DELETED', 'RULE_UPDATED', 'TEST_DELIVERY_CREATED']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_attention_rule_audit_outbox.scope_kind', ARRAY['ACTOR', 'APP_TYPE', 'RESOURCE', 'THREAD', 'TOPIC_TOKEN']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_attention_rule_audit_outbox.subject_type', ARRAY['ATTENTION_RULE', 'TEST_DELIVERY']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_delivery_admission_receipts.attention_effect', ARRAY['FOLLOW', 'MUTE', 'PRIORITIZE']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_delivery_admission_receipts.attention_scope_kind', ARRAY['ACTOR', 'APP_TYPE', 'RESOURCE', 'THREAD', 'TOPIC_TOKEN']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_notification_quality_facts.attention_effect', ARRAY['FOLLOW', 'MUTE', 'PRIORITIZE']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_notification_quality_facts.attention_scope_kind', ARRAY['ACTOR', 'APP_TYPE', 'RESOURCE', 'THREAD', 'TOPIC_TOKEN']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_notification_quality_facts.decision', ARRAY['ADMITTED', 'RATE_LIMITED', 'SUPPRESSED']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_recipient_notification_contexts.kind', ARRAY['CHANNEL', 'CONVERSATION', 'PERSON', 'PROJECT', 'THREAD', 'TOPIC', 'WORK_ITEM']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_test_delivery_receipts.state', ARRAY['COMPLETED', 'EXPIRED', 'FAILED', 'PARTIAL', 'PENDING']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_attention_rule_channels.channel', ARRAY['EMAIL', 'IN_APP', 'MOBILE_PUSH', 'SLACK', 'TEAMS', 'WEB_PUSH']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_attention_rules.effect', ARRAY['FOLLOW', 'MUTE', 'PRIORITIZE']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_attention_rules.scope_kind', ARRAY['ACTOR', 'APP_TYPE', 'RESOURCE', 'THREAD', 'TOPIC_TOKEN']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_attention_rules.source', ARRAY['SYSTEM_DEFAULT', 'TENANT_POLICY', 'USER']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_delivery_endpoints.channel', ARRAY['MOBILE_PUSH', 'WEB_PUSH']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_delivery_endpoints.platform', ARRAY['ANDROID', 'IOS', 'WEB']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_delivery_endpoints.state', ARRAY['ACTIVE', 'EXPIRED', 'REVOKED']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_notifications.attention_effect', ARRAY['FOLLOW', 'PRIORITIZE']::VARCHAR[]),
    ('dwp-notification-server', 'ntf_user_notifications.attention_scope_kind', ARRAY['ACTOR', 'APP_TYPE', 'RESOURCE', 'THREAD', 'TOPIC_TOKEN']::VARCHAR[]),
    ('dwp-people-server', 'abs_mail_proposal_execution_receipts.execution_state', ARRAY['CLAIMED', 'EXECUTED']::VARCHAR[]),
    ('dwp-people-server', 'abs_mail_proposal_outcome_outbox.delivery_state', ARRAY['PENDING', 'PUBLISHED', 'UNKNOWN_RECONCILE']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_change_proposal_events.event_type', ARRAY['CANCELLED', 'CREATED', 'SUBMITTED', 'VALIDATED']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_change_proposals.change_type', ARRAY['CHANGE_LOCATION', 'CHANGE_MANAGER', 'CORRECTION', 'DEMOTION', 'PROMOTION', 'TRANSFER']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_change_proposals.lifecycle_state', ARRAY['CANCELLED', 'DRAFT', 'SUBMITTED', 'VALIDATED']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_command_receipts.lifecycle_state', ARRAY['IN_PROGRESS', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_command_receipts.originating_action', ARRAY['CANCEL', 'CREATE', 'SUBMIT', 'VALIDATE']::VARCHAR[]),
    ('dwp-people-server', 'ppl_assignment_proposal_outbox.status', ARRAY['FAILED', 'PENDING', 'PUBLISHED']::VARCHAR[]),
    ('dwp-platform-server', 'adm_tenant_widget_policy_revisions.channel', ARRAY['PREVIEW', 'STABLE']::VARCHAR[]),
    ('dwp-platform-server', 'adm_tenant_widget_policy_revisions.policy_state', ARRAY['DRAFT', 'PUBLISHED', 'REVOKED', 'SUPERSEDED']::VARCHAR[]),
    ('dwp-platform-server', 'adm_tenant_widget_policy_revisions.selector_type', ARRAY['CHANNEL', 'PINNED']::VARCHAR[]),
    ('dwp-platform-server', 'adm_tenant_widget_policy_revisions.sharing_policy', ARRAY['DISABLED', 'PRIVATE', 'TENANT']::VARCHAR[]),
    ('dwp-platform-server', 'cal_calendar_delegations.status', ARRAY['ACTIVE', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'cal_event_occurrence_overrides.event_type', ARRAY['FOCUS', 'MEETING', 'OUT_OF_OFFICE', 'REMINDER', 'TASK']::VARCHAR[]),
    ('dwp-platform-server', 'cal_event_occurrence_overrides.visibility', ARRAY['CONFIDENTIAL', 'DEFAULT', 'PRIVATE', 'PUBLIC']::VARCHAR[]),
    ('dwp-platform-server', 'cal_invitation_response_commands.result_response_status', ARRAY['ACCEPTED', 'DECLINED', 'TENTATIVE']::VARCHAR[]),
    ('dwp-platform-server', 'cal_user_settings.default_visibility', ARRAY['DETAILS', 'FREE_BUSY', 'PRIVATE']::VARCHAR[]),
    ('dwp-platform-server', 'cal_user_settings.settings_origin', ARRAY['TENANT_POLICY', 'USER']::VARCHAR[]),
    ('dwp-platform-server', 'cal_user_settings.speedy_meeting_mode', ARRAY['FIVE_TEN', 'STANDARD']::VARCHAR[]),
    ('dwp-platform-server', 'mail_action_proposals.owner_state', ARRAY['ACCEPTED', 'CANCELLED', 'EXECUTED', 'EXECUTING', 'FAILED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'mail_address_book_command_receipts.command_status', ARRAY['COMPLETED', 'IN_PROGRESS']::VARCHAR[]),
    ('dwp-platform-server', 'mail_address_book_command_receipts.command_type', ARRAY['CONTACT_CREATE', 'GROUP_CREATE', 'GROUP_MEMBERS_REPLACE', 'GROUP_MESSAGE_SEND']::VARCHAR[]),
    ('dwp-platform-server', 'mail_compose_attachments.scan_state', ARRAY['BLOCKED', 'FAILED', 'READY', 'SCANNING', 'UPLOADING']::VARCHAR[]),
    ('dwp-platform-server', 'mail_connection_operations.operation_kind', ARRAY['DIAGNOSTIC', 'SYNC', 'TEST_SEND']::VARCHAR[]),
    ('dwp-platform-server', 'mail_connection_operations.operation_state', ARRAY['ACCEPTED', 'FAILED', 'RUNNING', 'SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'mail_contact_groups.lifecycle_state', ARRAY['ACTIVE', 'ARCHIVED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_contacts.lifecycle_state', ARRAY['ACTIVE', 'ARCHIVED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_contacts.source_kind', ARRAY['DIRECTORY', 'MANUAL']::VARCHAR[]),
    ('dwp-platform-server', 'mail_delivery_audit_exports.export_kind', ARRAY['DELIVERY_AUDIT', 'RETENTION_EVIDENCE']::VARCHAR[]),
    ('dwp-platform-server', 'mail_delivery_audit_exports.export_state', ARRAY['EXPIRED', 'FAILED', 'PENDING_APPROVAL', 'READY']::VARCHAR[]),
    ('dwp-platform-server', 'mail_delivery_outbox.delivery_status', ARRAY['CANCELLED', 'DELIVERED', 'FAILED', 'LEASED', 'QUEUED', 'RETRY_WAIT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_delivery_recovery_events.action_kind', ARRAY['CANCEL', 'RECONCILE', 'RETRY']::VARCHAR[]),
    ('dwp-platform-server', 'mail_delivery_recovery_events.result_state', ARRAY['BLOCKED', 'FAILED', 'SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'mail_draft_options.body_format', ARRAY['HTML', 'TEXT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_evidence_export_approvals.decision', ARRAY['APPROVED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_follow_up_notification_ledger.decision', ARRAY['CLAIMED', 'EMITTED', 'SUPPRESSED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_follow_up_trackers.tracker_status', ARRAY['CANCELLED', 'OVERDUE', 'REPLIED', 'WAITING']::VARCHAR[]),
    ('dwp-platform-server', 'mail_group_send_history.receipt_state', ARRAY['ACCEPTED', 'CANCELLED', 'DELIVERED', 'FAILED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'mail_group_send_history.recipient_mode', ARRAY['BCC', 'TO']::VARCHAR[]),
    ('dwp-platform-server', 'mail_legal_hold_release_approvals.decision', ARRAY['APPROVE', 'REJECT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_legal_holds.hold_status', ARRAY['ACTIVE', 'EXPIRED', 'RELEASED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_policy_history.apply_result', ARRAY['APPLIED', 'FAILED', 'PARTIAL', 'PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'mail_purge_jobs.job_state', ARRAY['ACCEPTED', 'FAILED', 'PARTIAL', 'RUNNING', 'SUCCEEDED', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'mail_purge_jobs.verification_state', ARRAY['FAILED', 'PENDING', 'UNKNOWN', 'VERIFIED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_shared_inbox_access_grants.member_state', ARRAY['ACTIVE', 'PENDING', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_shared_inbox_access_grants.provider_state', ARRAY['APPLIED', 'PARTIAL', 'PENDING', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'mail_signatures.body_format', ARRAY['HTML', 'TEXT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_signatures.lifecycle_state', ARRAY['ACTIVE', 'ARCHIVED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_signatures.publication_state', ARRAY['APPROVED', 'DRAFT', 'PENDING_APPROVAL', 'PRIVATE', 'PUBLISHED', 'RETIRED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_signatures.signature_scope', ARRAY['ACCOUNT', 'ORGANIZATION', 'PERSONAL']::VARCHAR[]),
    ('dwp-platform-server', 'mail_templates.body_format', ARRAY['HTML', 'TEXT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_templates.lifecycle_state', ARRAY['ACTIVE', 'ARCHIVED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_templates.publication_state', ARRAY['APPROVED', 'DRAFT', 'PENDING_APPROVAL', 'PRIVATE', 'PUBLISHED', 'RETIRED']::VARCHAR[]),
    ('dwp-platform-server', 'mail_templates.template_scope', ARRAY['ACCOUNT', 'ORGANIZATION', 'PERSONAL']::VARCHAR[]),
    ('dwp-platform-server', 'mail_user_preferences.density', ARRAY['COMFORTABLE', 'COMPACT']::VARCHAR[]),
    ('dwp-platform-server', 'mail_user_preferences.remote_images', ARRAY['ALLOW', 'ASK', 'BLOCK']::VARCHAR[]),
    ('dwp-platform-server', 'personal_work_calendar_links.state', ARRAY['LINKED', 'REMOVED']::VARCHAR[]),
    ('dwp-platform-server', 'personal_work_tasks.priority', ARRAY['HIGH', 'LOW', 'NORMAL', 'URGENT']::VARCHAR[]),
    ('dwp-platform-server', 'personal_work_tasks.status', ARRAY['ARCHIVED', 'COMPLETED', 'IN_PROGRESS', 'OPEN', 'WAITING']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoff_events.delivery_state', ARRAY['COMPLETED', 'DEAD', 'PENDING', 'RETRY', 'SENDING', 'TERMINAL']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.action_key', ARRAY['CALENDAR.EVENT.CREATE', 'MAIL.DRAFT.CREATE', 'SERVICE.REQUEST.CREATE']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.delivery_state', ARRAY['COMPLETED', 'DEAD', 'PENDING', 'RETRY', 'SENDING', 'TERMINAL']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.domain_name', ARRAY['CALENDAR', 'MAIL', 'SERVICE']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.domain_operation', ARRAY['DRAFT_CREATE', 'EVENT_CREATE', 'REQUEST_CREATE']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.domain_status', ARRAY['CONFIRMED', 'DRAFT', 'SUBMITTED', 'TENTATIVE']::VARCHAR[]),
    ('dwp-platform-server', 'platform_dwaion_proposal_handoffs.next_observation', ARRAY['COMPLETED', 'HANDED_OFF', 'RUNNING']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definition_versions.certification_status', ARRAY['EXPIRED', 'FAIL', 'NOT_RUN', 'PASS', 'WAIVED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definition_versions.release_state', ARRAY['BLOCKED', 'DEPRECATED', 'PUBLISHED', 'UNPUBLISHED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definition_versions.safety_state', ARRAY['CLEAR', 'QUARANTINED', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definition_versions.workflow_state', ARRAY['APPROVED', 'DRAFT', 'REJECTED', 'SUBMITTED', 'VALIDATED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definitions.data_classification', ARRAY['CONFIDENTIAL', 'INTERNAL', 'PUBLIC', 'RESTRICTED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definitions.definition_state', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_definitions.risk_tier', ARRAY['HIGH', 'LOW', 'MEDIUM']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_evidence.evidence_status', ARRAY['EXPIRED', 'FAIL', 'PASS', 'WAIVED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_evidence.evidence_type', ARRAY['A11Y', 'LOCALIZATION', 'MANIFEST', 'PERFORMANCE', 'PRIVACY', 'SECURITY']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_instances.instance_state', ARRAY['ACTIVE', 'BLOCKED', 'REMOVED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_registry_state.migration_mode', ARRAY['AUTHORITATIVE', 'SHADOW', 'STATIC']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_release_channels.channel', ARRAY['PREVIEW', 'STABLE']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_renderer_bindings.binding_state', ARRAY['ACTIVE', 'DISABLED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_renderer_bindings.kind', ARRAY['NATIVE']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_runtime_controls.control_scope', ARRAY['CATALOG_DISCOVERY', 'CATALOG_MUTATIONS', 'RUNTIME_ACTION', 'RUNTIME_RENDER']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_runtime_controls.control_state', ARRAY['DISABLED', 'ENABLED', 'EXPIRED']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_runtime_controls.target_id', ARRAY['CLASSIC', 'FLOW_V1', 'MZ_V1']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_runtime_controls.target_type', ARRAY['ACTION', 'DEFINITION', 'GLOBAL', 'MODE', 'PROVIDER', 'TENANT', 'VERSION']::VARCHAR[]),
    ('dwp-platform-server', 'plt_widget_runtime_enable_approvals.approval_state', ARRAY['ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'usr_home_owner_action_receipts.receipt_state', ARRAY['COMPLETED', 'PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'usr_home_preferences.current_mode', ARRAY['CLASSIC', 'FLOW_V1', 'MZ_V1']::VARCHAR[]),
    ('dwp-platform-server', 'usr_home_view_device_layouts.device_class', ARRAY['DESKTOP', 'DESKTOP_STANDARD', 'DESKTOP_WIDE', 'MOBILE', 'MOBILE_COMPACT', 'MOBILE_STANDARD']::VARCHAR[]),
    ('dwp-platform-server', 'usr_home_views.mode_key', ARRAY['CLASSIC', 'FLOW_V1', 'MZ_V1']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_consents.consent_state', ARRAY['GRANTED', 'WITHDRAWN']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_consents.source', ARRAY['ACCOUNT_SETTINGS']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_request_events.event_type', ARRAY['FULFILLMENT_BOUNDARY_RECORDED', 'REQUEST_CANCELLED', 'REQUEST_RECEIVED']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_request_events.request_state', ARRAY['CANCELLED', 'RECEIVED']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_request_receipts.evidence_state', ARRAY['INTAKE_ONLY']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_request_receipts.receipt_type', ARRAY['INTAKE']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_requests.request_state', ARRAY['CANCELLED', 'RECEIVED']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_privacy_requests.request_type', ARRAY['ACCOUNT_DELETION', 'DATA_EXPORT']::VARCHAR[]),
    ('dwp-platform-server', 'usr_personal_setting_activity.activity_type', ARRAY['CHANGE', 'VIEW']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignment_command_receipts.operation', ARRAY['ACCEPT', 'CANCEL', 'COMPLETE', 'CREATE', 'DECLINE', 'REASSIGN', 'START', 'WAIT']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignment_events.action', ARRAY['ACCEPT', 'CANCEL', 'COMPLETE', 'CREATE', 'DECLINE', 'REASSIGN', 'START', 'WAIT']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignment_events.assignment_state', ARRAY['ACCEPTED', 'DECLINED', 'PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignment_events.work_state', ARRAY['CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'OPEN', 'WAITING']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignments.assignment_state', ARRAY['ACCEPTED', 'DECLINED', 'PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignments.priority', ARRAY['HIGH', 'LOW', 'NORMAL', 'URGENT']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignments.source_system', ARRAY['MEETING_FOLLOWUP']::VARCHAR[]),
    ('dwp-platform-server', 'work_assignments.work_state', ARRAY['CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'OPEN', 'WAITING']::VARCHAR[]),
    ('dwp-platform-server', 'wp_alternative_offers.offer_state', ARRAY['ACCEPTED', 'ACCEPTING', 'EXPIRED', 'OFFERED', 'RESULT_UNKNOWN', 'WITHDRAWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_commands.command_type', ARRAY['CONFIRM_REQUEST', 'CREATE_REQUEST', 'SUBMIT_FEEDBACK', 'UPDATE_GOVERNANCE', 'VALIDATE_REQUEST']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_feedback.rating', ARRAY['HELPFUL', 'NOT_HELPFUL']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_governance.redaction_state', ARRAY['BLOCKED', 'READY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_proposal_items.policy_result', ARRAY['ALLOWED', 'CONFLICT', 'DENIED', 'UNAVAILABLE', 'UNVALIDATED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_requests.redaction_state', ARRAY['APPLIED', 'NOT_REQUIRED', 'RETAINED_CONTENT_DELETED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_assistant_requests.request_state', ARRAY['AWAITING_CONFIRMATION', 'FAILED', 'PARTIAL', 'PROCESSING', 'RESULT_UNKNOWN', 'SUCCEEDED', 'SUGGESTED', 'VALIDATED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_batch_items.authority', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_batch_items.item_state', ARRAY['COMPENSATED', 'COMPENSATION_FAILED', 'COMPENSATION_PENDING', 'FAILED', 'PENDING', 'PROCESSING', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_batches.batch_state', ARRAY['ACCEPTED', 'COMPENSATED', 'COMPENSATING', 'FAILED', 'PARTIAL', 'PROCESSING', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_batches.failure_policy', ARRAY['COMPENSATE_ALL', 'KEEP_SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_commands.command_type', ARRAY['CANCEL', 'CHECK_IN', 'RELEASE', 'RELOCATE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_delegate_grants.grant_state', ARRAY['ACTIVE', 'EXPIRED', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_intent_items.decision', ARRAY['ALTERNATIVES_AVAILABLE', 'AVAILABLE', 'POLICY_DENIED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_intent_items.resource_type', ARRAY['DESK', 'EQUIPMENT', 'FOCUS_POD', 'LOCKER', 'PARKING', 'PHONE_BOOTH', 'ROOM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_booking_intents.intent_state', ARRAY['COMPLETED', 'CONFIRMING', 'EXPIRED', 'HELD', 'PREVIEWED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_connector_replay_jobs.replay_state', ARRAY['DISPATCHING', 'FAILED', 'QUEUED', 'RESULT_UNKNOWN', 'RUNNING', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_connector_runtime_observations.reported_state', ARRAY['DEGRADED', 'HEALTHY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_connector_runtime_truth.reported_state', ARRAY['DEGRADED', 'HEALTHY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_connector_configurations.connector_kind', ARRAY['ACCESS_CONTROL', 'ACTUAL_PRESENCE', 'CALENDAR', 'FACILITY_WORK_ORDER', 'SIGNAGE', 'VEHICLE', 'VISITOR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_facility_closures.closure_status', ARRAY['ACTIVE', 'CANCELLED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_facility_requests.category', ARRAY['ACCESS', 'CLEANING', 'OTHER', 'REPAIR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_facility_requests.priority', ARRAY['CRITICAL', 'HIGH', 'LOW', 'NORMAL']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_facility_requests.request_status', ARRAY['CANCELLED', 'IN_PROGRESS', 'OPEN', 'RESOLVED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_resource_photos.content_type', ARRAY['image/jpeg', 'image/png']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_sharing_policies.maximum_visibility', ARRAY['FLOOR', 'PRIVATE', 'RESOURCE', 'SITE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_sharing_preferences.visibility', ARRAY['FLOOR', 'PRIVATE', 'RESOURCE', 'SITE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_work_plans.plan_mode', ARRAY['OFF', 'OFFICE', 'REMOTE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_experience_work_plans.visibility', ARRAY['FLOOR', 'PRIVATE', 'RESOURCE', 'SITE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_command_items.reservation_owner', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_command_items.result_state', ARRAY['FAILED', 'PENDING', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_command_items.selected_action', ARRAY['CANCEL', 'KEEP', 'REPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_commands.command_state', ARRAY['ACCEPTED', 'EXECUTING', 'FAILED', 'PARTIAL', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_impact_items.reservation_owner', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_impact_previews.reservation_owner', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_notification_events.impact_action', ARRAY['CANCEL', 'KEEP', 'REPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_facility_closure_notification_operations.operation_type', ARRAY['RECONCILE', 'RETRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_hold_release_commands.command_state', ARRAY['RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_access_pass_commands.command_state', ARRAY['FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_access_pass_commands.command_type', ARRAY['ISSUE', 'REVOKE', 'ROTATE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_access_pass_previews.command_type', ARRAY['ISSUE', 'REVOKE', 'ROTATE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_access_passes.lifecycle_state', ARRAY['ACTIVE', 'EXPIRED', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_admin_commands.command_type', ARRAY['DEVICE_APPROVE', 'DEVICE_BIND', 'DEVICE_COMMAND_PREVIEW', 'PROVIDER_CONFIGURE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_admin_commands.resource_type', ARRAY['DEVICE', 'PROVIDER_TRUTH']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_admin_commands.result_type', ARRAY['DEVICE', 'DEVICE_COMMAND_PREVIEW', 'PROVIDER_TRUTH']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_command_previews.command_type', ARRAY['CLEAR_CACHE', 'CLEAR_SAFETY', 'FORCE_SYNC', 'REBOOT', 'SAFETY_TAKEOVER', 'UNBIND']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_device_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'RUNNING', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_device_outbox.delivery_state', ARRAY['DEAD_LETTER', 'DELIVERED', 'PENDING', 'PROCESSING', 'RESULT_UNKNOWN', 'RETRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_devices.device_type', ARRAY['ROOM_PANEL', 'STATUS_BOARD']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_devices.registration_state', ARRAY['APPROVED', 'BOUND', 'PENDING', 'RETIRED', 'SUSPENDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_edges.travel_mode', ARRAY['ELEVATOR', 'RAMP', 'STAIR', 'WALK']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_graph_commands.command_type', ARRAY['ARCHIVE', 'CREATE', 'PUBLISH', 'REVIEW']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_graph_revisions.lifecycle_state', ARRAY['ARCHIVED', 'DRAFT', 'PUBLISHED', 'REVIEW']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_nodes.node_kind', ARRAY['ELEVATOR', 'ENTRY', 'HELP_DESK', 'JUNCTION', 'POI', 'RAMP', 'STAIR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_pois.category', ARRAY['AED', 'ASSEMBLY_POINT', 'ELEVATOR', 'EMERGENCY_EXIT', 'ENTRY', 'HELP_DESK', 'OTHER', 'PRINTER', 'RESTROOM', 'ROOM', 'STAIR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_provider_truth.capability', ARRAY['BLE', 'GRAPH', 'MDM', 'MTLS', 'NFC', 'SENSOR', 'SPEED_GATE', 'TPM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_provider_truth.reported_state', ARRAY['DEGRADED', 'HEALTHY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_navigation_safety_frames.frame_state', ARRAY['ACTIVE', 'CLEARED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_reservation_holds.hold_state', ARRAY['ACTIVE', 'BATCHED', 'CONSUMED', 'EXPIRED', 'RELEASED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_resource_command_previews.command_type', ARRAY['LOCKER_UNLOCK', 'NFC_KEY_RESEND', 'PARKING_EXIT_STATUS', 'PARKING_EXTEND', 'ROOM_PRE_ENTRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_resource_command_previews.provider_capability', ARRAY['NFC', 'SPEED_GATE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_resource_commands.command_state', ARRAY['FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_resource_commands.command_type', ARRAY['LOCKER_UNLOCK', 'NFC_KEY_RESEND', 'PARKING_EXIT_STATUS', 'PARKING_EXTEND', 'ROOM_PRE_ENTRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_activation_previews.severity', ARRAY['ADVISORY', 'CRITICAL', 'URGENT']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_audience_snapshots.owner_type', ARRAY['ACTIVATION_PREVIEW', 'INCIDENT', 'SCOPE_REVISION']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_audience_sources.availability_state', ARRAY['AVAILABLE', 'PARTIAL', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_audience_sources.freshness_state', ARRAY['FRESH', 'STALE', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_audience_sources.source_kind', ARRAY['ACTUAL_PRESENCE', 'RESERVATION', 'SCHEDULED_VISITOR', 'VISITOR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_closure_requests.request_state', ARRAY['APPROVED', 'PENDING_APPROVAL', 'REJECTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'RUNNING', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_commands.command_type', ARRAY['ACTIVATE', 'APPROVE_CLOSURE', 'CONFIGURE_CONNECTOR', 'CONFIGURE_EMERGENCY_CONTACT', 'CONFIRM_ASSEMBLY', 'CREATE_EXPORT', 'EMERGENCY_HANDOFF', 'PREVIEW_ACTIVATION', 'PREVIEW_CLOSURE', 'PREVIEW_EMERGENCY_HANDOFF', 'PREVIEW_SCOPE', 'RECONCILE_EMERGENCY_HANDOFF', 'REQUEST_CLOSURE', 'RESEND', 'RESPOND', 'REVISE_SCOPE', 'SEND_MESSAGE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_connector_truth.connector_kind', ARRAY['BLE_MESH', 'EBS', 'EMERGENCY_119', 'GOVERNMENT_LOG', 'WORM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_connector_truth.reported_state', ARRAY['DEGRADED', 'READY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_dispatch_attempts.attempt_state', ARRAY['DELIVERED', 'DELIVERY_FAILED', 'DISPATCHING', 'OFFLINE_QUEUED', 'QUEUED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_dispatch_attempts.channel', ARRAY['APP_PUSH', 'BLE_MESH', 'EBS', 'EMAIL', 'SMS']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_dispatch_batches.batch_kind', ARRAY['ACTIVATION', 'MESSAGE', 'RESEND', 'SCOPE_REVISION']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_dispatch_batches.dispatch_state', ARRAY['ACCEPTED', 'DISPATCHING', 'FAILED', 'PARTIAL', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_dispatch_receipts.receipt_state', ARRAY['DELIVERED', 'DELIVERY_FAILED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_emergency_contacts.action_mode', ARRAY['GOVERNED_HANDOFF', 'TEL_URI']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_emergency_contacts.connector_kind', ARRAY['EMERGENCY_119']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_emergency_contacts.contact_kind', ARRAY['HOTLINE', 'PUBLIC_EMERGENCY', 'RADIO']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_emergency_handoff_previews.provider_state', ARRAY['CONFIGURED_UNVERIFIED', 'DEGRADED', 'NOT_CONFIGURED', 'READY', 'STALE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_emergency_handoffs.handoff_state', ARRAY['FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_guarded_exports.export_format', ARRAY['CSV', 'PDF']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_incidents.incident_state', ARRAY['ACTIVE', 'CANCELLED', 'CLOSED', 'CLOSURE_PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_incidents.severity', ARRAY['ADVISORY', 'CRITICAL', 'URGENT']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_messages.direction', ARRAY['COMMAND_BROADCAST', 'COMMAND_TO_USER', 'USER_TO_COMMAND']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_outbox.delivery_state', ARRAY['DEAD_LETTER', 'DELIVERED', 'PENDING', 'PROCESSING', 'RESULT_UNKNOWN', 'RETRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_outbox.operation_type', ARRAY['DISPATCH_BATCH', 'SEND_MESSAGE', 'WRITE_GOVERNMENT_LOG', 'WRITE_WORM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_presence_observations.presence_state', ARRAY['DEPARTED', 'PRESENT', 'UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_responses.response_state', ARRAY['NEEDS_HELP', 'SAFE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_safety_scope_revisions.revision_state', ARRAY['APPLIED', 'EXPIRED', 'PREVIEW']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_capacity_holds.hold_state', ARRAY['COMMITTED', 'EXPIRED', 'HELD', 'RELEASED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_catalog_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_catalog_items.capacity_mode', ARRAY['BUCKETED', 'UNBOUNDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_catalog_items.category', ARRAY['AV', 'CATERING', 'CLEANING', 'IT_SUPPORT', 'ROOM_LAYOUT']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_catalog_items.inspection_mode', ARRAY['NONE', 'OPERATOR', 'REQUESTER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_catalog_items.lifecycle_state', ARRAY['ACTIVE', 'INACTIVE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_contact_requests.contact_state', ARRAY['DELIVERED', 'FAILED', 'QUEUED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_contact_requests.target_type', ARRAY['ASSIGNEE', 'SERVICE_DESK']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_ephemeral_access_grants.grant_state', ARRAY['EXPIRED', 'ISSUED', 'RESULT_UNKNOWN', 'REVOKED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_ephemeral_access_grants.provider_operation_kind', ARRAY['ISSUE', 'LEGACY_UNKNOWN', 'REVOKE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_fulfillment_tasks.task_state', ARRAY['ACCEPTED', 'BLOCKED', 'CANCELLED', 'DELAYED', 'FULFILLED', 'IN_PREPARATION', 'NOT_CONFIGURED', 'PARTIALLY_FULFILLED', 'RESULT_UNKNOWN', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_inspection_attempts.decision', ARRAY['FAILED', 'PASSED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_inspection_attempts.inspection_mode', ARRAY['OPERATOR', 'REQUESTER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_inspection_attempts.inspector_role', ARRAY['OPERATOR', 'REQUESTER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_line_adjustments.adjustment_state', ARRAY['CANCELLATION_PENDING', 'CANCELLATION_SUCCEEDED', 'FAILED', 'RECONCILIATION_PENDING', 'REFUNDED', 'REFUND_NOT_CONFIGURED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_line_adjustments.adjustment_type', ARRAY['CANCEL_REFUND']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_line_adjustments.refund_scope', ARRAY['FULL', 'NONE', 'PARTIAL']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_line_cancellation_previews.refund_scope', ARRAY['FULL', 'NONE', 'PARTIAL']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_operations_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_attachments.scan_state', ARRAY['CLEAN', 'ERROR', 'INFECTED', 'NOT_CONFIGURED', 'QUARANTINED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_events.event_type', ARRAY['ACCEPTED', 'ACCESS_CREDENTIAL_ISSUED', 'ACCESS_CREDENTIAL_REVOKED', 'ASSIGNEE_ASSIGNED', 'ATTACHMENT_LINKED', 'ATTACHMENT_SCAN_UPDATED', 'BLOCKED', 'CANCELLED', 'CONTACT_REQUESTED', 'DELAYED', 'FULFILLED', 'INSPECTION_FAILED', 'INSPECTION_PASSED', 'LINE_ADJUSTMENT_RECONCILED', 'LINE_CANCELLATION_FAILED', 'LINE_CANCELLATION_REQUIRES_REVIEW', 'LINE_CANCELLATION_RESULT_UNKNOWN', 'LINE_CANCELLED', 'MESSAGE_ADDED', 'PARTIALLY_FULFILLED', 'PREPARATION_STARTED', 'RESERVATION_IMPACT_CHANGED', 'RESULT_UNKNOWN', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_lines.category', ARRAY['AV', 'CATERING', 'CLEANING', 'IT_SUPPORT', 'ROOM_LAYOUT']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_lines.inspection_mode', ARRAY['NONE', 'OPERATOR', 'REQUESTER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_lines.line_state', ARRAY['ACCEPTED', 'BLOCKED', 'CANCELLED', 'DELAYED', 'FULFILLED', 'IN_PREPARATION', 'NOT_CONFIGURED', 'PARTIALLY_FULFILLED', 'RESULT_UNKNOWN', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_messages.author_role', ARRAY['OPERATOR', 'REQUESTER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_order_previews.reservation_authority', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_orders.order_state', ARRAY['ACCEPTED', 'BLOCKED', 'CANCELLED', 'DELAYED', 'FULFILLED', 'IN_PREPARATION', 'PARTIALLY_FULFILLED', 'RESULT_UNKNOWN', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_orders.reservation_authority', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_orders.reservation_impact', ARRAY['CANCELLATION_REVIEW', 'NONE', 'RECONFIRMATION_REQUIRED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_provider_profiles.lifecycle_state', ARRAY['ACTIVE', 'DRAFT', 'RETIRED', 'SUSPENDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_provider_truth.reported_state', ARRAY['DEGRADED', 'HEALTHY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_service_provider_verifications.reported_state', ARRAY['DEGRADED', 'HEALTHY', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_booking_impact_previews.impact_state', ARRAY['COMPUTE_FAILED', 'READY', 'SCOPE_INCOMPLETE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_commands.command_state', ARRAY['FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_commands.command_type', ARRAY['APPROVE', 'BOOKING_IMPACT_PREVIEW', 'CREATE', 'PREVIEW', 'PUBLISH', 'REJECT', 'SUBMIT', 'UPDATE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_commands.resulting_scenario_state', ARRAY['APPROVED', 'DRAFT', 'PREVIEWED', 'PUBLISHED', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_emission_evidence.evidence_kind', ARRAY['APPROVED_MODEL', 'METER']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_forecasts.forecast_state', ARRAY['COMPUTE_FAILED', 'DATA_INSUFFICIENT', 'PARTIAL', 'READY', 'STALE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_forecasts.resource_type', ARRAY['DESK', 'EQUIPMENT', 'FOCUS_POD', 'LOCKER', 'PARKING', 'PHONE_BOOTH', 'ROOM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_outbox.delivery_state', ARRAY['FAILED', 'PENDING', 'PUBLISHED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_report_audit_events.event_type', ARRAY['CONTENT_ACCESSED', 'PREVIEW_CREATED', 'REPORT_EXPORTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_report_commands.command_state', ARRAY['FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_report_commands.document_mime', ARRAY['application/pdf', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_report_commands.report_format', ARRAY['PDF', 'XLSX']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_report_previews.report_format', ARRAY['PDF', 'XLSX']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_scenario_previews.forecast_state', ARRAY['COMPUTE_FAILED', 'DATA_INSUFFICIENT', 'PARTIAL', 'READY', 'STALE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_scenarios.lifecycle_state', ARRAY['APPROVED', 'DRAFT', 'PREVIEWED', 'PUBLISHED', 'SUBMITTED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_scenarios.resource_type', ARRAY['DESK', 'EQUIPMENT', 'FOCUS_POD', 'LOCKER', 'PARKING', 'PHONE_BOOTH', 'ROOM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_source_observations.availability_state', ARRAY['AVAILABLE', 'COMPUTE_FAILED', 'PARTIAL', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_source_observations.resource_type', ARRAY['DESK', 'EQUIPMENT', 'FOCUS_POD', 'LOCKER', 'PARKING', 'PHONE_BOOTH', 'ROOM']::VARCHAR[]),
    ('dwp-platform-server', 'wp_space_planning_source_observations.series_kind', ARRAY['ACCESS', 'CHECK_IN', 'NO_SHOW', 'RESERVATION', 'SENSOR_OCCUPANCY', 'WORK_PLAN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_commands.command_state', ARRAY['ACCEPTED', 'FAILED', 'RESULT_UNKNOWN', 'SUCCEEDED']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_management_commands.resource_type', ARRAY['DEVICE', 'POLICY', 'PROVIDER', 'ZONE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_outbox.delivery_state', ARRAY['DEAD_LETTER', 'DELIVERED', 'PENDING', 'PROCESSING', 'RESULT_UNKNOWN', 'RETRY']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_outbox.operation_type', ARRAY['CHECK_PROVIDER_STATUS', 'NOTIFY_HOST', 'REQUEST_ACCESS', 'REVOKE_ACCESS', 'SEND_INVITATION']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_outbox.provider_kind', ARRAY['ACCESS', 'VISITOR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_previews.reservation_authority', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_provider_bindings.provider_kind', ARRAY['ACCESS', 'VISITOR']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_provider_bindings.reported_state', ARRAY['CONFIGURED_UNVERIFIED', 'DEGRADED', 'READY', 'STALE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visit_timeline.visit_state', ARRAY['ACCESS_FAILED', 'ACCESS_PENDING', 'APPROVAL_PENDING', 'APPROVED', 'ARRIVED', 'CANCELLED', 'CHECKED_OUT', 'DRAFT', 'INVITED', 'OVERSTAY', 'PREVIEWED', 'READY', 'REJECTED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visits.reservation_authority', ARRAY['CALENDAR', 'WORKPLACE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_visits.visit_state', ARRAY['ACCESS_FAILED', 'ACCESS_PENDING', 'APPROVAL_PENDING', 'APPROVED', 'ARRIVED', 'CANCELLED', 'CHECKED_OUT', 'DRAFT', 'INVITED', 'OVERSTAY', 'PREVIEWED', 'READY', 'REJECTED', 'RESULT_UNKNOWN']::VARCHAR[]),
    ('dwp-platform-server', 'wp_waitlist_entries.pricing_mode', ARRAY['MANAGED', 'NOT_APPLICABLE']::VARCHAR[]),
    ('dwp-platform-server', 'wp_waitlist_entries.promotion_evaluation_state', ARRAY['BLOCKED', 'MATCHED', 'NO_MATCH', 'PENDING']::VARCHAR[]),
    ('dwp-platform-server', 'wp_waitlist_entries.waitlist_state', ARRAY['ACTIVE', 'CANCELLED', 'CONFIRMED', 'CONFIRMING', 'EXPIRED', 'OFFERED']::VARCHAR[]),
    ('dwp-platform-server', 'wrk_personal_work_activity_bindings.source_system', ARRAY['PERSONAL_TASK']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_evidence.evidence_state', ARRAY['FAILED', 'INCONCLUSIVE', 'NOT_DISPATCHED', 'PASSED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_evidence.evidence_type', ARRAY['COMPATIBILITY', 'MANUAL_RECEIPT', 'OBSERVATION', 'PRE_FLIGHT', 'ROLLBACK_FEASIBILITY']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_evidence.source', ARRAY['INTERNAL_CONTROL_PLANE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_plans.executor_state', ARRAY['UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_plans.lifecycle_state', ARRAY['APPROVED', 'BLOCKED', 'CANCELLED', 'DRAFT', 'PENDING_APPROVAL', 'READY', 'REJECTED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_artifact_rollout_plans.rollback_feasibility', ARRAY['DECLARED', 'NOT_DECLARED', 'UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_feature_rollout_application_receipts.observation_state', ARRAY['APPLIED', 'FAILED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_feature_rollout_application_state.observation_state', ARRAY['APPLIED', 'FAILED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_operator_widget_owner_scopes.lifecycle_state', ARRAY['ACTIVE', 'REVOKED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_manifests.artifact_type', ARRAY['CONFIG_BUNDLE', 'SCHEMA', 'SERVICE', 'WEB_APP', 'WORKER']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_manifests.compatibility_state', ARRAY['BLOCKED', 'COMPATIBLE', 'NOT_EVALUATED', 'REVIEW_REQUIRED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_manifests.distribution_state', ARRAY['UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_manifests.lifecycle_state', ARRAY['APPROVED', 'DRAFT', 'RETIRED', 'REVIEW_REQUIRED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_manifests.signature_state', ARRAY['UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_artifact_reviews.decision', ARRAY['APPROVED', 'RETURNED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_product_entitlement_bindings.lifecycle_state', ARRAY['ACTIVE', 'RETIRED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_resource_commitment_changes.change_kind', ARRAY['CONTRACT_CHANGE', 'TEMPORARY_OVERRIDE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_resource_commitment_changes.lifecycle_state', ARRAY['APPROVED', 'EXPIRED', 'PENDING_APPROVAL', 'PUBLISHED', 'REJECTED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_resource_commitment_changes.reservation_state', ARRAY['UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_lifecycle_requests.execution_state', ARRAY['NOT_REQUIRED', 'OWNER_HANDOFF_REQUIRED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_lifecycle_requests.hold_evaluation_state', ARRAY['ACTIVE_GLOBAL_LEGAL_HOLD', 'OWNER_VERIFICATION_REQUIRED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_lifecycle_requests.lifecycle_state', ARRAY['APPROVED_FOR_HANDOFF', 'BLOCKED_BY_HOLD', 'CANCELLED', 'DRAFT', 'PENDING_APPROVAL', 'REJECTED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_lifecycle_requests.requested_action', ARRAY['PURGE', 'RETIRE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.control_mode', ARRAY['HARD_BLOCK', 'SOFT_ALERT']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.control_scope', ARRAY['INTERNAL_LEDGER_ONLY']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.external_feed_state', ARRAY['UNAVAILABLE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.lifecycle_state', ARRAY['ACTIVE', 'RETIRED', 'SUSPENDED']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.source_system', ARRAY['INTERNAL_CONTROL_PLANE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_commitments.unit', ARRAY['COUNT', 'CURRENCY_MINOR', 'GIB', 'REQUEST', 'SEAT']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_ledger.entry_type', ARRAY['ADJUST', 'ALLOCATE', 'BUDGET_RELEASE', 'BUDGET_RESERVE', 'BUDGET_SPEND', 'METER', 'RELEASE']::VARCHAR[]),
    ('dwp-provider-server', 'prv_tenant_resource_ledger.unit', ARRAY['COUNT', 'CURRENCY_MINOR', 'GIB', 'REQUEST', 'SEAT']::VARCHAR[]);

CREATE TEMP TABLE tmp_v322_resolved_check_contracts ON COMMIT DROP AS
SELECT COALESCE(
           (
               SELECT code_set.code_set_key
                 FROM sys_code_sets code_set
                WHERE code_set.owner_service = manifest.owner_service
                  AND code_set.source_reference = manifest.source_reference
                ORDER BY (code_set.lifecycle_state = 'ACTIVE') DESC,
                         code_set.code_set_key
                LIMIT 1
           ),
           'DBCHK.' || UPPER(SUBSTRING(MD5(
               manifest.owner_service || ':' || manifest.source_reference), 1, 32))
       )::VARCHAR(100) AS code_set_key,
       manifest.owner_service,
       manifest.source_reference,
       CASE
           WHEN manifest.source_reference LIKE 'sys_code_%'
               THEN 'REGISTRY_META'
           WHEN manifest.source_reference ~ '(status|state|decision|outcome)$'
               THEN 'STATE_MACHINE'
           WHEN manifest.owner_service = 'dwp-auth-server'
             OR manifest.source_reference ~ '(role|permission|access_scope|effect)$'
               THEN 'SECURITY'
           WHEN manifest.source_reference LIKE 'sys_audit_%'
             OR manifest.source_reference LIKE '%health%'
             OR manifest.source_reference LIKE '%incident%'
               THEN 'OBSERVABILITY'
           WHEN manifest.source_reference ~
                '(type|mode|kind|scope|tier|severity|operation|strategy|method)$'
               THEN 'PROTOCOL'
           ELSE 'REFERENCE'
       END::VARCHAR(24) AS contract_kind,
       manifest.allowed_values
  FROM tmp_v322_check_contract_manifest manifest;

ALTER TABLE tmp_v322_resolved_check_contracts
    ADD PRIMARY KEY (code_set_key),
    ADD UNIQUE (owner_service, source_reference);

DO $v322_registry_guard$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM tmp_v322_check_contract_manifest manifest
         WHERE (
             SELECT COUNT(*)
               FROM sys_code_sets code_set
              WHERE code_set.owner_service = manifest.owner_service
                AND code_set.source_reference = manifest.source_reference
         ) > 1
    ) THEN
        RAISE EXCEPTION
            'V322 found more than one code set for a database CHECK source';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM tmp_v322_resolved_check_contracts manifest
          JOIN sys_code_sets code_set
            ON code_set.code_set_key = manifest.code_set_key
         WHERE code_set.owner_service <> manifest.owner_service
            OR code_set.source_reference <> manifest.source_reference
    ) THEN
        RAISE EXCEPTION
            'V322 resolved a code-set key owned by a different source';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM tmp_v322_resolved_check_contracts manifest
          JOIN sys_code_bindings binding
            ON binding.consumer_service = manifest.owner_service
           AND binding.usage_type = 'DATABASE_COLUMN'
           AND binding.source_reference = manifest.source_reference
           AND binding.enforcement_type = 'CHECK'
           AND binding.lifecycle_state = 'ACTIVE'
           AND binding.code_set_key <> manifest.code_set_key
    ) THEN
        RAISE EXCEPTION
            'V322 found a conflicting active CHECK binding for a source';
    END IF;
END;
$v322_registry_guard$;

INSERT INTO sys_code_sets (
    code_set_key, owner_service, display_name, description,
    configuration_level, validation_source, source_reference, contract_kind,
    runtime_visibility, lifecycle_state)
SELECT manifest.code_set_key,
       manifest.owner_service,
       manifest.source_reference,
       'Database CHECK contract for ' || manifest.source_reference || '.',
       'SYSTEM', 'CHECK', manifest.source_reference, manifest.contract_kind,
       'ADMIN_ONLY', 'ACTIVE'
  FROM tmp_v322_resolved_check_contracts manifest
ON CONFLICT (code_set_key) DO UPDATE SET
    owner_service = EXCLUDED.owner_service,
    configuration_level = 'SYSTEM',
    validation_source = 'CHECK',
    source_reference = EXCLUDED.source_reference,
    contract_kind = EXCLUDED.contract_kind,
    runtime_visibility = 'ADMIN_ONLY',
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP
WHERE ROW(
          sys_code_sets.owner_service,
          sys_code_sets.configuration_level,
          sys_code_sets.validation_source,
          sys_code_sets.source_reference,
          sys_code_sets.contract_kind,
          sys_code_sets.runtime_visibility,
          sys_code_sets.lifecycle_state)
      IS DISTINCT FROM ROW(
          EXCLUDED.owner_service,
          'SYSTEM',
          'CHECK',
          EXCLUDED.source_reference,
          EXCLUDED.contract_kind,
          'ADMIN_ONLY',
          'ACTIVE');

INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n,
    behavior_metadata, sort_order, predefined, lifecycle_state)
SELECT manifest.code_set_key,
       value_ref.code,
       value_ref.code,
       jsonb_build_object('ko', value_ref.code, 'en', value_ref.code),
       '{}'::jsonb,
       value_ref.ordinality::INTEGER * 10,
       TRUE,
       'ACTIVE'
  FROM tmp_v322_resolved_check_contracts manifest
 CROSS JOIN LATERAL unnest(manifest.allowed_values)
     WITH ORDINALITY AS value_ref(code, ordinality)
ON CONFLICT (code_set_key, code) DO UPDATE SET
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP
WHERE sys_code_values.lifecycle_state <> 'ACTIVE';

UPDATE sys_code_values code_value
   SET lifecycle_state = 'RETIRED',
       updated_at = CURRENT_TIMESTAMP
  FROM tmp_v322_resolved_check_contracts manifest
 WHERE code_value.code_set_key = manifest.code_set_key
   AND NOT (code_value.code = ANY (manifest.allowed_values))
   AND code_value.lifecycle_state <> 'RETIRED';

INSERT INTO sys_code_bindings (
    code_set_key, consumer_service, usage_type,
    source_reference, enforcement_type, lifecycle_state)
SELECT manifest.code_set_key,
       manifest.owner_service,
       'DATABASE_COLUMN',
       manifest.source_reference,
       'CHECK',
       'ACTIVE'
  FROM tmp_v322_resolved_check_contracts manifest
ON CONFLICT (
    code_set_key, consumer_service, usage_type, source_reference)
DO UPDATE SET
    enforcement_type = 'CHECK',
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP
WHERE ROW(
          sys_code_bindings.enforcement_type,
          sys_code_bindings.lifecycle_state)
      IS DISTINCT FROM ROW('CHECK', 'ACTIVE');
