INSERT INTO sys_code_sets (
    code_set_key, owner_service, display_name, description,
    configuration_level, validation_source, source_reference, contract_kind)
VALUES
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'dwp-platform-server',
     'Productivity connector lifecycle', 'Configuration lifecycle of a productivity connector.',
     'SYSTEM', 'CHECK', 'int_productivity_connectors.lifecycle_state', 'STATE_MACHINE'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'dwp-platform-server',
     'Productivity connector health', 'Operational health reported for a productivity connector.',
     'SYSTEM', 'CHECK', 'int_productivity_connectors.health_state', 'OBSERVABILITY'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.POLICY_STATE', 'dwp-platform-server',
     'Productivity connector policy', 'Governance decision controlling connector activation.',
     'SYSTEM', 'CHECK', 'int_productivity_connectors.policy_state', 'SECURITY'),
    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'dwp-platform-server',
     'Productivity subject consent', 'User authorization lifecycle for productivity access.',
     'SYSTEM', 'CHECK', 'int_productivity_subjects.consent_state', 'STATE_MACHINE'),
    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'dwp-platform-server',
     'Productivity resource kind', 'Shared resource taxonomy for synchronized productivity data.',
     'SYSTEM', 'CHECK', 'int_productivity_sync_streams.resource_kind', 'PROTOCOL'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'dwp-platform-server',
     'Productivity stream state', 'Recoverable synchronization state for a user resource stream.',
     'SYSTEM', 'CHECK', 'int_productivity_sync_streams.stream_state', 'STATE_MACHINE'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.SYNC_MODE', 'dwp-platform-server',
     'Productivity synchronization mode', 'Checkpoint strategy used for a synchronization run.',
     'SYSTEM', 'CHECK', 'int_productivity_sync_runs.sync_mode', 'PROTOCOL'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'dwp-platform-server',
     'Productivity synchronization state', 'Execution outcome of a productivity synchronization run.',
     'SYSTEM', 'CHECK', 'int_productivity_sync_runs.run_state', 'STATE_MACHINE'),
    ('PLATFORM.PRODUCTIVITY_ITEM.CLASSIFICATION', 'dwp-platform-server',
     'Productivity item classification', 'Minimum handling classification applied to projected items.',
     'SYSTEM', 'CHECK', 'wrk_productivity_items.classification', 'SECURITY');

INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n, sort_order, behavior_metadata)
VALUES
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'DRAFT', 'Draft',
     '{"ko":"초안","en":"Draft"}', 10, '{"terminal":false}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'ACTIVE', 'Active',
     '{"ko":"활성","en":"Active"}', 20, '{"terminal":false}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'SUSPENDED', 'Suspended',
     '{"ko":"일시 중지","en":"Suspended"}', 30, '{"terminal":false}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'RETIRED', 'Retired',
     '{"ko":"종료","en":"Retired"}', 40, '{"terminal":true}'),

    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'CONFIGURATION_REQUIRED', 'Configuration required',
     '{"ko":"구성 필요","en":"Configuration required"}', 10, '{"severity":"WARNING"}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'HEALTHY', 'Healthy',
     '{"ko":"정상","en":"Healthy"}', 20, '{"severity":"SUCCESS"}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'DEGRADED', 'Degraded',
     '{"ko":"성능 저하","en":"Degraded"}', 30, '{"severity":"WARNING"}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'AUTHENTICATION_REQUIRED', 'Authentication required',
     '{"ko":"인증 필요","en":"Authentication required"}', 40, '{"severity":"ERROR"}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'UNAVAILABLE', 'Unavailable',
     '{"ko":"사용 불가","en":"Unavailable"}', 50, '{"severity":"ERROR"}'),

    ('PLATFORM.PRODUCTIVITY_CONNECTOR.POLICY_STATE', 'REVIEW_REQUIRED', 'Review required',
     '{"ko":"검토 필요","en":"Review required"}', 10, '{"approved":false}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.POLICY_STATE', 'APPROVED', 'Approved',
     '{"ko":"승인됨","en":"Approved"}', 20, '{"approved":true}'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.POLICY_STATE', 'BLOCKED', 'Blocked',
     '{"ko":"차단됨","en":"Blocked"}', 30, '{"approved":false}'),

    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'NOT_CONNECTED', 'Not connected',
     '{"ko":"연결 안 됨","en":"Not connected"}', 10, '{"connected":false}'),
    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'CONNECTED', 'Connected',
     '{"ko":"연결됨","en":"Connected"}', 20, '{"connected":true}'),
    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'REAUTHORIZATION_REQUIRED', 'Reauthorization required',
     '{"ko":"재인증 필요","en":"Reauthorization required"}', 30, '{"connected":false}'),
    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'REVOKED', 'Revoked',
     '{"ko":"동의 철회","en":"Revoked"}', 40, '{"connected":false,"terminal":true}'),

    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'MAIL', 'Mail',
     '{"ko":"메일","en":"Mail"}', 10, '{"timeBounded":false}'),
    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'CALENDAR', 'Calendar',
     '{"ko":"캘린더","en":"Calendar"}', 20, '{"timeBounded":true}'),

    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'READY', 'Ready',
     '{"ko":"준비됨","en":"Ready"}', 10, '{"recoverable":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'SYNCING', 'Syncing',
     '{"ko":"동기화 중","en":"Syncing"}', 20, '{"recoverable":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'STALE', 'Stale',
     '{"ko":"갱신 지연","en":"Stale"}', 30, '{"recoverable":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'RESET_REQUIRED', 'Reset required',
     '{"ko":"초기화 필요","en":"Reset required"}', 40, '{"recoverable":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'AUTHENTICATION_REQUIRED', 'Authentication required',
     '{"ko":"인증 필요","en":"Authentication required"}', 50, '{"recoverable":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'SUSPENDED', 'Suspended',
     '{"ko":"일시 중지","en":"Suspended"}', 60, '{"recoverable":false}'),

    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.SYNC_MODE', 'INITIAL', 'Initial',
     '{"ko":"최초 동기화","en":"Initial"}', 10, '{"resetsCheckpoint":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.SYNC_MODE', 'DELTA', 'Delta',
     '{"ko":"증분 동기화","en":"Delta"}', 20, '{"resetsCheckpoint":false}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.SYNC_MODE', 'RESET', 'Reset',
     '{"ko":"재동기화","en":"Reset"}', 30, '{"resetsCheckpoint":true}'),

    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'RUNNING', 'Running',
     '{"ko":"실행 중","en":"Running"}', 10, '{"terminal":false}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'SUCCEEDED', 'Succeeded',
     '{"ko":"성공","en":"Succeeded"}', 20, '{"terminal":true,"successful":true}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'PARTIAL', 'Partial',
     '{"ko":"부분 성공","en":"Partial"}', 30, '{"terminal":true,"successful":false}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'FAILED', 'Failed',
     '{"ko":"실패","en":"Failed"}', 40, '{"terminal":true,"successful":false}'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'BLOCKED', 'Blocked',
     '{"ko":"차단됨","en":"Blocked"}', 50, '{"terminal":true,"successful":false}'),

    ('PLATFORM.PRODUCTIVITY_ITEM.CLASSIFICATION', 'INTERNAL', 'Internal',
     '{"ko":"내부","en":"Internal"}', 10, '{"weight":1}'),
    ('PLATFORM.PRODUCTIVITY_ITEM.CLASSIFICATION', 'CONFIDENTIAL', 'Confidential',
     '{"ko":"기밀","en":"Confidential"}', 20, '{"weight":2}'),
    ('PLATFORM.PRODUCTIVITY_ITEM.CLASSIFICATION', 'RESTRICTED', 'Restricted',
     '{"ko":"제한","en":"Restricted"}', 30, '{"weight":3}');

INSERT INTO sys_code_bindings (
    code_set_key, consumer_service, usage_type, source_reference, enforcement_type)
VALUES
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.LIFECYCLE_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_connectors.lifecycle_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.HEALTH_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_connectors.health_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.POLICY_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_connectors.policy_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_SUBJECT.CONSENT_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_subjects.consent_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_sync_streams.resource_kind', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_sync_runs.resource_kind', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY.RESOURCE_KIND', 'dwp-platform-server', 'DATABASE_COLUMN',
     'wrk_productivity_items.resource_kind', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_SYNC_STREAM.STREAM_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_sync_streams.stream_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.SYNC_MODE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_sync_runs.sync_mode', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_SYNC_RUN.RUN_STATE', 'dwp-platform-server', 'DATABASE_COLUMN',
     'int_productivity_sync_runs.run_state', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_ITEM.CLASSIFICATION', 'dwp-platform-server', 'DATABASE_COLUMN',
     'wrk_productivity_items.classification', 'CHECK');
