INSERT INTO sys_code_sets (
    code_set_key, owner_service, display_name, description,
    configuration_level, validation_source, source_reference, contract_kind)
VALUES
    ('PEOPLE.WORKFORCE_ACCESS.SUBJECT_TYPE', 'dwp-people-server',
     'Workforce access subject type',
     'Identity subject classes eligible for a governed workforce access boundary.',
     'SYSTEM', 'CHECK', 'ppl_workforce_access_policies.subject_type', 'SECURITY'),
    ('PEOPLE.WORKFORCE_ACCESS.POPULATION_TYPE', 'dwp-people-server',
     'Workforce access population type',
     'Population boundary resolved before workforce fields and actions are authorized.',
     'SYSTEM', 'CHECK', 'ppl_workforce_access_policies.population_type', 'SECURITY'),
    ('PEOPLE.WORKFORCE_ACCESS.LIFECYCLE_STATE', 'dwp-people-server',
     'Workforce access lifecycle',
     'Lifecycle of a governed workforce access boundary.',
     'SYSTEM', 'CHECK', 'ppl_workforce_access_policies.lifecycle_state', 'STATE_MACHINE'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'dwp-people-server',
     'Workforce field group',
     'Field-level disclosure groups shared by access boundaries and export contracts.',
     'SYSTEM', 'CHECK', 'ppl_workforce_access_policies.field_groups', 'SECURITY'),
    ('PEOPLE.WORKFORCE_ACCESS.ACTION', 'dwp-people-server',
     'Workforce governed action',
     'Actions that a workforce access boundary can authorize.',
     'SYSTEM', 'CHECK', 'ppl_workforce_access_policies.action_codes', 'SECURITY'),
    ('PEOPLE.WORKFORCE_EXPORT.DATASET_LIFECYCLE_STATE', 'dwp-people-server',
     'Workforce export dataset lifecycle',
     'Availability lifecycle for governed workforce export datasets.',
     'SYSTEM', 'CHECK', 'ppl_workforce_export_datasets.lifecycle_state', 'STATE_MACHINE'),
    ('PEOPLE.WORKFORCE_EXPORT.POPULATION_TYPE', 'dwp-people-server',
     'Workforce export population type',
     'Population scope captured in an immutable workforce export request.',
     'SYSTEM', 'CHECK', 'ppl_workforce_export_requests.population_type', 'SECURITY'),
    ('PEOPLE.WORKFORCE_EXPORT.FORMAT', 'dwp-people-server',
     'Workforce export format',
     'Approved artifact formats for governed workforce export delivery.',
     'SYSTEM', 'CHECK', 'ppl_workforce_export_requests.export_format', 'PROTOCOL'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'dwp-people-server',
     'Workforce export lifecycle',
     'Durable worker, cancellation, retry, and retention lifecycle for export requests.',
     'SYSTEM', 'CHECK', 'ppl_workforce_export_requests.lifecycle_state', 'STATE_MACHINE'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'dwp-people-server',
     'Workforce export attempt event',
     'Append-only evidence events emitted by the workforce export worker.',
     'SYSTEM', 'CHECK', 'ppl_workforce_export_attempt_events.event_type', 'OBSERVABILITY'),
    ('PLATFORM.WORKSPACE_APP_ACCESS_REQUEST.PERMISSION', 'dwp-platform-server',
     'Workspace app request permission',
     'Permission subset that a workspace user can request through self service.',
     'SYSTEM', 'CHECK', 'usr_workspace_app_access_requests.requested_permission_code', 'SECURITY'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'dwp-core',
     'Domain event outbox status',
     'Shared transactional producer delivery lifecycle installed in each service database.',
     'SYSTEM', 'CHECK', 'sys_domain_event_outbox.status', 'STATE_MACHINE'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'dwp-core',
     'Domain event inbox status',
     'Shared idempotent consumer delivery lifecycle installed in each service database.',
     'SYSTEM', 'CHECK', 'sys_domain_event_inbox.status', 'STATE_MACHINE'),
    ('CORE.DOMAIN_EVENT.REPLAY_DIRECTION', 'dwp-core',
     'Domain event replay direction',
     'Ledger direction selected for an audited domain event replay request.',
     'SYSTEM', 'CHECK', 'sys_domain_event_replay_audit.direction', 'PROTOCOL');

INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n, sort_order, behavior_metadata)
VALUES
    ('PEOPLE.WORKFORCE_ACCESS.SUBJECT_TYPE', 'ROLE', 'Role',
     '{"ko":"역할","en":"Role"}', 10, '{}'),
    ('PEOPLE.WORKFORCE_ACCESS.SUBJECT_TYPE', 'USER', 'User',
     '{"ko":"사용자","en":"User"}', 20, '{}'),
    ('PEOPLE.WORKFORCE_ACCESS.POPULATION_TYPE', 'TENANT', 'Entire tenant',
     '{"ko":"전체 테넌트","en":"Entire tenant"}', 10, '{"tenantWide":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.POPULATION_TYPE', 'ORG_UNIT', 'Organization unit',
     '{"ko":"선택 조직","en":"Organization unit"}', 20, '{"includeDescendants":false}'),
    ('PEOPLE.WORKFORCE_ACCESS.POPULATION_TYPE', 'ORG_TREE', 'Organization tree',
     '{"ko":"선택 조직 및 하위 조직","en":"Organization tree"}', 30,
     '{"includeDescendants":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.LIFECYCLE_STATE', 'ACTIVE', 'Active',
     '{"ko":"활성","en":"Active"}', 10, '{"effective":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.LIFECYCLE_STATE', 'REVOKED', 'Revoked',
     '{"ko":"회수됨","en":"Revoked"}', 20, '{"terminal":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.LIFECYCLE_STATE', 'EXPIRED', 'Expired',
     '{"ko":"만료됨","en":"Expired"}', 30, '{"terminal":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'DIRECTORY', 'Directory',
     '{"ko":"기본 디렉터리","en":"Directory"}', 10, '{"requiredForAccess":true}'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'WORKER_IDENTIFIERS', 'Worker identifiers',
     '{"ko":"인력 식별자","en":"Worker identifiers"}', 20, '{"sensitivity":"RESTRICTED"}'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'EMPLOYMENT', 'Employment',
     '{"ko":"고용 및 배치 이력","en":"Employment"}', 30, '{"sensitivity":"CONFIDENTIAL"}'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'JOB_GRADE', 'Job grade',
     '{"ko":"직급","en":"Job grade"}', 40, '{"sensitivity":"CONFIDENTIAL"}'),
    ('PEOPLE.WORKFORCE_ACCESS.ACTION', 'READ', 'Read',
     '{"ko":"조회","en":"Read"}', 10, '{}'),
    ('PEOPLE.WORKFORCE_ACCESS.ACTION', 'EXPORT', 'Export',
     '{"ko":"반출","en":"Export"}', 20, '{"requiresGovernedArtifact":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.DATASET_LIFECYCLE_STATE', 'ACTIVE', 'Active',
     '{"ko":"활성","en":"Active"}', 10, '{"requestable":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.DATASET_LIFECYCLE_STATE', 'RETIRED', 'Retired',
     '{"ko":"폐기됨","en":"Retired"}', 20, '{"terminal":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.POPULATION_TYPE', 'TENANT', 'Entire tenant',
     '{"ko":"전체 테넌트","en":"Entire tenant"}', 10, '{"tenantWide":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.POPULATION_TYPE', 'ORGANIZATION_SET', 'Organization set',
     '{"ko":"조직 집합","en":"Organization set"}', 20, '{"tenantWide":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.FORMAT', 'CSV', 'CSV',
     '{"ko":"CSV","en":"CSV"}', 10, '{"mediaType":"text/csv"}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'BLOCKED_PENDING_APPROVAL',
     'Blocked pending approval',
     '{"ko":"승인 전 차단","en":"Blocked pending approval"}', 10,
     '{"terminal":false,"executable":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'QUEUED', 'Queued',
     '{"ko":"대기열","en":"Queued"}', 20, '{"terminal":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'RUNNING', 'Running',
     '{"ko":"실행 중","en":"Running"}', 30, '{"terminal":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'RETRY_WAIT', 'Waiting to retry',
     '{"ko":"재시도 대기","en":"Waiting to retry"}', 40, '{"terminal":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'CANCEL_REQUESTED', 'Cancellation requested',
     '{"ko":"취소 요청됨","en":"Cancellation requested"}', 50, '{"terminal":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'CANCELLED', 'Cancelled',
     '{"ko":"취소됨","en":"Cancelled"}', 60, '{"terminal":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'COMPLETED', 'Completed',
     '{"ko":"완료","en":"Completed"}', 70, '{"terminal":false,"artifactAvailable":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'FAILED', 'Failed',
     '{"ko":"실패","en":"Failed"}', 80, '{"terminal":true,"manualRetryEligible":true}'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'EXPIRED', 'Expired',
     '{"ko":"만료됨","en":"Expired"}', 90, '{"terminal":true,"artifactAvailable":false}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'BLOCKED', 'Blocked',
     '{"ko":"차단","en":"Blocked"}', 10, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'QUEUED', 'Queued',
     '{"ko":"대기열 등록","en":"Queued"}', 20, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'CLAIMED', 'Claimed',
     '{"ko":"작업 할당","en":"Claimed"}', 30, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'RETRY_SCHEDULED', 'Retry scheduled',
     '{"ko":"재시도 예약","en":"Retry scheduled"}', 40, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'FAILED', 'Failed',
     '{"ko":"실패","en":"Failed"}', 50, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'COMPLETED', 'Completed',
     '{"ko":"완료","en":"Completed"}', 60, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'CANCELLED', 'Cancelled',
     '{"ko":"취소됨","en":"Cancelled"}', 70, '{}'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'EXPIRED', 'Expired',
     '{"ko":"만료됨","en":"Expired"}', 80, '{}'),
    ('PLATFORM.WORKSPACE_APP_ACCESS_REQUEST.PERMISSION', 'VIEW', 'View',
     '{"ko":"조회","en":"View"}', 10, '{}'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'PENDING', 'Pending',
     '{"ko":"대기","en":"Pending"}', 10, '{}'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'SENDING', 'Sending',
     '{"ko":"전송 중","en":"Sending"}', 20, '{}'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'PUBLISHED', 'Published',
     '{"ko":"게시됨","en":"Published"}', 30, '{"terminal":true}'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'FAILED', 'Failed',
     '{"ko":"실패","en":"Failed"}', 40, '{}'),
    ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'DEAD', 'Dead letter',
     '{"ko":"데드 레터","en":"Dead letter"}', 50, '{"terminal":true}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'RECEIVED', 'Received',
     '{"ko":"수신됨","en":"Received"}', 10, '{}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'PROCESSING', 'Processing',
     '{"ko":"처리 중","en":"Processing"}', 20, '{}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'SUCCEEDED', 'Succeeded',
     '{"ko":"성공","en":"Succeeded"}', 30, '{"terminal":true}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'FAILED', 'Failed',
     '{"ko":"실패","en":"Failed"}', 40, '{}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'DEFERRED', 'Deferred',
     '{"ko":"지연됨","en":"Deferred"}', 50, '{}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'DEAD', 'Dead letter',
     '{"ko":"데드 레터","en":"Dead letter"}', 60, '{"terminal":true}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'REPLAY_PENDING', 'Replay pending',
     '{"ko":"재처리 대기","en":"Replay pending"}', 70, '{}'),
    ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'DUPLICATE', 'Duplicate',
     '{"ko":"중복","en":"Duplicate"}', 80, '{"terminal":true}'),
    ('CORE.DOMAIN_EVENT.REPLAY_DIRECTION', 'OUTBOX', 'Outbox',
     '{"ko":"발신 원장","en":"Outbox"}', 10, '{}'),
    ('CORE.DOMAIN_EVENT.REPLAY_DIRECTION', 'INBOX', 'Inbox',
     '{"ko":"수신 원장","en":"Inbox"}', 20, '{}');

INSERT INTO sys_code_bindings (
    code_set_key, consumer_service, usage_type, source_reference, enforcement_type)
VALUES
    ('PEOPLE.WORKFORCE_ACCESS.SUBJECT_TYPE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_access_policies.subject_type', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.POPULATION_TYPE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_access_policies.population_type', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.LIFECYCLE_STATE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_access_policies.lifecycle_state', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_access_policies.field_groups', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_datasets.required_field_groups', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.FIELD_GROUP', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_requests.field_groups', 'CHECK'),
    ('PEOPLE.WORKFORCE_ACCESS.ACTION', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_access_policies.action_codes', 'CHECK'),
    ('PEOPLE.WORKFORCE_EXPORT.DATASET_LIFECYCLE_STATE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_datasets.lifecycle_state', 'CHECK'),
    ('PEOPLE.WORKFORCE_EXPORT.POPULATION_TYPE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_requests.population_type', 'CHECK'),
    ('PEOPLE.WORKFORCE_EXPORT.FORMAT', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_requests.export_format', 'CHECK'),
    ('PEOPLE.WORKFORCE_EXPORT.LIFECYCLE_STATE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_requests.lifecycle_state', 'CHECK'),
    ('PEOPLE.WORKFORCE_EXPORT.ATTEMPT_EVENT_TYPE', 'dwp-people-server',
     'DATABASE_COLUMN', 'ppl_workforce_export_attempt_events.event_type', 'CHECK'),
    ('PLATFORM.WORKSPACE_APP_ACCESS_REQUEST.PERMISSION', 'dwp-platform-server',
     'DATABASE_COLUMN', 'usr_workspace_app_access_requests.requested_permission_code', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.PROVIDER_TYPE', 'dwp-platform-server',
     'DATABASE_COLUMN', 'int_productivity_connectors.provider_type', 'CHECK'),
    ('PLATFORM.PRODUCTIVITY_CONNECTOR.AUTH_MODE', 'dwp-platform-server',
     'DATABASE_COLUMN', 'int_productivity_connectors.auth_mode', 'CHECK');

INSERT INTO sys_code_bindings (
    code_set_key, consumer_service, usage_type, source_reference, enforcement_type)
SELECT contract.code_set_key,
       service.consumer_service,
       'DATABASE_COLUMN',
       contract.source_reference,
       'CHECK'
  FROM (VALUES
      ('CORE.DOMAIN_EVENT.OUTBOX_STATUS', 'sys_domain_event_outbox.status'),
      ('CORE.DOMAIN_EVENT.INBOX_STATUS', 'sys_domain_event_inbox.status'),
      ('CORE.DOMAIN_EVENT.REPLAY_DIRECTION', 'sys_domain_event_replay_audit.direction')
  ) contract(code_set_key, source_reference)
 CROSS JOIN (VALUES
      ('dwp-auth-server'),
      ('dwp-people-server'),
      ('dwp-platform-server'),
      ('dwp-provider-server')
  ) service(consumer_service);
