INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n,
    sort_order, behavior_metadata, lifecycle_state)
VALUES
    ('AUTH.BUILT_IN_ROLE', 'IDENTITY_ADMIN', 'Identity administrator',
     '{"ko":"ID 관리자","en":"Identity administrator"}', 35,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'APP_CATALOG_ADMIN', 'Application catalog administrator',
     '{"ko":"앱 카탈로그 관리자","en":"Application catalog administrator"}', 36,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'COMMUNICATIONS_EDITOR', 'Communications editor',
     '{"ko":"사내 소식 편집자","en":"Communications editor"}', 42,
     '{"roleFamily":"TENANT","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'COMMUNICATIONS_PUBLISHER', 'Communications publisher',
     '{"ko":"사내 소식 게시 책임자","en":"Communications publisher"}', 43,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SERVICE_CATALOG_MANAGER', 'Service catalog manager',
     '{"ko":"서비스 카탈로그 관리자","en":"Service catalog manager"}', 44,
     '{"roleFamily":"TENANT","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'SERVICE_AGENT', 'Service operations agent',
     '{"ko":"서비스 처리 담당자","en":"Service operations agent"}', 45,
     '{"roleFamily":"TENANT","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PROVIDER_TENANT_PROVISIONER', 'Provider tenant provisioner',
     '{"ko":"프로바이더 테넌트 개통 담당자","en":"Provider tenant provisioner"}', 101,
     '{"roleFamily":"PROVIDER","privileged":true,"assignableToGroups":false,"assignmentClass":"CONTROL_PLANE"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PROVIDER_ENTITLEMENT_ADMIN', 'Provider entitlement administrator',
     '{"ko":"프로바이더 구독 권한 관리자","en":"Provider entitlement administrator"}', 102,
     '{"roleFamily":"PROVIDER","privileged":true,"assignableToGroups":false,"assignmentClass":"CONTROL_PLANE"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PROVIDER_CHANGE_APPROVER', 'Provider change approver',
     '{"ko":"프로바이더 변경 승인자","en":"Provider change approver"}', 103,
     '{"roleFamily":"PROVIDER","privileged":true,"assignableToGroups":false,"assignmentClass":"CONTROL_PLANE"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PROVIDER_RELEASE_APPROVER', 'Provider release approver',
     '{"ko":"프로바이더 릴리스 승인자","en":"Provider release approver"}', 104,
     '{"roleFamily":"PROVIDER","privileged":true,"assignableToGroups":false,"assignmentClass":"CONTROL_PLANE"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PROVIDER_DATA_APPROVER', 'Provider data policy approver',
     '{"ko":"프로바이더 데이터 정책 승인자","en":"Provider data policy approver"}', 105,
     '{"roleFamily":"PROVIDER","privileged":true,"assignableToGroups":false,"assignmentClass":"CONTROL_PLANE"}',
     'ACTIVE')
ON CONFLICT (code_set_key, code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    label_i18n = EXCLUDED.label_i18n,
    sort_order = EXCLUDED.sort_order,
    behavior_metadata = EXCLUDED.behavior_metadata,
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP;

COMMENT ON COLUMN sys_code_values.behavior_metadata IS
    'Machine-readable code behavior; AUTH.BUILT_IN_ROLE mirrors role family, privilege, group assignment, and assignment class from Auth.';
