INSERT INTO sys_code_values (
    code_set_key, code, display_name, label_i18n,
    sort_order, behavior_metadata, lifecycle_state)
VALUES
    ('AUTH.BUILT_IN_ROLE', 'CALENDAR_ADMIN', 'Calendar administrator',
     '{"ko":"캘린더 관리자","en":"Calendar administrator"}', 46,
     '{"roleFamily":"WORKSPACE","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'APPROVAL_DESIGNER', 'Approval process designer',
     '{"ko":"결재 프로세스 설계자","en":"Approval process designer"}', 47,
     '{"roleFamily":"TENANT","privileged":false,"assignableToGroups":true,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'APPROVAL_PUBLISHER', 'Approval policy publisher',
     '{"ko":"결재 정책 게시 책임자","en":"Approval policy publisher"}', 48,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'APPROVAL_OPERATOR', 'Approval operations manager',
     '{"ko":"결재 운영 관리자","en":"Approval operations manager"}', 49,
     '{"roleFamily":"TENANT","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'TIME_ADMIN', 'Time administrator',
     '{"ko":"근태 관리자","en":"Time administrator"}', 51,
     '{"roleFamily":"PEOPLE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'ABSENCE_ADMIN', 'Absence administrator',
     '{"ko":"휴가 관리자","en":"Absence administrator"}', 52,
     '{"roleFamily":"PEOPLE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'BENEFITS_ADMIN', 'Benefits administrator',
     '{"ko":"복리후생 관리자","en":"Benefits administrator"}', 53,
     '{"roleFamily":"PEOPLE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'PAYROLL_ADMIN', 'Payroll administrator',
     '{"ko":"급여 관리자","en":"Payroll administrator"}', 54,
     '{"roleFamily":"PEOPLE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE'),
    ('AUTH.BUILT_IN_ROLE', 'TALENT_ADMIN', 'Talent administrator',
     '{"ko":"인재 관리자","en":"Talent administrator"}', 55,
     '{"roleFamily":"PEOPLE","privileged":true,"assignableToGroups":false,"assignmentClass":"DELEGATED"}',
     'ACTIVE')
ON CONFLICT (code_set_key, code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    label_i18n = EXCLUDED.label_i18n,
    sort_order = EXCLUDED.sort_order,
    behavior_metadata = EXCLUDED.behavior_metadata,
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP;
