/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_017
 * Normalized schema SHA-256: e4355a2f03f396cb082e7f43ede9938be78a48e49351117cf06809983c8dee97
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon017WorkerDependentEligibilitySnapshotV1.Deserializer.class)
public record Xcon017WorkerDependentEligibilitySnapshotV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID dependentPublicId,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
        List<EligibilityFacts> eligibilityFacts,
        String payloadDigest,
        String relationshipType,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId) {

    public Xcon017WorkerDependentEligibilitySnapshotV1 {
        Objects.requireNonNull(dependentPublicId, "dependentPublicId must not be null");
        Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        Objects.requireNonNull(eligibilityFacts, "eligibilityFacts must not be null");
        eligibilityFacts = List.copyOf(eligibilityFacts);
        if (eligibilityFacts.size() < 1) {
            throw new IllegalArgumentException("eligibilityFacts has too few items");
        }
        if (eligibilityFacts.size() > 64) {
            throw new IllegalArgumentException("eligibilityFacts has too many items");
        }
        for (EligibilityFacts eligibilityFactsItem : eligibilityFacts) {
            Objects.requireNonNull(eligibilityFactsItem, "eligibilityFactsItem must not be null");
        }
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(relationshipType, "relationshipType must not be null");
        if (!Set.of("SPOUSE", "CHILD", "DOMESTIC_PARTNER", "OTHER_DEPENDENT").contains(relationshipType)) {
            throw new IllegalArgumentException("relationshipType is not a canonical value");
        }
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        Objects.requireNonNull(workerId, "workerId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon017WorkerDependentEligibilitySnapshotV1> {

        @Override
        public Xcon017WorkerDependentEligibilitySnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "Xcon017WorkerDependentEligibilitySnapshotV1 must be encoded as a JSON object");
            }
            UUID dependentPublicId = null; boolean dependentPublicIdSeen = false;
            LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
            LocalDate effectiveTo = null; boolean effectiveToSeen = false;
            List<EligibilityFacts> eligibilityFacts = null; boolean eligibilityFactsSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            String relationshipType = null; boolean relationshipTypeSeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            UUID workerId = null; boolean workerIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon017WorkerDependentEligibilitySnapshotV1.class,
                            "Xcon017WorkerDependentEligibilitySnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon017WorkerDependentEligibilitySnapshotV1.class,
                            "Xcon017WorkerDependentEligibilitySnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "dependentPublicId" -> {
                    if (dependentPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property dependentPublicId");
                    }
                    dependentPublicIdSeen = true;
                    dependentPublicId = CanonicalHrisJson.readUuid(parser, context, "dependentPublicId", false);
                }
                case "effectiveFrom" -> {
                    if (effectiveFromSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property effectiveFrom");
                    }
                    effectiveFromSeen = true;
                    effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                }
                case "effectiveTo" -> {
                    if (effectiveToSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property effectiveTo");
                    }
                    effectiveToSeen = true;
                    effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                }
                case "eligibilityFacts" -> {
                    if (eligibilityFactsSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property eligibilityFacts");
                    }
                    eligibilityFactsSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "eligibilityFacts must be encoded as a JSON array");
                    }
                    ArrayList<EligibilityFacts> eligibilityFactsValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (eligibilityFactsValues.size() >= 64) {
                            return context.reportInputMismatch(
                                    Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                    "eligibilityFacts exceeds its canonical item limit");
                        }
                        eligibilityFactsValues.add(CanonicalHrisJson.readObject(parser, context, "eligibilityFacts[]", EligibilityFacts.class, false));
                    }
                    eligibilityFacts = List.copyOf(eligibilityFactsValues);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "relationshipType" -> {
                    if (relationshipTypeSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property relationshipType");
                    }
                    relationshipTypeSeen = true;
                    relationshipType = CanonicalHrisJson.readString(parser, context, "relationshipType", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                case "workerId" -> {
                    if (workerIdSeen) {
                        return context.reportInputMismatch(
                                Xcon017WorkerDependentEligibilitySnapshotV1.class,
                                "duplicate property workerId");
                    }
                    workerIdSeen = true;
                    workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon017WorkerDependentEligibilitySnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!dependentPublicIdSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property dependentPublicId");
            }
            if (!effectiveFromSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property effectiveFrom");
            }
            if (!effectiveToSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property effectiveTo");
            }
            if (!eligibilityFactsSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property eligibilityFacts");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!relationshipTypeSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property relationshipType");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property sourceVersion");
            }
            if (!workerIdSeen) {
                return context.reportInputMismatch(Xcon017WorkerDependentEligibilitySnapshotV1.class,
                        "missing required property workerId");
            }
            return new Xcon017WorkerDependentEligibilitySnapshotV1(
                    dependentPublicId,
                    effectiveFrom,
                    effectiveTo,
                    eligibilityFacts,
                    payloadDigest,
                    relationshipType,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion,
                    workerId);
        }
    }

    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonDeserialize(using = EligibilityFacts.Deserializer.class)
    public record EligibilityFacts(
            String eligibilityType,
            boolean eligible,
            long factRevision,
            String jurisdictionCode) {

        public EligibilityFacts {
            Objects.requireNonNull(eligibilityType, "eligibilityType must not be null");
            if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", eligibilityType)) {
                throw new IllegalArgumentException("eligibilityType does not match its canonical format");
            }
            if (factRevision < 1L) {
                throw new IllegalArgumentException("factRevision is below its canonical minimum");
            }
            if (jurisdictionCode != null) {
                if (!Pattern.matches("^[A-Z0-9-]{2,16}$", jurisdictionCode)) {
                    throw new IllegalArgumentException("jurisdictionCode does not match its canonical format");
                }
            }
        }

        public static final class Deserializer
                extends JsonDeserializer<EligibilityFacts> {

            @Override
            public EligibilityFacts deserialize(
                    JsonParser parser,
                    DeserializationContext context) throws IOException {
                if (!parser.isExpectedStartObjectToken()) {
                    return context.reportInputMismatch(
                            EligibilityFacts.class,
                            "EligibilityFacts must be encoded as a JSON object");
                }
                String eligibilityType = null; boolean eligibilityTypeSeen = false;
                boolean eligible = false; boolean eligibleSeen = false;
                long factRevision = 0L; boolean factRevisionSeen = false;
                String jurisdictionCode = null; boolean jurisdictionCodeSeen = false;
                while (parser.nextToken() != JsonToken.END_OBJECT) {
                    if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                        return context.reportInputMismatch(
                                EligibilityFacts.class,
                                "EligibilityFacts contains a non-field token");
                    }
                    String propertyName = parser.currentName();
                    if (parser.nextToken() == null) {
                        return context.reportInputMismatch(
                                EligibilityFacts.class,
                                "EligibilityFacts ends before a property value");
                    }
                    switch (propertyName) {
                    case "eligibilityType" -> {
                        if (eligibilityTypeSeen) {
                            return context.reportInputMismatch(
                                    EligibilityFacts.class,
                                    "duplicate property eligibilityType");
                        }
                        eligibilityTypeSeen = true;
                        eligibilityType = CanonicalHrisJson.readString(parser, context, "eligibilityType", false);
                    }
                    case "eligible" -> {
                        if (eligibleSeen) {
                            return context.reportInputMismatch(
                                    EligibilityFacts.class,
                                    "duplicate property eligible");
                        }
                        eligibleSeen = true;
                        eligible = CanonicalHrisJson.readBoolean(parser, context, "eligible", false);
                    }
                    case "factRevision" -> {
                        if (factRevisionSeen) {
                            return context.reportInputMismatch(
                                    EligibilityFacts.class,
                                    "duplicate property factRevision");
                        }
                        factRevisionSeen = true;
                        factRevision = CanonicalHrisJson.readLong(parser, context, "factRevision", false);
                    }
                    case "jurisdictionCode" -> {
                        if (jurisdictionCodeSeen) {
                            return context.reportInputMismatch(
                                    EligibilityFacts.class,
                                    "duplicate property jurisdictionCode");
                        }
                        jurisdictionCodeSeen = true;
                        jurisdictionCode = CanonicalHrisJson.readString(parser, context, "jurisdictionCode", true);
                    }
                    default -> {
                        return context.reportInputMismatch(
                                EligibilityFacts.class,
                                "unknown property %s", propertyName);
                    }
                    }
                }
                if (!eligibilityTypeSeen) {
                    return context.reportInputMismatch(EligibilityFacts.class,
                            "missing required property eligibilityType");
                }
                if (!eligibleSeen) {
                    return context.reportInputMismatch(EligibilityFacts.class,
                            "missing required property eligible");
                }
                if (!factRevisionSeen) {
                    return context.reportInputMismatch(EligibilityFacts.class,
                            "missing required property factRevision");
                }
                if (!jurisdictionCodeSeen) {
                    return context.reportInputMismatch(EligibilityFacts.class,
                            "missing required property jurisdictionCode");
                }
                return new EligibilityFacts(
                        eligibilityType,
                        eligible,
                        factRevision,
                        jurisdictionCode);
            }
        }
    }
}
