/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_001
 * Normalized schema SHA-256: 401469d7a1922ec548d7328873fc57709fd6bd3238ab60ac012ad92b266fe49e
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon001WorkerAssignmentSnapshotV1.Deserializer.class)
public record Xcon001WorkerAssignmentSnapshotV1(
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant asOf,
        List<Assignment> assignments,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID personPublicId,
        List<Relationship> relationships,
        long snapshotVersion,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerPublicId,
        String workerStatus) {

    public Xcon001WorkerAssignmentSnapshotV1 {
        Objects.requireNonNull(asOf, "asOf must not be null");
        Objects.requireNonNull(assignments, "assignments must not be null");
        assignments = List.copyOf(assignments);
        if (assignments.size() < 1) {
            throw new IllegalArgumentException("assignments has too few items");
        }
        if (assignments.size() > 1000) {
            throw new IllegalArgumentException("assignments has too many items");
        }
        for (Assignment assignmentsItem : assignments) {
            Objects.requireNonNull(assignmentsItem, "assignmentsItem must not be null");
        }
        Objects.requireNonNull(personPublicId, "personPublicId must not be null");
        Objects.requireNonNull(relationships, "relationships must not be null");
        relationships = List.copyOf(relationships);
        if (relationships.size() < 1) {
            throw new IllegalArgumentException("relationships has too few items");
        }
        if (relationships.size() > 100) {
            throw new IllegalArgumentException("relationships has too many items");
        }
        for (Relationship relationshipsItem : relationships) {
            Objects.requireNonNull(relationshipsItem, "relationshipsItem must not be null");
        }
        if (snapshotVersion < 1L) {
            throw new IllegalArgumentException("snapshotVersion is below its canonical minimum");
        }
        Objects.requireNonNull(workerPublicId, "workerPublicId must not be null");
        Objects.requireNonNull(workerStatus, "workerStatus must not be null");
        if (!Set.of("PENDING", "ACTIVE", "INACTIVE", "TERMINATED").contains(workerStatus)) {
            throw new IllegalArgumentException("workerStatus is not a canonical value");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon001WorkerAssignmentSnapshotV1> {

        @Override
        public Xcon001WorkerAssignmentSnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon001WorkerAssignmentSnapshotV1.class,
                        "Xcon001WorkerAssignmentSnapshotV1 must be encoded as a JSON object");
            }
            Instant asOf = null; boolean asOfSeen = false;
            List<Assignment> assignments = null; boolean assignmentsSeen = false;
            UUID personPublicId = null; boolean personPublicIdSeen = false;
            List<Relationship> relationships = null; boolean relationshipsSeen = false;
            long snapshotVersion = 0L; boolean snapshotVersionSeen = false;
            UUID workerPublicId = null; boolean workerPublicIdSeen = false;
            String workerStatus = null; boolean workerStatusSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon001WorkerAssignmentSnapshotV1.class,
                            "Xcon001WorkerAssignmentSnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon001WorkerAssignmentSnapshotV1.class,
                            "Xcon001WorkerAssignmentSnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "asOf" -> {
                    if (asOfSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property asOf");
                    }
                    asOfSeen = true;
                    asOf = CanonicalHrisJson.readInstant(parser, context, "asOf", false);
                }
                case "assignments" -> {
                    if (assignmentsSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property assignments");
                    }
                    assignmentsSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "assignments must be encoded as a JSON array");
                    }
                    ArrayList<Assignment> assignmentsValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (assignmentsValues.size() >= 1000) {
                            return context.reportInputMismatch(
                                    Xcon001WorkerAssignmentSnapshotV1.class,
                                    "assignments exceeds its canonical item limit");
                        }
                        assignmentsValues.add(CanonicalHrisJson.readObject(parser, context, "assignments[]", Assignment.class, false));
                    }
                    assignments = List.copyOf(assignmentsValues);
                }
                case "personPublicId" -> {
                    if (personPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property personPublicId");
                    }
                    personPublicIdSeen = true;
                    personPublicId = CanonicalHrisJson.readUuid(parser, context, "personPublicId", false);
                }
                case "relationships" -> {
                    if (relationshipsSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property relationships");
                    }
                    relationshipsSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "relationships must be encoded as a JSON array");
                    }
                    ArrayList<Relationship> relationshipsValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (relationshipsValues.size() >= 100) {
                            return context.reportInputMismatch(
                                    Xcon001WorkerAssignmentSnapshotV1.class,
                                    "relationships exceeds its canonical item limit");
                        }
                        relationshipsValues.add(CanonicalHrisJson.readObject(parser, context, "relationships[]", Relationship.class, false));
                    }
                    relationships = List.copyOf(relationshipsValues);
                }
                case "snapshotVersion" -> {
                    if (snapshotVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property snapshotVersion");
                    }
                    snapshotVersionSeen = true;
                    snapshotVersion = CanonicalHrisJson.readLong(parser, context, "snapshotVersion", false);
                }
                case "workerPublicId" -> {
                    if (workerPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property workerPublicId");
                    }
                    workerPublicIdSeen = true;
                    workerPublicId = CanonicalHrisJson.readUuid(parser, context, "workerPublicId", false);
                }
                case "workerStatus" -> {
                    if (workerStatusSeen) {
                        return context.reportInputMismatch(
                                Xcon001WorkerAssignmentSnapshotV1.class,
                                "duplicate property workerStatus");
                    }
                    workerStatusSeen = true;
                    workerStatus = CanonicalHrisJson.readString(parser, context, "workerStatus", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon001WorkerAssignmentSnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!asOfSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property asOf");
            }
            if (!assignmentsSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property assignments");
            }
            if (!personPublicIdSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property personPublicId");
            }
            if (!relationshipsSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property relationships");
            }
            if (!snapshotVersionSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property snapshotVersion");
            }
            if (!workerPublicIdSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property workerPublicId");
            }
            if (!workerStatusSeen) {
                return context.reportInputMismatch(Xcon001WorkerAssignmentSnapshotV1.class,
                        "missing required property workerStatus");
            }
            return new Xcon001WorkerAssignmentSnapshotV1(
                    asOf,
                    assignments,
                    personPublicId,
                    relationships,
                    snapshotVersion,
                    workerPublicId,
                    workerStatus);
        }
    }

    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonDeserialize(using = Assignment.Deserializer.class)
    public record Assignment(
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentPublicId,
            String status,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID legalEntityPublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID organizationPublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID locationPublicId,
            String timeZone,
            String employmentTerms,
            String costCenterKey,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payGroupPublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID compensationBasisPublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID managerAssignmentPublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID jobProfilePublicId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID gradePublicId) {

        public Assignment {
            Objects.requireNonNull(assignmentPublicId, "assignmentPublicId must not be null");
            Objects.requireNonNull(status, "status must not be null");
            if (!Set.of("PENDING", "ACTIVE", "INACTIVE", "ENDED").contains(status)) {
                throw new IllegalArgumentException("status is not a canonical value");
            }
            Objects.requireNonNull(legalEntityPublicId, "legalEntityPublicId must not be null");
            Objects.requireNonNull(organizationPublicId, "organizationPublicId must not be null");
            Objects.requireNonNull(timeZone, "timeZone must not be null");
            if (timeZone.length() > 80) {
                throw new IllegalArgumentException("timeZone is longer than 80");
            }
            if (!Pattern.matches("^[A-Za-z_]+(?:/[A-Za-z0-9_+.-]+)+$", timeZone)) {
                throw new IllegalArgumentException("timeZone does not match its canonical format");
            }
            Objects.requireNonNull(employmentTerms, "employmentTerms must not be null");
            if (!Set.of("FULL_TIME", "PART_TIME", "CASUAL", "TEMPORARY", "OTHER").contains(employmentTerms)) {
                throw new IllegalArgumentException("employmentTerms is not a canonical value");
            }
            if (costCenterKey != null) {
                if (costCenterKey.length() < 1) {
                    throw new IllegalArgumentException("costCenterKey is shorter than 1");
                }
                if (costCenterKey.length() > 80) {
                    throw new IllegalArgumentException("costCenterKey is longer than 80");
                }
            }
        }

        public static final class Deserializer
                extends JsonDeserializer<Assignment> {

            @Override
            public Assignment deserialize(
                    JsonParser parser,
                    DeserializationContext context) throws IOException {
                if (!parser.isExpectedStartObjectToken()) {
                    return context.reportInputMismatch(
                            Assignment.class,
                            "Assignment must be encoded as a JSON object");
                }
                UUID assignmentPublicId = null; boolean assignmentPublicIdSeen = false;
                String status = null; boolean statusSeen = false;
                UUID legalEntityPublicId = null; boolean legalEntityPublicIdSeen = false;
                UUID organizationPublicId = null; boolean organizationPublicIdSeen = false;
                UUID locationPublicId = null; boolean locationPublicIdSeen = false;
                String timeZone = null; boolean timeZoneSeen = false;
                String employmentTerms = null; boolean employmentTermsSeen = false;
                String costCenterKey = null; boolean costCenterKeySeen = false;
                UUID payGroupPublicId = null; boolean payGroupPublicIdSeen = false;
                UUID compensationBasisPublicId = null; boolean compensationBasisPublicIdSeen = false;
                UUID managerAssignmentPublicId = null; boolean managerAssignmentPublicIdSeen = false;
                UUID jobProfilePublicId = null; boolean jobProfilePublicIdSeen = false;
                UUID gradePublicId = null; boolean gradePublicIdSeen = false;
                while (parser.nextToken() != JsonToken.END_OBJECT) {
                    if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                        return context.reportInputMismatch(
                                Assignment.class,
                                "Assignment contains a non-field token");
                    }
                    String propertyName = parser.currentName();
                    if (parser.nextToken() == null) {
                        return context.reportInputMismatch(
                                Assignment.class,
                                "Assignment ends before a property value");
                    }
                    switch (propertyName) {
                    case "assignmentPublicId" -> {
                        if (assignmentPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property assignmentPublicId");
                        }
                        assignmentPublicIdSeen = true;
                        assignmentPublicId = CanonicalHrisJson.readUuid(parser, context, "assignmentPublicId", false);
                    }
                    case "status" -> {
                        if (statusSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property status");
                        }
                        statusSeen = true;
                        status = CanonicalHrisJson.readString(parser, context, "status", false);
                    }
                    case "legalEntityPublicId" -> {
                        if (legalEntityPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property legalEntityPublicId");
                        }
                        legalEntityPublicIdSeen = true;
                        legalEntityPublicId = CanonicalHrisJson.readUuid(parser, context, "legalEntityPublicId", false);
                    }
                    case "organizationPublicId" -> {
                        if (organizationPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property organizationPublicId");
                        }
                        organizationPublicIdSeen = true;
                        organizationPublicId = CanonicalHrisJson.readUuid(parser, context, "organizationPublicId", false);
                    }
                    case "locationPublicId" -> {
                        if (locationPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property locationPublicId");
                        }
                        locationPublicIdSeen = true;
                        locationPublicId = CanonicalHrisJson.readUuid(parser, context, "locationPublicId", true);
                    }
                    case "timeZone" -> {
                        if (timeZoneSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property timeZone");
                        }
                        timeZoneSeen = true;
                        timeZone = CanonicalHrisJson.readString(parser, context, "timeZone", false);
                    }
                    case "employmentTerms" -> {
                        if (employmentTermsSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property employmentTerms");
                        }
                        employmentTermsSeen = true;
                        employmentTerms = CanonicalHrisJson.readString(parser, context, "employmentTerms", false);
                    }
                    case "costCenterKey" -> {
                        if (costCenterKeySeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property costCenterKey");
                        }
                        costCenterKeySeen = true;
                        costCenterKey = CanonicalHrisJson.readString(parser, context, "costCenterKey", true);
                    }
                    case "payGroupPublicId" -> {
                        if (payGroupPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property payGroupPublicId");
                        }
                        payGroupPublicIdSeen = true;
                        payGroupPublicId = CanonicalHrisJson.readUuid(parser, context, "payGroupPublicId", true);
                    }
                    case "compensationBasisPublicId" -> {
                        if (compensationBasisPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property compensationBasisPublicId");
                        }
                        compensationBasisPublicIdSeen = true;
                        compensationBasisPublicId = CanonicalHrisJson.readUuid(parser, context, "compensationBasisPublicId", true);
                    }
                    case "managerAssignmentPublicId" -> {
                        if (managerAssignmentPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property managerAssignmentPublicId");
                        }
                        managerAssignmentPublicIdSeen = true;
                        managerAssignmentPublicId = CanonicalHrisJson.readUuid(parser, context, "managerAssignmentPublicId", true);
                    }
                    case "jobProfilePublicId" -> {
                        if (jobProfilePublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property jobProfilePublicId");
                        }
                        jobProfilePublicIdSeen = true;
                        jobProfilePublicId = CanonicalHrisJson.readUuid(parser, context, "jobProfilePublicId", true);
                    }
                    case "gradePublicId" -> {
                        if (gradePublicIdSeen) {
                            return context.reportInputMismatch(
                                    Assignment.class,
                                    "duplicate property gradePublicId");
                        }
                        gradePublicIdSeen = true;
                        gradePublicId = CanonicalHrisJson.readUuid(parser, context, "gradePublicId", true);
                    }
                    default -> {
                        return context.reportInputMismatch(
                                Assignment.class,
                                "unknown property %s", propertyName);
                    }
                    }
                }
                if (!assignmentPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property assignmentPublicId");
                }
                if (!statusSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property status");
                }
                if (!legalEntityPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property legalEntityPublicId");
                }
                if (!organizationPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property organizationPublicId");
                }
                if (!locationPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property locationPublicId");
                }
                if (!timeZoneSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property timeZone");
                }
                if (!employmentTermsSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property employmentTerms");
                }
                if (!costCenterKeySeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property costCenterKey");
                }
                if (!payGroupPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property payGroupPublicId");
                }
                if (!compensationBasisPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property compensationBasisPublicId");
                }
                if (!managerAssignmentPublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property managerAssignmentPublicId");
                }
                if (!jobProfilePublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property jobProfilePublicId");
                }
                if (!gradePublicIdSeen) {
                    return context.reportInputMismatch(Assignment.class,
                            "missing required property gradePublicId");
                }
                return new Assignment(
                        assignmentPublicId,
                        status,
                        legalEntityPublicId,
                        organizationPublicId,
                        locationPublicId,
                        timeZone,
                        employmentTerms,
                        costCenterKey,
                        payGroupPublicId,
                        compensationBasisPublicId,
                        managerAssignmentPublicId,
                        jobProfilePublicId,
                        gradePublicId);
            }
        }
    }

    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonDeserialize(using = Relationship.Deserializer.class)
    public record Relationship(
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID relationshipPublicId,
            String relationshipType,
            String status,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID legalEntityPublicId,
            @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
            @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo) {

        public Relationship {
            Objects.requireNonNull(relationshipPublicId, "relationshipPublicId must not be null");
            Objects.requireNonNull(relationshipType, "relationshipType must not be null");
            if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", relationshipType)) {
                throw new IllegalArgumentException("relationshipType does not match its canonical format");
            }
            Objects.requireNonNull(status, "status must not be null");
            if (!Set.of("PENDING", "ACTIVE", "INACTIVE", "TERMINATED").contains(status)) {
                throw new IllegalArgumentException("status is not a canonical value");
            }
            Objects.requireNonNull(legalEntityPublicId, "legalEntityPublicId must not be null");
            Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        }

        public static final class Deserializer
                extends JsonDeserializer<Relationship> {

            @Override
            public Relationship deserialize(
                    JsonParser parser,
                    DeserializationContext context) throws IOException {
                if (!parser.isExpectedStartObjectToken()) {
                    return context.reportInputMismatch(
                            Relationship.class,
                            "Relationship must be encoded as a JSON object");
                }
                UUID relationshipPublicId = null; boolean relationshipPublicIdSeen = false;
                String relationshipType = null; boolean relationshipTypeSeen = false;
                String status = null; boolean statusSeen = false;
                UUID legalEntityPublicId = null; boolean legalEntityPublicIdSeen = false;
                LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
                LocalDate effectiveTo = null; boolean effectiveToSeen = false;
                while (parser.nextToken() != JsonToken.END_OBJECT) {
                    if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                        return context.reportInputMismatch(
                                Relationship.class,
                                "Relationship contains a non-field token");
                    }
                    String propertyName = parser.currentName();
                    if (parser.nextToken() == null) {
                        return context.reportInputMismatch(
                                Relationship.class,
                                "Relationship ends before a property value");
                    }
                    switch (propertyName) {
                    case "relationshipPublicId" -> {
                        if (relationshipPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property relationshipPublicId");
                        }
                        relationshipPublicIdSeen = true;
                        relationshipPublicId = CanonicalHrisJson.readUuid(parser, context, "relationshipPublicId", false);
                    }
                    case "relationshipType" -> {
                        if (relationshipTypeSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property relationshipType");
                        }
                        relationshipTypeSeen = true;
                        relationshipType = CanonicalHrisJson.readString(parser, context, "relationshipType", false);
                    }
                    case "status" -> {
                        if (statusSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property status");
                        }
                        statusSeen = true;
                        status = CanonicalHrisJson.readString(parser, context, "status", false);
                    }
                    case "legalEntityPublicId" -> {
                        if (legalEntityPublicIdSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property legalEntityPublicId");
                        }
                        legalEntityPublicIdSeen = true;
                        legalEntityPublicId = CanonicalHrisJson.readUuid(parser, context, "legalEntityPublicId", false);
                    }
                    case "effectiveFrom" -> {
                        if (effectiveFromSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property effectiveFrom");
                        }
                        effectiveFromSeen = true;
                        effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                    }
                    case "effectiveTo" -> {
                        if (effectiveToSeen) {
                            return context.reportInputMismatch(
                                    Relationship.class,
                                    "duplicate property effectiveTo");
                        }
                        effectiveToSeen = true;
                        effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                    }
                    default -> {
                        return context.reportInputMismatch(
                                Relationship.class,
                                "unknown property %s", propertyName);
                    }
                    }
                }
                if (!relationshipPublicIdSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property relationshipPublicId");
                }
                if (!relationshipTypeSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property relationshipType");
                }
                if (!statusSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property status");
                }
                if (!legalEntityPublicIdSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property legalEntityPublicId");
                }
                if (!effectiveFromSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property effectiveFrom");
                }
                if (!effectiveToSeen) {
                    return context.reportInputMismatch(Relationship.class,
                            "missing required property effectiveTo");
                }
                return new Relationship(
                        relationshipPublicId,
                        relationshipType,
                        status,
                        legalEntityPublicId,
                        effectiveFrom,
                        effectiveTo);
            }
        }
    }
}
