/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_013
 * Normalized schema SHA-256: 38776a227486baa05aeb1cb895737db6bcf29db267c84cb31d7603a7f5752a5c
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.Instant;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon013PeopleHomeContributionChangedV1.Deserializer.class)
public record Xcon013PeopleHomeContributionChangedV1(
        String ownerPopulationScope,
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant freshUntil,
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant generatedAt,
        String module,
        String payloadDigest,
        String payloadRef,
        long scopeRevision,
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant staleAfter,
        String state,
        String widgetKey) {

    public Xcon013PeopleHomeContributionChangedV1 {
        Objects.requireNonNull(ownerPopulationScope, "ownerPopulationScope must not be null");
        if (!Set.of("SELF", "TEAM", "NAMED_POPULATION").contains(ownerPopulationScope)) {
            throw new IllegalArgumentException("ownerPopulationScope is not a canonical value");
        }
        Objects.requireNonNull(freshUntil, "freshUntil must not be null");
        Objects.requireNonNull(generatedAt, "generatedAt must not be null");
        Objects.requireNonNull(module, "module must not be null");
        if (!"HRM".equals(module)) {
            throw new IllegalArgumentException("module must equal " + "HRM");
        }
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(payloadRef, "payloadRef must not be null");
        if (!Pattern.matches("^href_[A-Za-z0-9_-]{16,128}$", payloadRef)) {
            throw new IllegalArgumentException("payloadRef does not match its canonical format");
        }
        if (scopeRevision < 1L) {
            throw new IllegalArgumentException("scopeRevision is below its canonical minimum");
        }
        Objects.requireNonNull(staleAfter, "staleAfter must not be null");
        Objects.requireNonNull(state, "state must not be null");
        if (!Set.of("FRESH", "STALE", "DEGRADED", "UNAVAILABLE").contains(state)) {
            throw new IllegalArgumentException("state is not a canonical value");
        }
        Objects.requireNonNull(widgetKey, "widgetKey must not be null");
        if (!Pattern.matches("^people-[a-z0-9-]{1,33}$", widgetKey)) {
            throw new IllegalArgumentException("widgetKey does not match its canonical format");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon013PeopleHomeContributionChangedV1> {

        @Override
        public Xcon013PeopleHomeContributionChangedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon013PeopleHomeContributionChangedV1.class,
                        "Xcon013PeopleHomeContributionChangedV1 must be encoded as a JSON object");
            }
            String ownerPopulationScope = null; boolean ownerPopulationScopeSeen = false;
            Instant freshUntil = null; boolean freshUntilSeen = false;
            Instant generatedAt = null; boolean generatedAtSeen = false;
            String module = null; boolean moduleSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            String payloadRef = null; boolean payloadRefSeen = false;
            long scopeRevision = 0L; boolean scopeRevisionSeen = false;
            Instant staleAfter = null; boolean staleAfterSeen = false;
            String state = null; boolean stateSeen = false;
            String widgetKey = null; boolean widgetKeySeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon013PeopleHomeContributionChangedV1.class,
                            "Xcon013PeopleHomeContributionChangedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon013PeopleHomeContributionChangedV1.class,
                            "Xcon013PeopleHomeContributionChangedV1 ends before a property value");
                }
                switch (propertyName) {
                case "ownerPopulationScope" -> {
                    if (ownerPopulationScopeSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property ownerPopulationScope");
                    }
                    ownerPopulationScopeSeen = true;
                    ownerPopulationScope = CanonicalHrisJson.readString(parser, context, "ownerPopulationScope", false);
                }
                case "freshUntil" -> {
                    if (freshUntilSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property freshUntil");
                    }
                    freshUntilSeen = true;
                    freshUntil = CanonicalHrisJson.readInstant(parser, context, "freshUntil", false);
                }
                case "generatedAt" -> {
                    if (generatedAtSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property generatedAt");
                    }
                    generatedAtSeen = true;
                    generatedAt = CanonicalHrisJson.readInstant(parser, context, "generatedAt", false);
                }
                case "module" -> {
                    if (moduleSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property module");
                    }
                    moduleSeen = true;
                    module = CanonicalHrisJson.readString(parser, context, "module", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "payloadRef" -> {
                    if (payloadRefSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property payloadRef");
                    }
                    payloadRefSeen = true;
                    payloadRef = CanonicalHrisJson.readString(parser, context, "payloadRef", false);
                }
                case "scopeRevision" -> {
                    if (scopeRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property scopeRevision");
                    }
                    scopeRevisionSeen = true;
                    scopeRevision = CanonicalHrisJson.readLong(parser, context, "scopeRevision", false);
                }
                case "staleAfter" -> {
                    if (staleAfterSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property staleAfter");
                    }
                    staleAfterSeen = true;
                    staleAfter = CanonicalHrisJson.readInstant(parser, context, "staleAfter", false);
                }
                case "state" -> {
                    if (stateSeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property state");
                    }
                    stateSeen = true;
                    state = CanonicalHrisJson.readString(parser, context, "state", false);
                }
                case "widgetKey" -> {
                    if (widgetKeySeen) {
                        return context.reportInputMismatch(
                                Xcon013PeopleHomeContributionChangedV1.class,
                                "duplicate property widgetKey");
                    }
                    widgetKeySeen = true;
                    widgetKey = CanonicalHrisJson.readString(parser, context, "widgetKey", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon013PeopleHomeContributionChangedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!ownerPopulationScopeSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property ownerPopulationScope");
            }
            if (!freshUntilSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property freshUntil");
            }
            if (!generatedAtSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property generatedAt");
            }
            if (!moduleSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property module");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property payloadDigest");
            }
            if (!payloadRefSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property payloadRef");
            }
            if (!scopeRevisionSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property scopeRevision");
            }
            if (!staleAfterSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property staleAfter");
            }
            if (!stateSeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property state");
            }
            if (!widgetKeySeen) {
                return context.reportInputMismatch(Xcon013PeopleHomeContributionChangedV1.class,
                        "missing required property widgetKey");
            }
            return new Xcon013PeopleHomeContributionChangedV1(
                    ownerPopulationScope,
                    freshUntil,
                    generatedAt,
                    module,
                    payloadDigest,
                    payloadRef,
                    scopeRevision,
                    staleAfter,
                    state,
                    widgetKey);
        }
    }
}
