/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_019
 * Normalized schema SHA-256: 8e202d9657e4e85c2891457b9eb42e567fc8d63d12e7e0f0cdff6f2a99042623
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon019WorkerBankAccountTokenSnapshotV1.Deserializer.class)
public record Xcon019WorkerBankAccountTokenSnapshotV1(
        String bankAccountToken,
        String currency,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
        String maskedAccountDisplay,
        String payloadDigest,
        int paymentPriority,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId) {

    public Xcon019WorkerBankAccountTokenSnapshotV1 {
        Objects.requireNonNull(bankAccountToken, "bankAccountToken must not be null");
        if (!Pattern.matches("^vault_[A-Za-z0-9_-]{24,160}$", bankAccountToken)) {
            throw new IllegalArgumentException("bankAccountToken does not match its canonical format");
        }
        Objects.requireNonNull(currency, "currency must not be null");
        if (!Pattern.matches("^[A-Z]{3}$", currency)) {
            throw new IllegalArgumentException("currency does not match its canonical format");
        }
        Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        Objects.requireNonNull(maskedAccountDisplay, "maskedAccountDisplay must not be null");
        if (maskedAccountDisplay.length() < 4) {
            throw new IllegalArgumentException("maskedAccountDisplay is shorter than 4");
        }
        if (maskedAccountDisplay.length() > 40) {
            throw new IllegalArgumentException("maskedAccountDisplay is longer than 40");
        }
        if (!Pattern.matches("^(?=.*[*Xx\u2022]).+$", maskedAccountDisplay)) {
            throw new IllegalArgumentException("maskedAccountDisplay does not match its canonical format");
        }
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        if (paymentPriority < 1L) {
            throw new IllegalArgumentException("paymentPriority is below its canonical minimum");
        }
        if (paymentPriority > 99L) {
            throw new IllegalArgumentException("paymentPriority exceeds its canonical maximum");
        }
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        Objects.requireNonNull(workerId, "workerId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon019WorkerBankAccountTokenSnapshotV1> {

        @Override
        public Xcon019WorkerBankAccountTokenSnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "Xcon019WorkerBankAccountTokenSnapshotV1 must be encoded as a JSON object");
            }
            String bankAccountToken = null; boolean bankAccountTokenSeen = false;
            String currency = null; boolean currencySeen = false;
            LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
            LocalDate effectiveTo = null; boolean effectiveToSeen = false;
            String maskedAccountDisplay = null; boolean maskedAccountDisplaySeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            int paymentPriority = 0; boolean paymentPrioritySeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            UUID workerId = null; boolean workerIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon019WorkerBankAccountTokenSnapshotV1.class,
                            "Xcon019WorkerBankAccountTokenSnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon019WorkerBankAccountTokenSnapshotV1.class,
                            "Xcon019WorkerBankAccountTokenSnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "bankAccountToken" -> {
                    if (bankAccountTokenSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property bankAccountToken");
                    }
                    bankAccountTokenSeen = true;
                    bankAccountToken = CanonicalHrisJson.readString(parser, context, "bankAccountToken", false);
                }
                case "currency" -> {
                    if (currencySeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property currency");
                    }
                    currencySeen = true;
                    currency = CanonicalHrisJson.readString(parser, context, "currency", false);
                }
                case "effectiveFrom" -> {
                    if (effectiveFromSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property effectiveFrom");
                    }
                    effectiveFromSeen = true;
                    effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                }
                case "effectiveTo" -> {
                    if (effectiveToSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property effectiveTo");
                    }
                    effectiveToSeen = true;
                    effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                }
                case "maskedAccountDisplay" -> {
                    if (maskedAccountDisplaySeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property maskedAccountDisplay");
                    }
                    maskedAccountDisplaySeen = true;
                    maskedAccountDisplay = CanonicalHrisJson.readString(parser, context, "maskedAccountDisplay", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "paymentPriority" -> {
                    if (paymentPrioritySeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property paymentPriority");
                    }
                    paymentPrioritySeen = true;
                    paymentPriority = CanonicalHrisJson.readInt(parser, context, "paymentPriority", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                case "workerId" -> {
                    if (workerIdSeen) {
                        return context.reportInputMismatch(
                                Xcon019WorkerBankAccountTokenSnapshotV1.class,
                                "duplicate property workerId");
                    }
                    workerIdSeen = true;
                    workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon019WorkerBankAccountTokenSnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!bankAccountTokenSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property bankAccountToken");
            }
            if (!currencySeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property currency");
            }
            if (!effectiveFromSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property effectiveFrom");
            }
            if (!effectiveToSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property effectiveTo");
            }
            if (!maskedAccountDisplaySeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property maskedAccountDisplay");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!paymentPrioritySeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property paymentPriority");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property sourceVersion");
            }
            if (!workerIdSeen) {
                return context.reportInputMismatch(Xcon019WorkerBankAccountTokenSnapshotV1.class,
                        "missing required property workerId");
            }
            return new Xcon019WorkerBankAccountTokenSnapshotV1(
                    bankAccountToken,
                    currency,
                    effectiveFrom,
                    effectiveTo,
                    maskedAccountDisplay,
                    payloadDigest,
                    paymentPriority,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion,
                    workerId);
        }
    }
}
