/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_010
 * Normalized schema SHA-256: 8e1c693f373482b60653b8d21d851125db682b142814f24067de94e90f404c93
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon010TimePeriodReopenedV1.Deserializer.class)
public record Xcon010TimePeriodReopenedV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closePeriodId,
        long newRevision,
        long priorCloseRevision,
        String reasonCode) {

    public Xcon010TimePeriodReopenedV1 {
        Objects.requireNonNull(closePeriodId, "closePeriodId must not be null");
        if (newRevision < 1L) {
            throw new IllegalArgumentException("newRevision is below its canonical minimum");
        }
        if (priorCloseRevision < 1L) {
            throw new IllegalArgumentException("priorCloseRevision is below its canonical minimum");
        }
        Objects.requireNonNull(reasonCode, "reasonCode must not be null");
        if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", reasonCode)) {
            throw new IllegalArgumentException("reasonCode does not match its canonical format");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon010TimePeriodReopenedV1> {

        @Override
        public Xcon010TimePeriodReopenedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon010TimePeriodReopenedV1.class,
                        "Xcon010TimePeriodReopenedV1 must be encoded as a JSON object");
            }
            UUID closePeriodId = null; boolean closePeriodIdSeen = false;
            long newRevision = 0L; boolean newRevisionSeen = false;
            long priorCloseRevision = 0L; boolean priorCloseRevisionSeen = false;
            String reasonCode = null; boolean reasonCodeSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon010TimePeriodReopenedV1.class,
                            "Xcon010TimePeriodReopenedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon010TimePeriodReopenedV1.class,
                            "Xcon010TimePeriodReopenedV1 ends before a property value");
                }
                switch (propertyName) {
                case "closePeriodId" -> {
                    if (closePeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon010TimePeriodReopenedV1.class,
                                "duplicate property closePeriodId");
                    }
                    closePeriodIdSeen = true;
                    closePeriodId = CanonicalHrisJson.readUuid(parser, context, "closePeriodId", false);
                }
                case "newRevision" -> {
                    if (newRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon010TimePeriodReopenedV1.class,
                                "duplicate property newRevision");
                    }
                    newRevisionSeen = true;
                    newRevision = CanonicalHrisJson.readLong(parser, context, "newRevision", false);
                }
                case "priorCloseRevision" -> {
                    if (priorCloseRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon010TimePeriodReopenedV1.class,
                                "duplicate property priorCloseRevision");
                    }
                    priorCloseRevisionSeen = true;
                    priorCloseRevision = CanonicalHrisJson.readLong(parser, context, "priorCloseRevision", false);
                }
                case "reasonCode" -> {
                    if (reasonCodeSeen) {
                        return context.reportInputMismatch(
                                Xcon010TimePeriodReopenedV1.class,
                                "duplicate property reasonCode");
                    }
                    reasonCodeSeen = true;
                    reasonCode = CanonicalHrisJson.readString(parser, context, "reasonCode", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon010TimePeriodReopenedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!closePeriodIdSeen) {
                return context.reportInputMismatch(Xcon010TimePeriodReopenedV1.class,
                        "missing required property closePeriodId");
            }
            if (!newRevisionSeen) {
                return context.reportInputMismatch(Xcon010TimePeriodReopenedV1.class,
                        "missing required property newRevision");
            }
            if (!priorCloseRevisionSeen) {
                return context.reportInputMismatch(Xcon010TimePeriodReopenedV1.class,
                        "missing required property priorCloseRevision");
            }
            if (!reasonCodeSeen) {
                return context.reportInputMismatch(Xcon010TimePeriodReopenedV1.class,
                        "missing required property reasonCode");
            }
            return new Xcon010TimePeriodReopenedV1(
                    closePeriodId,
                    newRevision,
                    priorCloseRevision,
                    reasonCode);
        }
    }
}
