/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_021
 * Normalized schema SHA-256: a1189eeda37bd3874e1dc20b2e2d291c9bfb897cc1d7ddbb793923cdbc59d1cb
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon021ApprovedCompensationPlanSnapshotPublishedV2.Deserializer.class)
public record Xcon021ApprovedCompensationPlanSnapshotPublishedV2(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID aggregateId,
        long aggregateVersion,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID approvalReceiptId,
        long approvalRevision,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID correlationId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID cycleId,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveDate,
        String fromState,
        int lineCount,
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant occurredAt,
        String payloadDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID planId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion,
        String toState) {

    public Xcon021ApprovedCompensationPlanSnapshotPublishedV2 {
        Objects.requireNonNull(aggregateId, "aggregateId must not be null");
        if (aggregateVersion < 1L) {
            throw new IllegalArgumentException("aggregateVersion is below its canonical minimum");
        }
        Objects.requireNonNull(approvalReceiptId, "approvalReceiptId must not be null");
        if (approvalRevision < 1L) {
            throw new IllegalArgumentException("approvalRevision is below its canonical minimum");
        }
        Objects.requireNonNull(correlationId, "correlationId must not be null");
        Objects.requireNonNull(cycleId, "cycleId must not be null");
        Objects.requireNonNull(effectiveDate, "effectiveDate must not be null");
        Objects.requireNonNull(fromState, "fromState must not be null");
        if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", fromState)) {
            throw new IllegalArgumentException("fromState does not match its canonical format");
        }
        if (lineCount < 1L) {
            throw new IllegalArgumentException("lineCount is below its canonical minimum");
        }
        if (lineCount > 100000L) {
            throw new IllegalArgumentException("lineCount exceeds its canonical maximum");
        }
        Objects.requireNonNull(occurredAt, "occurredAt must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(planId, "planId must not be null");
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        Objects.requireNonNull(toState, "toState must not be null");
        if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", toState)) {
            throw new IllegalArgumentException("toState does not match its canonical format");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon021ApprovedCompensationPlanSnapshotPublishedV2> {

        @Override
        public Xcon021ApprovedCompensationPlanSnapshotPublishedV2 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "Xcon021ApprovedCompensationPlanSnapshotPublishedV2 must be encoded as a JSON object");
            }
            UUID aggregateId = null; boolean aggregateIdSeen = false;
            long aggregateVersion = 0L; boolean aggregateVersionSeen = false;
            UUID approvalReceiptId = null; boolean approvalReceiptIdSeen = false;
            long approvalRevision = 0L; boolean approvalRevisionSeen = false;
            UUID correlationId = null; boolean correlationIdSeen = false;
            UUID cycleId = null; boolean cycleIdSeen = false;
            LocalDate effectiveDate = null; boolean effectiveDateSeen = false;
            String fromState = null; boolean fromStateSeen = false;
            int lineCount = 0; boolean lineCountSeen = false;
            Instant occurredAt = null; boolean occurredAtSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            UUID planId = null; boolean planIdSeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            String toState = null; boolean toStateSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                            "Xcon021ApprovedCompensationPlanSnapshotPublishedV2 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                            "Xcon021ApprovedCompensationPlanSnapshotPublishedV2 ends before a property value");
                }
                switch (propertyName) {
                case "aggregateId" -> {
                    if (aggregateIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property aggregateId");
                    }
                    aggregateIdSeen = true;
                    aggregateId = CanonicalHrisJson.readUuid(parser, context, "aggregateId", false);
                }
                case "aggregateVersion" -> {
                    if (aggregateVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property aggregateVersion");
                    }
                    aggregateVersionSeen = true;
                    aggregateVersion = CanonicalHrisJson.readLong(parser, context, "aggregateVersion", false);
                }
                case "approvalReceiptId" -> {
                    if (approvalReceiptIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property approvalReceiptId");
                    }
                    approvalReceiptIdSeen = true;
                    approvalReceiptId = CanonicalHrisJson.readUuid(parser, context, "approvalReceiptId", false);
                }
                case "approvalRevision" -> {
                    if (approvalRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property approvalRevision");
                    }
                    approvalRevisionSeen = true;
                    approvalRevision = CanonicalHrisJson.readLong(parser, context, "approvalRevision", false);
                }
                case "correlationId" -> {
                    if (correlationIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property correlationId");
                    }
                    correlationIdSeen = true;
                    correlationId = CanonicalHrisJson.readUuid(parser, context, "correlationId", false);
                }
                case "cycleId" -> {
                    if (cycleIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property cycleId");
                    }
                    cycleIdSeen = true;
                    cycleId = CanonicalHrisJson.readUuid(parser, context, "cycleId", false);
                }
                case "effectiveDate" -> {
                    if (effectiveDateSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property effectiveDate");
                    }
                    effectiveDateSeen = true;
                    effectiveDate = CanonicalHrisJson.readDate(parser, context, "effectiveDate", false);
                }
                case "fromState" -> {
                    if (fromStateSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property fromState");
                    }
                    fromStateSeen = true;
                    fromState = CanonicalHrisJson.readString(parser, context, "fromState", false);
                }
                case "lineCount" -> {
                    if (lineCountSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property lineCount");
                    }
                    lineCountSeen = true;
                    lineCount = CanonicalHrisJson.readInt(parser, context, "lineCount", false);
                }
                case "occurredAt" -> {
                    if (occurredAtSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property occurredAt");
                    }
                    occurredAtSeen = true;
                    occurredAt = CanonicalHrisJson.readInstant(parser, context, "occurredAt", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "planId" -> {
                    if (planIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property planId");
                    }
                    planIdSeen = true;
                    planId = CanonicalHrisJson.readUuid(parser, context, "planId", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                case "toState" -> {
                    if (toStateSeen) {
                        return context.reportInputMismatch(
                                Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                                "duplicate property toState");
                    }
                    toStateSeen = true;
                    toState = CanonicalHrisJson.readString(parser, context, "toState", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!aggregateIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property aggregateId");
            }
            if (!aggregateVersionSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property aggregateVersion");
            }
            if (!approvalReceiptIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property approvalReceiptId");
            }
            if (!approvalRevisionSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property approvalRevision");
            }
            if (!correlationIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property correlationId");
            }
            if (!cycleIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property cycleId");
            }
            if (!effectiveDateSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property effectiveDate");
            }
            if (!fromStateSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property fromState");
            }
            if (!lineCountSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property lineCount");
            }
            if (!occurredAtSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property occurredAt");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property payloadDigest");
            }
            if (!planIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property planId");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property sourceVersion");
            }
            if (!toStateSeen) {
                return context.reportInputMismatch(Xcon021ApprovedCompensationPlanSnapshotPublishedV2.class,
                        "missing required property toState");
            }
            return new Xcon021ApprovedCompensationPlanSnapshotPublishedV2(
                    aggregateId,
                    aggregateVersion,
                    approvalReceiptId,
                    approvalRevision,
                    correlationId,
                    cycleId,
                    effectiveDate,
                    fromState,
                    lineCount,
                    occurredAt,
                    payloadDigest,
                    planId,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion,
                    toState);
        }
    }
}
