/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_006
 * Normalized schema SHA-256: 187be73247a9eccb0e8af10afbbe32be8bb515c9f842b9443795d55e3be0d6ad
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon006OrganizationChangedV1.Deserializer.class)
public record Xcon006OrganizationChangedV1(
        @JsonSerialize(contentUsing = CanonicalHrisJson.UuidSerializer.class) List<UUID> changedOrganizationPublicIds,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveDate,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID revisionPublicId,
        String snapshotDigest) {

    public Xcon006OrganizationChangedV1 {
        Objects.requireNonNull(changedOrganizationPublicIds, "changedOrganizationPublicIds must not be null");
        changedOrganizationPublicIds = List.copyOf(changedOrganizationPublicIds);
        if (changedOrganizationPublicIds.size() < 1) {
            throw new IllegalArgumentException("changedOrganizationPublicIds has too few items");
        }
        if (changedOrganizationPublicIds.size() > 1000) {
            throw new IllegalArgumentException("changedOrganizationPublicIds has too many items");
        }
        if (new HashSet<>(changedOrganizationPublicIds).size() != changedOrganizationPublicIds.size()) {
            throw new IllegalArgumentException("changedOrganizationPublicIds must contain unique items");
        }
        for (UUID changedOrganizationPublicIdsItem : changedOrganizationPublicIds) {
            Objects.requireNonNull(changedOrganizationPublicIdsItem, "changedOrganizationPublicIdsItem must not be null");
        }
        Objects.requireNonNull(effectiveDate, "effectiveDate must not be null");
        Objects.requireNonNull(revisionPublicId, "revisionPublicId must not be null");
        Objects.requireNonNull(snapshotDigest, "snapshotDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", snapshotDigest)) {
            throw new IllegalArgumentException("snapshotDigest does not match its canonical format");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon006OrganizationChangedV1> {

        @Override
        public Xcon006OrganizationChangedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon006OrganizationChangedV1.class,
                        "Xcon006OrganizationChangedV1 must be encoded as a JSON object");
            }
            List<UUID> changedOrganizationPublicIds = null; boolean changedOrganizationPublicIdsSeen = false;
            LocalDate effectiveDate = null; boolean effectiveDateSeen = false;
            UUID revisionPublicId = null; boolean revisionPublicIdSeen = false;
            String snapshotDigest = null; boolean snapshotDigestSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon006OrganizationChangedV1.class,
                            "Xcon006OrganizationChangedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon006OrganizationChangedV1.class,
                            "Xcon006OrganizationChangedV1 ends before a property value");
                }
                switch (propertyName) {
                case "changedOrganizationPublicIds" -> {
                    if (changedOrganizationPublicIdsSeen) {
                        return context.reportInputMismatch(
                                Xcon006OrganizationChangedV1.class,
                                "duplicate property changedOrganizationPublicIds");
                    }
                    changedOrganizationPublicIdsSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon006OrganizationChangedV1.class,
                                "changedOrganizationPublicIds must be encoded as a JSON array");
                    }
                    ArrayList<UUID> changedOrganizationPublicIdsValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (changedOrganizationPublicIdsValues.size() >= 1000) {
                            return context.reportInputMismatch(
                                    Xcon006OrganizationChangedV1.class,
                                    "changedOrganizationPublicIds exceeds its canonical item limit");
                        }
                        changedOrganizationPublicIdsValues.add(CanonicalHrisJson.readUuid(parser, context, "changedOrganizationPublicIds[]", false));
                    }
                    changedOrganizationPublicIds = List.copyOf(changedOrganizationPublicIdsValues);
                }
                case "effectiveDate" -> {
                    if (effectiveDateSeen) {
                        return context.reportInputMismatch(
                                Xcon006OrganizationChangedV1.class,
                                "duplicate property effectiveDate");
                    }
                    effectiveDateSeen = true;
                    effectiveDate = CanonicalHrisJson.readDate(parser, context, "effectiveDate", false);
                }
                case "revisionPublicId" -> {
                    if (revisionPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon006OrganizationChangedV1.class,
                                "duplicate property revisionPublicId");
                    }
                    revisionPublicIdSeen = true;
                    revisionPublicId = CanonicalHrisJson.readUuid(parser, context, "revisionPublicId", false);
                }
                case "snapshotDigest" -> {
                    if (snapshotDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon006OrganizationChangedV1.class,
                                "duplicate property snapshotDigest");
                    }
                    snapshotDigestSeen = true;
                    snapshotDigest = CanonicalHrisJson.readString(parser, context, "snapshotDigest", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon006OrganizationChangedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!changedOrganizationPublicIdsSeen) {
                return context.reportInputMismatch(Xcon006OrganizationChangedV1.class,
                        "missing required property changedOrganizationPublicIds");
            }
            if (!effectiveDateSeen) {
                return context.reportInputMismatch(Xcon006OrganizationChangedV1.class,
                        "missing required property effectiveDate");
            }
            if (!revisionPublicIdSeen) {
                return context.reportInputMismatch(Xcon006OrganizationChangedV1.class,
                        "missing required property revisionPublicId");
            }
            if (!snapshotDigestSeen) {
                return context.reportInputMismatch(Xcon006OrganizationChangedV1.class,
                        "missing required property snapshotDigest");
            }
            return new Xcon006OrganizationChangedV1(
                    changedOrganizationPublicIds,
                    effectiveDate,
                    revisionPublicId,
                    snapshotDigest);
        }
    }
}
