/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_007
 * Normalized schema SHA-256: a77a43424969a8688962f46c873e9bb134142d67dfd1048898fda257ab15f0e3
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon007CompensationBasisChangedV1.Deserializer.class)
public record Xcon007CompensationBasisChangedV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentPublicId,
        String basisType,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID compensationBasisPublicId,
        long newAggregateVersion,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate validFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate validTo) {

    public Xcon007CompensationBasisChangedV1 {
        Objects.requireNonNull(assignmentPublicId, "assignmentPublicId must not be null");
        Objects.requireNonNull(basisType, "basisType must not be null");
        if (!Set.of("SALARY", "HOURLY", "DAILY", "PIECE", "OTHER").contains(basisType)) {
            throw new IllegalArgumentException("basisType is not a canonical value");
        }
        Objects.requireNonNull(compensationBasisPublicId, "compensationBasisPublicId must not be null");
        if (newAggregateVersion < 1L) {
            throw new IllegalArgumentException("newAggregateVersion is below its canonical minimum");
        }
        Objects.requireNonNull(validFrom, "validFrom must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon007CompensationBasisChangedV1> {

        @Override
        public Xcon007CompensationBasisChangedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon007CompensationBasisChangedV1.class,
                        "Xcon007CompensationBasisChangedV1 must be encoded as a JSON object");
            }
            UUID assignmentPublicId = null; boolean assignmentPublicIdSeen = false;
            String basisType = null; boolean basisTypeSeen = false;
            UUID compensationBasisPublicId = null; boolean compensationBasisPublicIdSeen = false;
            long newAggregateVersion = 0L; boolean newAggregateVersionSeen = false;
            LocalDate validFrom = null; boolean validFromSeen = false;
            LocalDate validTo = null; boolean validToSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon007CompensationBasisChangedV1.class,
                            "Xcon007CompensationBasisChangedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon007CompensationBasisChangedV1.class,
                            "Xcon007CompensationBasisChangedV1 ends before a property value");
                }
                switch (propertyName) {
                case "assignmentPublicId" -> {
                    if (assignmentPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property assignmentPublicId");
                    }
                    assignmentPublicIdSeen = true;
                    assignmentPublicId = CanonicalHrisJson.readUuid(parser, context, "assignmentPublicId", false);
                }
                case "basisType" -> {
                    if (basisTypeSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property basisType");
                    }
                    basisTypeSeen = true;
                    basisType = CanonicalHrisJson.readString(parser, context, "basisType", false);
                }
                case "compensationBasisPublicId" -> {
                    if (compensationBasisPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property compensationBasisPublicId");
                    }
                    compensationBasisPublicIdSeen = true;
                    compensationBasisPublicId = CanonicalHrisJson.readUuid(parser, context, "compensationBasisPublicId", false);
                }
                case "newAggregateVersion" -> {
                    if (newAggregateVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property newAggregateVersion");
                    }
                    newAggregateVersionSeen = true;
                    newAggregateVersion = CanonicalHrisJson.readLong(parser, context, "newAggregateVersion", false);
                }
                case "validFrom" -> {
                    if (validFromSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property validFrom");
                    }
                    validFromSeen = true;
                    validFrom = CanonicalHrisJson.readDate(parser, context, "validFrom", false);
                }
                case "validTo" -> {
                    if (validToSeen) {
                        return context.reportInputMismatch(
                                Xcon007CompensationBasisChangedV1.class,
                                "duplicate property validTo");
                    }
                    validToSeen = true;
                    validTo = CanonicalHrisJson.readDate(parser, context, "validTo", true);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon007CompensationBasisChangedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!assignmentPublicIdSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property assignmentPublicId");
            }
            if (!basisTypeSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property basisType");
            }
            if (!compensationBasisPublicIdSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property compensationBasisPublicId");
            }
            if (!newAggregateVersionSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property newAggregateVersion");
            }
            if (!validFromSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property validFrom");
            }
            if (!validToSeen) {
                return context.reportInputMismatch(Xcon007CompensationBasisChangedV1.class,
                        "missing required property validTo");
            }
            return new Xcon007CompensationBasisChangedV1(
                    assignmentPublicId,
                    basisType,
                    compensationBasisPublicId,
                    newAggregateVersion,
                    validFrom,
                    validTo);
        }
    }
}
