/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_008
 * Normalized schema SHA-256: bb481b337dfdc237258f67bd2034471be5b0e6a5f22df456820eab5b4b5acab8
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalDecimalJson;
import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Currency;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon008ClosedTimeResultV1.Deserializer.class)
public record Xcon008ClosedTimeResultV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closePeriodId,
        long closeRevision,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closedTimeResultId,
        long ledgerRevisionFrom,
        long ledgerRevisionTo,
        int lineCount,
        List<ClosedTimeLine> lines,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payPeriodId,
        String payloadDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payrollEntityId,
        String ruleDigest,
        String sourceDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID supersedesResultId,
        int workerCount) {

    public Xcon008ClosedTimeResultV1 {
        Objects.requireNonNull(closePeriodId, "closePeriodId must not be null");
        if (closeRevision < 1L) {
            throw new IllegalArgumentException("closeRevision is below its canonical minimum");
        }
        Objects.requireNonNull(closedTimeResultId, "closedTimeResultId must not be null");
        if (ledgerRevisionFrom < 1L) {
            throw new IllegalArgumentException("ledgerRevisionFrom is below its canonical minimum");
        }
        if (ledgerRevisionTo < 1L) {
            throw new IllegalArgumentException("ledgerRevisionTo is below its canonical minimum");
        }
        if (lineCount < 0L) {
            throw new IllegalArgumentException("lineCount is below its canonical minimum");
        }
        if (lineCount > 1000000L) {
            throw new IllegalArgumentException("lineCount exceeds its canonical maximum");
        }
        Objects.requireNonNull(lines, "lines must not be null");
        lines = List.copyOf(lines);
        if (lines.size() < 0) {
            throw new IllegalArgumentException("lines has too few items");
        }
        if (lines.size() > 1000000) {
            throw new IllegalArgumentException("lines has too many items");
        }
        for (ClosedTimeLine linesItem : lines) {
            Objects.requireNonNull(linesItem, "linesItem must not be null");
        }
        Objects.requireNonNull(payPeriodId, "payPeriodId must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(payrollEntityId, "payrollEntityId must not be null");
        Objects.requireNonNull(ruleDigest, "ruleDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", ruleDigest)) {
            throw new IllegalArgumentException("ruleDigest does not match its canonical format");
        }
        Objects.requireNonNull(sourceDigest, "sourceDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", sourceDigest)) {
            throw new IllegalArgumentException("sourceDigest does not match its canonical format");
        }
        if (workerCount < 0L) {
            throw new IllegalArgumentException("workerCount is below its canonical minimum");
        }
        if (workerCount > 1000000L) {
            throw new IllegalArgumentException("workerCount exceeds its canonical maximum");
        }
        if (lineCount != lines.size()) {
            throw new IllegalArgumentException("lineCount must equal lines.size");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon008ClosedTimeResultV1> {

        @Override
        public Xcon008ClosedTimeResultV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon008ClosedTimeResultV1.class,
                        "Xcon008ClosedTimeResultV1 must be encoded as a JSON object");
            }
            UUID closePeriodId = null; boolean closePeriodIdSeen = false;
            long closeRevision = 0L; boolean closeRevisionSeen = false;
            UUID closedTimeResultId = null; boolean closedTimeResultIdSeen = false;
            long ledgerRevisionFrom = 0L; boolean ledgerRevisionFromSeen = false;
            long ledgerRevisionTo = 0L; boolean ledgerRevisionToSeen = false;
            int lineCount = 0; boolean lineCountSeen = false;
            List<ClosedTimeLine> lines = null; boolean linesSeen = false;
            UUID payPeriodId = null; boolean payPeriodIdSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            UUID payrollEntityId = null; boolean payrollEntityIdSeen = false;
            String ruleDigest = null; boolean ruleDigestSeen = false;
            String sourceDigest = null; boolean sourceDigestSeen = false;
            UUID supersedesResultId = null; boolean supersedesResultIdSeen = false;
            int workerCount = 0; boolean workerCountSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon008ClosedTimeResultV1.class,
                            "Xcon008ClosedTimeResultV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon008ClosedTimeResultV1.class,
                            "Xcon008ClosedTimeResultV1 ends before a property value");
                }
                switch (propertyName) {
                case "closePeriodId" -> {
                    if (closePeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property closePeriodId");
                    }
                    closePeriodIdSeen = true;
                    closePeriodId = CanonicalHrisJson.readUuid(parser, context, "closePeriodId", false);
                }
                case "closeRevision" -> {
                    if (closeRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property closeRevision");
                    }
                    closeRevisionSeen = true;
                    closeRevision = CanonicalHrisJson.readLong(parser, context, "closeRevision", false);
                }
                case "closedTimeResultId" -> {
                    if (closedTimeResultIdSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property closedTimeResultId");
                    }
                    closedTimeResultIdSeen = true;
                    closedTimeResultId = CanonicalHrisJson.readUuid(parser, context, "closedTimeResultId", false);
                }
                case "ledgerRevisionFrom" -> {
                    if (ledgerRevisionFromSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property ledgerRevisionFrom");
                    }
                    ledgerRevisionFromSeen = true;
                    ledgerRevisionFrom = CanonicalHrisJson.readLong(parser, context, "ledgerRevisionFrom", false);
                }
                case "ledgerRevisionTo" -> {
                    if (ledgerRevisionToSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property ledgerRevisionTo");
                    }
                    ledgerRevisionToSeen = true;
                    ledgerRevisionTo = CanonicalHrisJson.readLong(parser, context, "ledgerRevisionTo", false);
                }
                case "lineCount" -> {
                    if (lineCountSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property lineCount");
                    }
                    lineCountSeen = true;
                    lineCount = CanonicalHrisJson.readInt(parser, context, "lineCount", false);
                }
                case "lines" -> {
                    if (linesSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property lines");
                    }
                    linesSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "lines must be encoded as a JSON array");
                    }
                    ArrayList<ClosedTimeLine> linesValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (linesValues.size() >= 1000000) {
                            return context.reportInputMismatch(
                                    Xcon008ClosedTimeResultV1.class,
                                    "lines exceeds its canonical item limit");
                        }
                        linesValues.add(CanonicalHrisJson.readObject(parser, context, "lines[]", ClosedTimeLine.class, false));
                    }
                    lines = List.copyOf(linesValues);
                }
                case "payPeriodId" -> {
                    if (payPeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property payPeriodId");
                    }
                    payPeriodIdSeen = true;
                    payPeriodId = CanonicalHrisJson.readUuid(parser, context, "payPeriodId", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "payrollEntityId" -> {
                    if (payrollEntityIdSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property payrollEntityId");
                    }
                    payrollEntityIdSeen = true;
                    payrollEntityId = CanonicalHrisJson.readUuid(parser, context, "payrollEntityId", false);
                }
                case "ruleDigest" -> {
                    if (ruleDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property ruleDigest");
                    }
                    ruleDigestSeen = true;
                    ruleDigest = CanonicalHrisJson.readString(parser, context, "ruleDigest", false);
                }
                case "sourceDigest" -> {
                    if (sourceDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property sourceDigest");
                    }
                    sourceDigestSeen = true;
                    sourceDigest = CanonicalHrisJson.readString(parser, context, "sourceDigest", false);
                }
                case "supersedesResultId" -> {
                    if (supersedesResultIdSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property supersedesResultId");
                    }
                    supersedesResultIdSeen = true;
                    supersedesResultId = CanonicalHrisJson.readUuid(parser, context, "supersedesResultId", true);
                }
                case "workerCount" -> {
                    if (workerCountSeen) {
                        return context.reportInputMismatch(
                                Xcon008ClosedTimeResultV1.class,
                                "duplicate property workerCount");
                    }
                    workerCountSeen = true;
                    workerCount = CanonicalHrisJson.readInt(parser, context, "workerCount", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon008ClosedTimeResultV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!closePeriodIdSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property closePeriodId");
            }
            if (!closeRevisionSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property closeRevision");
            }
            if (!closedTimeResultIdSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property closedTimeResultId");
            }
            if (!ledgerRevisionFromSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property ledgerRevisionFrom");
            }
            if (!ledgerRevisionToSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property ledgerRevisionTo");
            }
            if (!lineCountSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property lineCount");
            }
            if (!linesSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property lines");
            }
            if (!payPeriodIdSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property payPeriodId");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property payloadDigest");
            }
            if (!payrollEntityIdSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property payrollEntityId");
            }
            if (!ruleDigestSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property ruleDigest");
            }
            if (!sourceDigestSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property sourceDigest");
            }
            if (!supersedesResultIdSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property supersedesResultId");
            }
            if (!workerCountSeen) {
                return context.reportInputMismatch(Xcon008ClosedTimeResultV1.class,
                        "missing required property workerCount");
            }
            return new Xcon008ClosedTimeResultV1(
                    closePeriodId,
                    closeRevision,
                    closedTimeResultId,
                    ledgerRevisionFrom,
                    ledgerRevisionTo,
                    lineCount,
                    lines,
                    payPeriodId,
                    payloadDigest,
                    payrollEntityId,
                    ruleDigest,
                    sourceDigest,
                    supersedesResultId,
                    workerCount);
        }
    }

    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonDeserialize(using = ClosedTimeLine.Deserializer.class)
    public record ClosedTimeLine(
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentId,
            String payCode,
            @JsonSerialize(using = CanonicalDecimalJson.Serializer.class) @JsonDeserialize(using = CanonicalDecimalJson.QuantityDecimalDeserializer.class) BigDecimal quantity,
            String currency,
            int sourceEntryCount,
            String sourceEntryDigest,
            String unit) {

        public ClosedTimeLine {
            Objects.requireNonNull(workerId, "workerId must not be null");
            Objects.requireNonNull(assignmentId, "assignmentId must not be null");
            Objects.requireNonNull(payCode, "payCode must not be null");
            if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", payCode)) {
                throw new IllegalArgumentException("payCode does not match its canonical format");
            }
            Objects.requireNonNull(quantity, "quantity must not be null");
            quantity = CanonicalDecimalJson.normalize(quantity);
            if (!Pattern.matches("^-?(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?$", quantity.toPlainString())) {
                throw new IllegalArgumentException("quantity does not match its canonical decimal format");
            }
            if (currency != null) {
                if (!Pattern.matches("^[A-Z]{3}$", currency)) {
                    throw new IllegalArgumentException("currency does not match its canonical format");
                }
            }
            if (sourceEntryCount < 1L) {
                throw new IllegalArgumentException("sourceEntryCount is below its canonical minimum");
            }
            if (sourceEntryCount > 100000L) {
                throw new IllegalArgumentException("sourceEntryCount exceeds its canonical maximum");
            }
            Objects.requireNonNull(sourceEntryDigest, "sourceEntryDigest must not be null");
            if (!Pattern.matches("^[0-9a-f]{64}$", sourceEntryDigest)) {
                throw new IllegalArgumentException("sourceEntryDigest does not match its canonical format");
            }
            Objects.requireNonNull(unit, "unit must not be null");
            if (!Set.of("MINUTE", "HOUR", "DAY", "COUNT", "AMOUNT").contains(unit)) {
                throw new IllegalArgumentException("unit is not a canonical value");
            }
            if ("AMOUNT".equals(unit)) {
                Objects.requireNonNull(quantity, "quantity must not be null");
                quantity = CanonicalDecimalJson.normalize(quantity);
                if (!Pattern.matches("^-?(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?$", quantity.toPlainString())) {
                    throw new IllegalArgumentException("quantity does not match its canonical decimal format");
                }
                Objects.requireNonNull(currency, "currency must not be null");
                if (!Pattern.matches("^[A-Z]{3}$", currency)) {
                    throw new IllegalArgumentException("currency does not match its canonical format");
                }
            } else {
                Objects.requireNonNull(quantity, "quantity must not be null");
                quantity = CanonicalDecimalJson.normalize(quantity);
                if (!Pattern.matches("^-?(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?$", quantity.toPlainString())) {
                    throw new IllegalArgumentException("quantity does not match its canonical decimal format");
                }
                if (currency != null) {
                    throw new IllegalArgumentException("currency must be null unless unit is AMOUNT");
                }
            }
            if ("AMOUNT".equals(unit)) {
                try {
                    Currency.getInstance(currency);
                } catch (IllegalArgumentException exception) {
                    throw new IllegalArgumentException("currency must be a recognized ISO 4217 code", exception);
                }
            }
        }

        public static final class Deserializer
                extends JsonDeserializer<ClosedTimeLine> {

            @Override
            public ClosedTimeLine deserialize(
                    JsonParser parser,
                    DeserializationContext context) throws IOException {
                if (!parser.isExpectedStartObjectToken()) {
                    return context.reportInputMismatch(
                            ClosedTimeLine.class,
                            "ClosedTimeLine must be encoded as a JSON object");
                }
                UUID workerId = null; boolean workerIdSeen = false;
                UUID assignmentId = null; boolean assignmentIdSeen = false;
                String payCode = null; boolean payCodeSeen = false;
                BigDecimal quantity = null; boolean quantitySeen = false;
                String currency = null; boolean currencySeen = false;
                int sourceEntryCount = 0; boolean sourceEntryCountSeen = false;
                String sourceEntryDigest = null; boolean sourceEntryDigestSeen = false;
                String unit = null; boolean unitSeen = false;
                while (parser.nextToken() != JsonToken.END_OBJECT) {
                    if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                        return context.reportInputMismatch(
                                ClosedTimeLine.class,
                                "ClosedTimeLine contains a non-field token");
                    }
                    String propertyName = parser.currentName();
                    if (parser.nextToken() == null) {
                        return context.reportInputMismatch(
                                ClosedTimeLine.class,
                                "ClosedTimeLine ends before a property value");
                    }
                    switch (propertyName) {
                    case "workerId" -> {
                        if (workerIdSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property workerId");
                        }
                        workerIdSeen = true;
                        workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                    }
                    case "assignmentId" -> {
                        if (assignmentIdSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property assignmentId");
                        }
                        assignmentIdSeen = true;
                        assignmentId = CanonicalHrisJson.readUuid(parser, context, "assignmentId", false);
                    }
                    case "payCode" -> {
                        if (payCodeSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property payCode");
                        }
                        payCodeSeen = true;
                        payCode = CanonicalHrisJson.readString(parser, context, "payCode", false);
                    }
                    case "quantity" -> {
                        if (quantitySeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property quantity");
                        }
                        quantitySeen = true;
                        quantity = new CanonicalDecimalJson.QuantityDecimalDeserializer().deserialize(parser, context);
                    }
                    case "currency" -> {
                        if (currencySeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property currency");
                        }
                        currencySeen = true;
                        currency = CanonicalHrisJson.readString(parser, context, "currency", true);
                    }
                    case "sourceEntryCount" -> {
                        if (sourceEntryCountSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property sourceEntryCount");
                        }
                        sourceEntryCountSeen = true;
                        sourceEntryCount = CanonicalHrisJson.readInt(parser, context, "sourceEntryCount", false);
                    }
                    case "sourceEntryDigest" -> {
                        if (sourceEntryDigestSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property sourceEntryDigest");
                        }
                        sourceEntryDigestSeen = true;
                        sourceEntryDigest = CanonicalHrisJson.readString(parser, context, "sourceEntryDigest", false);
                    }
                    case "unit" -> {
                        if (unitSeen) {
                            return context.reportInputMismatch(
                                    ClosedTimeLine.class,
                                    "duplicate property unit");
                        }
                        unitSeen = true;
                        unit = CanonicalHrisJson.readString(parser, context, "unit", false);
                    }
                    default -> {
                        return context.reportInputMismatch(
                                ClosedTimeLine.class,
                                "unknown property %s", propertyName);
                    }
                    }
                }
                if (!workerIdSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property workerId");
                }
                if (!assignmentIdSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property assignmentId");
                }
                if (!payCodeSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property payCode");
                }
                if (!quantitySeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property quantity");
                }
                if (!currencySeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property currency");
                }
                if (!sourceEntryCountSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property sourceEntryCount");
                }
                if (!sourceEntryDigestSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property sourceEntryDigest");
                }
                if (!unitSeen) {
                    return context.reportInputMismatch(ClosedTimeLine.class,
                            "missing required property unit");
                }
                return new ClosedTimeLine(
                        workerId,
                        assignmentId,
                        payCode,
                        quantity,
                        currency,
                        sourceEntryCount,
                        sourceEntryDigest,
                        unit);
            }
        }
    }
}
