/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_002
 * Normalized schema SHA-256: 00f999cf182c5611afc56290b84a8ada5740222183f3cb1e9022b6f77909837a
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalDecimalJson;
import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon002CompensationBasisSnapshotV1.Deserializer.class)
public record Xcon002CompensationBasisSnapshotV1(
        @JsonSerialize(using = CanonicalDecimalJson.Serializer.class) @JsonDeserialize(using = CanonicalDecimalJson.InputAmountDeserializer.class) BigDecimal amount,
        @JsonSerialize(using = CanonicalHrisJson.InstantSerializer.class) Instant asOf,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentPublicId,
        String basisType,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID compensationBasisPublicId,
        String currency,
        String frequency,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID legalEntityPublicId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payGroupPublicId,
        String payloadDigest,
        long snapshotVersion,
        long sourceRevision,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate validFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate validTo,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerPublicId) {

    public Xcon002CompensationBasisSnapshotV1 {
        Objects.requireNonNull(amount, "amount must not be null");
        amount = CanonicalDecimalJson.normalize(amount);
        if (!Pattern.matches("^-?(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?$", amount.toPlainString())) {
            throw new IllegalArgumentException("amount does not match its canonical decimal format");
        }
        Objects.requireNonNull(asOf, "asOf must not be null");
        Objects.requireNonNull(assignmentPublicId, "assignmentPublicId must not be null");
        Objects.requireNonNull(basisType, "basisType must not be null");
        if (!Set.of("SALARY", "HOURLY", "DAILY", "PIECE", "OTHER").contains(basisType)) {
            throw new IllegalArgumentException("basisType is not a canonical value");
        }
        Objects.requireNonNull(compensationBasisPublicId, "compensationBasisPublicId must not be null");
        Objects.requireNonNull(currency, "currency must not be null");
        if (!Pattern.matches("^[A-Z]{3}$", currency)) {
            throw new IllegalArgumentException("currency does not match its canonical format");
        }
        Objects.requireNonNull(frequency, "frequency must not be null");
        if (!Set.of("HOURLY", "DAILY", "WEEKLY", "BIWEEKLY", "SEMIMONTHLY", "MONTHLY", "ANNUAL").contains(frequency)) {
            throw new IllegalArgumentException("frequency is not a canonical value");
        }
        Objects.requireNonNull(legalEntityPublicId, "legalEntityPublicId must not be null");
        Objects.requireNonNull(payGroupPublicId, "payGroupPublicId must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        if (snapshotVersion < 1L) {
            throw new IllegalArgumentException("snapshotVersion is below its canonical minimum");
        }
        if (sourceRevision < 1L) {
            throw new IllegalArgumentException("sourceRevision is below its canonical minimum");
        }
        Objects.requireNonNull(validFrom, "validFrom must not be null");
        Objects.requireNonNull(workerPublicId, "workerPublicId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon002CompensationBasisSnapshotV1> {

        @Override
        public Xcon002CompensationBasisSnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon002CompensationBasisSnapshotV1.class,
                        "Xcon002CompensationBasisSnapshotV1 must be encoded as a JSON object");
            }
            BigDecimal amount = null; boolean amountSeen = false;
            Instant asOf = null; boolean asOfSeen = false;
            UUID assignmentPublicId = null; boolean assignmentPublicIdSeen = false;
            String basisType = null; boolean basisTypeSeen = false;
            UUID compensationBasisPublicId = null; boolean compensationBasisPublicIdSeen = false;
            String currency = null; boolean currencySeen = false;
            String frequency = null; boolean frequencySeen = false;
            UUID legalEntityPublicId = null; boolean legalEntityPublicIdSeen = false;
            UUID payGroupPublicId = null; boolean payGroupPublicIdSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            long snapshotVersion = 0L; boolean snapshotVersionSeen = false;
            long sourceRevision = 0L; boolean sourceRevisionSeen = false;
            LocalDate validFrom = null; boolean validFromSeen = false;
            LocalDate validTo = null; boolean validToSeen = false;
            UUID workerPublicId = null; boolean workerPublicIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon002CompensationBasisSnapshotV1.class,
                            "Xcon002CompensationBasisSnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon002CompensationBasisSnapshotV1.class,
                            "Xcon002CompensationBasisSnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "amount" -> {
                    if (amountSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property amount");
                    }
                    amountSeen = true;
                    amount = new CanonicalDecimalJson.InputAmountDeserializer().deserialize(parser, context);
                }
                case "asOf" -> {
                    if (asOfSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property asOf");
                    }
                    asOfSeen = true;
                    asOf = CanonicalHrisJson.readInstant(parser, context, "asOf", false);
                }
                case "assignmentPublicId" -> {
                    if (assignmentPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property assignmentPublicId");
                    }
                    assignmentPublicIdSeen = true;
                    assignmentPublicId = CanonicalHrisJson.readUuid(parser, context, "assignmentPublicId", false);
                }
                case "basisType" -> {
                    if (basisTypeSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property basisType");
                    }
                    basisTypeSeen = true;
                    basisType = CanonicalHrisJson.readString(parser, context, "basisType", false);
                }
                case "compensationBasisPublicId" -> {
                    if (compensationBasisPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property compensationBasisPublicId");
                    }
                    compensationBasisPublicIdSeen = true;
                    compensationBasisPublicId = CanonicalHrisJson.readUuid(parser, context, "compensationBasisPublicId", false);
                }
                case "currency" -> {
                    if (currencySeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property currency");
                    }
                    currencySeen = true;
                    currency = CanonicalHrisJson.readString(parser, context, "currency", false);
                }
                case "frequency" -> {
                    if (frequencySeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property frequency");
                    }
                    frequencySeen = true;
                    frequency = CanonicalHrisJson.readString(parser, context, "frequency", false);
                }
                case "legalEntityPublicId" -> {
                    if (legalEntityPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property legalEntityPublicId");
                    }
                    legalEntityPublicIdSeen = true;
                    legalEntityPublicId = CanonicalHrisJson.readUuid(parser, context, "legalEntityPublicId", false);
                }
                case "payGroupPublicId" -> {
                    if (payGroupPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property payGroupPublicId");
                    }
                    payGroupPublicIdSeen = true;
                    payGroupPublicId = CanonicalHrisJson.readUuid(parser, context, "payGroupPublicId", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "snapshotVersion" -> {
                    if (snapshotVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property snapshotVersion");
                    }
                    snapshotVersionSeen = true;
                    snapshotVersion = CanonicalHrisJson.readLong(parser, context, "snapshotVersion", false);
                }
                case "sourceRevision" -> {
                    if (sourceRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property sourceRevision");
                    }
                    sourceRevisionSeen = true;
                    sourceRevision = CanonicalHrisJson.readLong(parser, context, "sourceRevision", false);
                }
                case "validFrom" -> {
                    if (validFromSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property validFrom");
                    }
                    validFromSeen = true;
                    validFrom = CanonicalHrisJson.readDate(parser, context, "validFrom", false);
                }
                case "validTo" -> {
                    if (validToSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property validTo");
                    }
                    validToSeen = true;
                    validTo = CanonicalHrisJson.readDate(parser, context, "validTo", true);
                }
                case "workerPublicId" -> {
                    if (workerPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon002CompensationBasisSnapshotV1.class,
                                "duplicate property workerPublicId");
                    }
                    workerPublicIdSeen = true;
                    workerPublicId = CanonicalHrisJson.readUuid(parser, context, "workerPublicId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon002CompensationBasisSnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!amountSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property amount");
            }
            if (!asOfSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property asOf");
            }
            if (!assignmentPublicIdSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property assignmentPublicId");
            }
            if (!basisTypeSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property basisType");
            }
            if (!compensationBasisPublicIdSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property compensationBasisPublicId");
            }
            if (!currencySeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property currency");
            }
            if (!frequencySeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property frequency");
            }
            if (!legalEntityPublicIdSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property legalEntityPublicId");
            }
            if (!payGroupPublicIdSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property payGroupPublicId");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!snapshotVersionSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property snapshotVersion");
            }
            if (!sourceRevisionSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property sourceRevision");
            }
            if (!validFromSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property validFrom");
            }
            if (!validToSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property validTo");
            }
            if (!workerPublicIdSeen) {
                return context.reportInputMismatch(Xcon002CompensationBasisSnapshotV1.class,
                        "missing required property workerPublicId");
            }
            return new Xcon002CompensationBasisSnapshotV1(
                    amount,
                    asOf,
                    assignmentPublicId,
                    basisType,
                    compensationBasisPublicId,
                    currency,
                    frequency,
                    legalEntityPublicId,
                    payGroupPublicId,
                    payloadDigest,
                    snapshotVersion,
                    sourceRevision,
                    validFrom,
                    validTo,
                    workerPublicId);
        }
    }
}
