/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_020
 * Normalized schema SHA-256: d7b73b84c93e60fa8ff114f16625eab31bd2aa9095423120585039066e02ca20
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalDecimalJson;
import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon020ApprovedCompensationPlanSnapshotV1.Deserializer.class)
public record Xcon020ApprovedCompensationPlanSnapshotV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID approvalReceiptId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID cycleId,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
        int lineCount,
        List<ApprovedCompensationPlanLine> lines,
        String payloadDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID planId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion) {

    public Xcon020ApprovedCompensationPlanSnapshotV1 {
        Objects.requireNonNull(approvalReceiptId, "approvalReceiptId must not be null");
        Objects.requireNonNull(cycleId, "cycleId must not be null");
        Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        if (lineCount < 1L) {
            throw new IllegalArgumentException("lineCount is below its canonical minimum");
        }
        if (lineCount > 100000L) {
            throw new IllegalArgumentException("lineCount exceeds its canonical maximum");
        }
        Objects.requireNonNull(lines, "lines must not be null");
        lines = List.copyOf(lines);
        if (lines.size() < 1) {
            throw new IllegalArgumentException("lines has too few items");
        }
        if (lines.size() > 100000) {
            throw new IllegalArgumentException("lines has too many items");
        }
        for (ApprovedCompensationPlanLine linesItem : lines) {
            Objects.requireNonNull(linesItem, "linesItem must not be null");
        }
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(planId, "planId must not be null");
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        if (lineCount != lines.size()) {
            throw new IllegalArgumentException("lineCount must equal lines.size");
        }
        for (int index = 0; index < lines.size(); index++) {
            if (lines.get(index).lineSequence() != index + 1) {
                throw new IllegalArgumentException("lineSequence must be contiguous from 1 in list order");
            }
        }
        if (lines.stream().map(ApprovedCompensationPlanLine::lineId).distinct().count() != lines.size()) {
            throw new IllegalArgumentException("lineId must be unique within the snapshot");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon020ApprovedCompensationPlanSnapshotV1> {

        @Override
        public Xcon020ApprovedCompensationPlanSnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "Xcon020ApprovedCompensationPlanSnapshotV1 must be encoded as a JSON object");
            }
            UUID approvalReceiptId = null; boolean approvalReceiptIdSeen = false;
            UUID cycleId = null; boolean cycleIdSeen = false;
            LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
            LocalDate effectiveTo = null; boolean effectiveToSeen = false;
            int lineCount = 0; boolean lineCountSeen = false;
            List<ApprovedCompensationPlanLine> lines = null; boolean linesSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            UUID planId = null; boolean planIdSeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon020ApprovedCompensationPlanSnapshotV1.class,
                            "Xcon020ApprovedCompensationPlanSnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon020ApprovedCompensationPlanSnapshotV1.class,
                            "Xcon020ApprovedCompensationPlanSnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "approvalReceiptId" -> {
                    if (approvalReceiptIdSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property approvalReceiptId");
                    }
                    approvalReceiptIdSeen = true;
                    approvalReceiptId = CanonicalHrisJson.readUuid(parser, context, "approvalReceiptId", false);
                }
                case "cycleId" -> {
                    if (cycleIdSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property cycleId");
                    }
                    cycleIdSeen = true;
                    cycleId = CanonicalHrisJson.readUuid(parser, context, "cycleId", false);
                }
                case "effectiveFrom" -> {
                    if (effectiveFromSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property effectiveFrom");
                    }
                    effectiveFromSeen = true;
                    effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                }
                case "effectiveTo" -> {
                    if (effectiveToSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property effectiveTo");
                    }
                    effectiveToSeen = true;
                    effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                }
                case "lineCount" -> {
                    if (lineCountSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property lineCount");
                    }
                    lineCountSeen = true;
                    lineCount = CanonicalHrisJson.readInt(parser, context, "lineCount", false);
                }
                case "lines" -> {
                    if (linesSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property lines");
                    }
                    linesSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "lines must be encoded as a JSON array");
                    }
                    ArrayList<ApprovedCompensationPlanLine> linesValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (linesValues.size() >= 100000) {
                            return context.reportInputMismatch(
                                    Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                    "lines exceeds its canonical item limit");
                        }
                        linesValues.add(CanonicalHrisJson.readObject(parser, context, "lines[]", ApprovedCompensationPlanLine.class, false));
                    }
                    lines = List.copyOf(linesValues);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "planId" -> {
                    if (planIdSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property planId");
                    }
                    planIdSeen = true;
                    planId = CanonicalHrisJson.readUuid(parser, context, "planId", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon020ApprovedCompensationPlanSnapshotV1.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon020ApprovedCompensationPlanSnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!approvalReceiptIdSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property approvalReceiptId");
            }
            if (!cycleIdSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property cycleId");
            }
            if (!effectiveFromSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property effectiveFrom");
            }
            if (!effectiveToSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property effectiveTo");
            }
            if (!lineCountSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property lineCount");
            }
            if (!linesSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property lines");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!planIdSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property planId");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon020ApprovedCompensationPlanSnapshotV1.class,
                        "missing required property sourceVersion");
            }
            return new Xcon020ApprovedCompensationPlanSnapshotV1(
                    approvalReceiptId,
                    cycleId,
                    effectiveFrom,
                    effectiveTo,
                    lineCount,
                    lines,
                    payloadDigest,
                    planId,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion);
        }
    }

    @JsonInclude(JsonInclude.Include.ALWAYS)
    @JsonDeserialize(using = ApprovedCompensationPlanLine.Deserializer.class)
    public record ApprovedCompensationPlanLine(
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID lineId,
            int lineSequence,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId,
            @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentId,
            String componentCode,
            String currency,
            @JsonSerialize(using = CanonicalDecimalJson.Serializer.class) @JsonDeserialize(using = CanonicalDecimalJson.PostedMoneyDeserializer.class) BigDecimal approvedAmount,
            @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
            @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
            String lineDigest) {

        public ApprovedCompensationPlanLine {
            Objects.requireNonNull(lineId, "lineId must not be null");
            if (lineSequence < 1L) {
                throw new IllegalArgumentException("lineSequence is below its canonical minimum");
            }
            if (lineSequence > 100000L) {
                throw new IllegalArgumentException("lineSequence exceeds its canonical maximum");
            }
            Objects.requireNonNull(workerId, "workerId must not be null");
            Objects.requireNonNull(assignmentId, "assignmentId must not be null");
            Objects.requireNonNull(componentCode, "componentCode must not be null");
            if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", componentCode)) {
                throw new IllegalArgumentException("componentCode does not match its canonical format");
            }
            Objects.requireNonNull(currency, "currency must not be null");
            if (!Pattern.matches("^[A-Z]{3}$", currency)) {
                throw new IllegalArgumentException("currency does not match its canonical format");
            }
            Objects.requireNonNull(approvedAmount, "approvedAmount must not be null");
            approvedAmount = CanonicalDecimalJson.normalize(approvedAmount);
            if (!Pattern.matches("^-?(?:0|[1-9][0-9]{0,14})(?:\\.[0-9]{1,4})?$", approvedAmount.toPlainString())) {
                throw new IllegalArgumentException("approvedAmount does not match its canonical decimal format");
            }
            Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
            Objects.requireNonNull(lineDigest, "lineDigest must not be null");
            if (!Pattern.matches("^[0-9a-f]{64}$", lineDigest)) {
                throw new IllegalArgumentException("lineDigest does not match its canonical format");
            }
        }

        public static final class Deserializer
                extends JsonDeserializer<ApprovedCompensationPlanLine> {

            @Override
            public ApprovedCompensationPlanLine deserialize(
                    JsonParser parser,
                    DeserializationContext context) throws IOException {
                if (!parser.isExpectedStartObjectToken()) {
                    return context.reportInputMismatch(
                            ApprovedCompensationPlanLine.class,
                            "ApprovedCompensationPlanLine must be encoded as a JSON object");
                }
                UUID lineId = null; boolean lineIdSeen = false;
                int lineSequence = 0; boolean lineSequenceSeen = false;
                UUID workerId = null; boolean workerIdSeen = false;
                UUID assignmentId = null; boolean assignmentIdSeen = false;
                String componentCode = null; boolean componentCodeSeen = false;
                String currency = null; boolean currencySeen = false;
                BigDecimal approvedAmount = null; boolean approvedAmountSeen = false;
                LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
                LocalDate effectiveTo = null; boolean effectiveToSeen = false;
                String lineDigest = null; boolean lineDigestSeen = false;
                while (parser.nextToken() != JsonToken.END_OBJECT) {
                    if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                        return context.reportInputMismatch(
                                ApprovedCompensationPlanLine.class,
                                "ApprovedCompensationPlanLine contains a non-field token");
                    }
                    String propertyName = parser.currentName();
                    if (parser.nextToken() == null) {
                        return context.reportInputMismatch(
                                ApprovedCompensationPlanLine.class,
                                "ApprovedCompensationPlanLine ends before a property value");
                    }
                    switch (propertyName) {
                    case "lineId" -> {
                        if (lineIdSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property lineId");
                        }
                        lineIdSeen = true;
                        lineId = CanonicalHrisJson.readUuid(parser, context, "lineId", false);
                    }
                    case "lineSequence" -> {
                        if (lineSequenceSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property lineSequence");
                        }
                        lineSequenceSeen = true;
                        lineSequence = CanonicalHrisJson.readInt(parser, context, "lineSequence", false);
                    }
                    case "workerId" -> {
                        if (workerIdSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property workerId");
                        }
                        workerIdSeen = true;
                        workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                    }
                    case "assignmentId" -> {
                        if (assignmentIdSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property assignmentId");
                        }
                        assignmentIdSeen = true;
                        assignmentId = CanonicalHrisJson.readUuid(parser, context, "assignmentId", false);
                    }
                    case "componentCode" -> {
                        if (componentCodeSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property componentCode");
                        }
                        componentCodeSeen = true;
                        componentCode = CanonicalHrisJson.readString(parser, context, "componentCode", false);
                    }
                    case "currency" -> {
                        if (currencySeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property currency");
                        }
                        currencySeen = true;
                        currency = CanonicalHrisJson.readString(parser, context, "currency", false);
                    }
                    case "approvedAmount" -> {
                        if (approvedAmountSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property approvedAmount");
                        }
                        approvedAmountSeen = true;
                        approvedAmount = new CanonicalDecimalJson.PostedMoneyDeserializer().deserialize(parser, context);
                    }
                    case "effectiveFrom" -> {
                        if (effectiveFromSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property effectiveFrom");
                        }
                        effectiveFromSeen = true;
                        effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                    }
                    case "effectiveTo" -> {
                        if (effectiveToSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property effectiveTo");
                        }
                        effectiveToSeen = true;
                        effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                    }
                    case "lineDigest" -> {
                        if (lineDigestSeen) {
                            return context.reportInputMismatch(
                                    ApprovedCompensationPlanLine.class,
                                    "duplicate property lineDigest");
                        }
                        lineDigestSeen = true;
                        lineDigest = CanonicalHrisJson.readString(parser, context, "lineDigest", false);
                    }
                    default -> {
                        return context.reportInputMismatch(
                                ApprovedCompensationPlanLine.class,
                                "unknown property %s", propertyName);
                    }
                    }
                }
                if (!lineIdSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property lineId");
                }
                if (!lineSequenceSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property lineSequence");
                }
                if (!workerIdSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property workerId");
                }
                if (!assignmentIdSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property assignmentId");
                }
                if (!componentCodeSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property componentCode");
                }
                if (!currencySeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property currency");
                }
                if (!approvedAmountSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property approvedAmount");
                }
                if (!effectiveFromSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property effectiveFrom");
                }
                if (!effectiveToSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property effectiveTo");
                }
                if (!lineDigestSeen) {
                    return context.reportInputMismatch(ApprovedCompensationPlanLine.class,
                            "missing required property lineDigest");
                }
                return new ApprovedCompensationPlanLine(
                        lineId,
                        lineSequence,
                        workerId,
                        assignmentId,
                        componentCode,
                        currency,
                        approvedAmount,
                        effectiveFrom,
                        effectiveTo,
                        lineDigest);
            }
        }
    }
}
