/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_003
 * Normalized schema SHA-256: ff76eab3a75464f3f7263ac3387b25015971f9e6117ee2f5359c8c86c8c810ca
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon003WorkerChangedV1.Deserializer.class)
public record Xcon003WorkerChangedV1(
        String changeType,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveDate,
        long newAggregateVersion,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerPublicId) {

    public Xcon003WorkerChangedV1 {
        Objects.requireNonNull(changeType, "changeType must not be null");
        if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", changeType)) {
            throw new IllegalArgumentException("changeType does not match its canonical format");
        }
        Objects.requireNonNull(effectiveDate, "effectiveDate must not be null");
        if (newAggregateVersion < 1L) {
            throw new IllegalArgumentException("newAggregateVersion is below its canonical minimum");
        }
        Objects.requireNonNull(workerPublicId, "workerPublicId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon003WorkerChangedV1> {

        @Override
        public Xcon003WorkerChangedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon003WorkerChangedV1.class,
                        "Xcon003WorkerChangedV1 must be encoded as a JSON object");
            }
            String changeType = null; boolean changeTypeSeen = false;
            LocalDate effectiveDate = null; boolean effectiveDateSeen = false;
            long newAggregateVersion = 0L; boolean newAggregateVersionSeen = false;
            UUID workerPublicId = null; boolean workerPublicIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon003WorkerChangedV1.class,
                            "Xcon003WorkerChangedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon003WorkerChangedV1.class,
                            "Xcon003WorkerChangedV1 ends before a property value");
                }
                switch (propertyName) {
                case "changeType" -> {
                    if (changeTypeSeen) {
                        return context.reportInputMismatch(
                                Xcon003WorkerChangedV1.class,
                                "duplicate property changeType");
                    }
                    changeTypeSeen = true;
                    changeType = CanonicalHrisJson.readString(parser, context, "changeType", false);
                }
                case "effectiveDate" -> {
                    if (effectiveDateSeen) {
                        return context.reportInputMismatch(
                                Xcon003WorkerChangedV1.class,
                                "duplicate property effectiveDate");
                    }
                    effectiveDateSeen = true;
                    effectiveDate = CanonicalHrisJson.readDate(parser, context, "effectiveDate", false);
                }
                case "newAggregateVersion" -> {
                    if (newAggregateVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon003WorkerChangedV1.class,
                                "duplicate property newAggregateVersion");
                    }
                    newAggregateVersionSeen = true;
                    newAggregateVersion = CanonicalHrisJson.readLong(parser, context, "newAggregateVersion", false);
                }
                case "workerPublicId" -> {
                    if (workerPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon003WorkerChangedV1.class,
                                "duplicate property workerPublicId");
                    }
                    workerPublicIdSeen = true;
                    workerPublicId = CanonicalHrisJson.readUuid(parser, context, "workerPublicId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon003WorkerChangedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!changeTypeSeen) {
                return context.reportInputMismatch(Xcon003WorkerChangedV1.class,
                        "missing required property changeType");
            }
            if (!effectiveDateSeen) {
                return context.reportInputMismatch(Xcon003WorkerChangedV1.class,
                        "missing required property effectiveDate");
            }
            if (!newAggregateVersionSeen) {
                return context.reportInputMismatch(Xcon003WorkerChangedV1.class,
                        "missing required property newAggregateVersion");
            }
            if (!workerPublicIdSeen) {
                return context.reportInputMismatch(Xcon003WorkerChangedV1.class,
                        "missing required property workerPublicId");
            }
            return new Xcon003WorkerChangedV1(
                    changeType,
                    effectiveDate,
                    newAggregateVersion,
                    workerPublicId);
        }
    }
}
