/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_005
 * Normalized schema SHA-256: 3e32aa3bdd673d523468e1b6975a1af73bc3fafa98d9ce8f57dd9dfcf921bef4
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon005AssignmentChangedV1.Deserializer.class)
public record Xcon005AssignmentChangedV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentPublicId,
        List<String> changedReferences,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveDate,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID eventPublicId,
        String eventType,
        long newAggregateVersion) {

    public Xcon005AssignmentChangedV1 {
        Objects.requireNonNull(assignmentPublicId, "assignmentPublicId must not be null");
        Objects.requireNonNull(changedReferences, "changedReferences must not be null");
        changedReferences = List.copyOf(changedReferences);
        if (changedReferences.size() < 1) {
            throw new IllegalArgumentException("changedReferences has too few items");
        }
        if (changedReferences.size() > 32) {
            throw new IllegalArgumentException("changedReferences has too many items");
        }
        if (new HashSet<>(changedReferences).size() != changedReferences.size()) {
            throw new IllegalArgumentException("changedReferences must contain unique items");
        }
        for (String changedReferencesItem : changedReferences) {
            Objects.requireNonNull(changedReferencesItem, "changedReferencesItem must not be null");
            if (!Pattern.matches("^[A-Z0-9][A-Z0-9._-]{0,79}$", changedReferencesItem)) {
                throw new IllegalArgumentException("changedReferencesItem does not match its canonical format");
            }
        }
        Objects.requireNonNull(effectiveDate, "effectiveDate must not be null");
        Objects.requireNonNull(eventPublicId, "eventPublicId must not be null");
        Objects.requireNonNull(eventType, "eventType must not be null");
        if (!Set.of("HIRE", "REHIRE", "TRANSFER", "PROMOTION", "DEMOTION", "CONCURRENT_ASSIGNMENT", "CHANGE_MANAGER", "CHANGE_LOCATION", "LEAVE", "RETURN", "TERMINATION", "CORRECTION").contains(eventType)) {
            throw new IllegalArgumentException("eventType is not a canonical value");
        }
        if (newAggregateVersion < 1L) {
            throw new IllegalArgumentException("newAggregateVersion is below its canonical minimum");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon005AssignmentChangedV1> {

        @Override
        public Xcon005AssignmentChangedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon005AssignmentChangedV1.class,
                        "Xcon005AssignmentChangedV1 must be encoded as a JSON object");
            }
            UUID assignmentPublicId = null; boolean assignmentPublicIdSeen = false;
            List<String> changedReferences = null; boolean changedReferencesSeen = false;
            LocalDate effectiveDate = null; boolean effectiveDateSeen = false;
            UUID eventPublicId = null; boolean eventPublicIdSeen = false;
            String eventType = null; boolean eventTypeSeen = false;
            long newAggregateVersion = 0L; boolean newAggregateVersionSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon005AssignmentChangedV1.class,
                            "Xcon005AssignmentChangedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon005AssignmentChangedV1.class,
                            "Xcon005AssignmentChangedV1 ends before a property value");
                }
                switch (propertyName) {
                case "assignmentPublicId" -> {
                    if (assignmentPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property assignmentPublicId");
                    }
                    assignmentPublicIdSeen = true;
                    assignmentPublicId = CanonicalHrisJson.readUuid(parser, context, "assignmentPublicId", false);
                }
                case "changedReferences" -> {
                    if (changedReferencesSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property changedReferences");
                    }
                    changedReferencesSeen = true;
                    if (!parser.hasToken(JsonToken.START_ARRAY)) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "changedReferences must be encoded as a JSON array");
                    }
                    ArrayList<String> changedReferencesValues = new ArrayList<>();
                    while (parser.nextToken() != JsonToken.END_ARRAY) {
                        if (changedReferencesValues.size() >= 32) {
                            return context.reportInputMismatch(
                                    Xcon005AssignmentChangedV1.class,
                                    "changedReferences exceeds its canonical item limit");
                        }
                        changedReferencesValues.add(CanonicalHrisJson.readString(parser, context, "changedReferences[]", false));
                    }
                    changedReferences = List.copyOf(changedReferencesValues);
                }
                case "effectiveDate" -> {
                    if (effectiveDateSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property effectiveDate");
                    }
                    effectiveDateSeen = true;
                    effectiveDate = CanonicalHrisJson.readDate(parser, context, "effectiveDate", false);
                }
                case "eventPublicId" -> {
                    if (eventPublicIdSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property eventPublicId");
                    }
                    eventPublicIdSeen = true;
                    eventPublicId = CanonicalHrisJson.readUuid(parser, context, "eventPublicId", false);
                }
                case "eventType" -> {
                    if (eventTypeSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property eventType");
                    }
                    eventTypeSeen = true;
                    eventType = CanonicalHrisJson.readString(parser, context, "eventType", false);
                }
                case "newAggregateVersion" -> {
                    if (newAggregateVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon005AssignmentChangedV1.class,
                                "duplicate property newAggregateVersion");
                    }
                    newAggregateVersionSeen = true;
                    newAggregateVersion = CanonicalHrisJson.readLong(parser, context, "newAggregateVersion", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon005AssignmentChangedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!assignmentPublicIdSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property assignmentPublicId");
            }
            if (!changedReferencesSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property changedReferences");
            }
            if (!effectiveDateSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property effectiveDate");
            }
            if (!eventPublicIdSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property eventPublicId");
            }
            if (!eventTypeSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property eventType");
            }
            if (!newAggregateVersionSeen) {
                return context.reportInputMismatch(Xcon005AssignmentChangedV1.class,
                        "missing required property newAggregateVersion");
            }
            return new Xcon005AssignmentChangedV1(
                    assignmentPublicId,
                    changedReferences,
                    effectiveDate,
                    eventPublicId,
                    eventType,
                    newAggregateVersion);
        }
    }
}
