/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_009
 * Normalized schema SHA-256: 76e4414b72687a61e9168f79427a575ec2ec13af2f6cdc8c197e30698a249e80
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon009TimePeriodClosedV1.Deserializer.class)
public record Xcon009TimePeriodClosedV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closePeriodId,
        long closeRevision,
        long ledgerRevision,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate periodEnd,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate periodStart,
        String ruleDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID scopeId,
        String sourceDigest) {

    public Xcon009TimePeriodClosedV1 {
        Objects.requireNonNull(closePeriodId, "closePeriodId must not be null");
        if (closeRevision < 1L) {
            throw new IllegalArgumentException("closeRevision is below its canonical minimum");
        }
        if (ledgerRevision < 1L) {
            throw new IllegalArgumentException("ledgerRevision is below its canonical minimum");
        }
        Objects.requireNonNull(periodEnd, "periodEnd must not be null");
        Objects.requireNonNull(periodStart, "periodStart must not be null");
        Objects.requireNonNull(ruleDigest, "ruleDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", ruleDigest)) {
            throw new IllegalArgumentException("ruleDigest does not match its canonical format");
        }
        Objects.requireNonNull(scopeId, "scopeId must not be null");
        Objects.requireNonNull(sourceDigest, "sourceDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", sourceDigest)) {
            throw new IllegalArgumentException("sourceDigest does not match its canonical format");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon009TimePeriodClosedV1> {

        @Override
        public Xcon009TimePeriodClosedV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon009TimePeriodClosedV1.class,
                        "Xcon009TimePeriodClosedV1 must be encoded as a JSON object");
            }
            UUID closePeriodId = null; boolean closePeriodIdSeen = false;
            long closeRevision = 0L; boolean closeRevisionSeen = false;
            long ledgerRevision = 0L; boolean ledgerRevisionSeen = false;
            LocalDate periodEnd = null; boolean periodEndSeen = false;
            LocalDate periodStart = null; boolean periodStartSeen = false;
            String ruleDigest = null; boolean ruleDigestSeen = false;
            UUID scopeId = null; boolean scopeIdSeen = false;
            String sourceDigest = null; boolean sourceDigestSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon009TimePeriodClosedV1.class,
                            "Xcon009TimePeriodClosedV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon009TimePeriodClosedV1.class,
                            "Xcon009TimePeriodClosedV1 ends before a property value");
                }
                switch (propertyName) {
                case "closePeriodId" -> {
                    if (closePeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property closePeriodId");
                    }
                    closePeriodIdSeen = true;
                    closePeriodId = CanonicalHrisJson.readUuid(parser, context, "closePeriodId", false);
                }
                case "closeRevision" -> {
                    if (closeRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property closeRevision");
                    }
                    closeRevisionSeen = true;
                    closeRevision = CanonicalHrisJson.readLong(parser, context, "closeRevision", false);
                }
                case "ledgerRevision" -> {
                    if (ledgerRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property ledgerRevision");
                    }
                    ledgerRevisionSeen = true;
                    ledgerRevision = CanonicalHrisJson.readLong(parser, context, "ledgerRevision", false);
                }
                case "periodEnd" -> {
                    if (periodEndSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property periodEnd");
                    }
                    periodEndSeen = true;
                    periodEnd = CanonicalHrisJson.readDate(parser, context, "periodEnd", false);
                }
                case "periodStart" -> {
                    if (periodStartSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property periodStart");
                    }
                    periodStartSeen = true;
                    periodStart = CanonicalHrisJson.readDate(parser, context, "periodStart", false);
                }
                case "ruleDigest" -> {
                    if (ruleDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property ruleDigest");
                    }
                    ruleDigestSeen = true;
                    ruleDigest = CanonicalHrisJson.readString(parser, context, "ruleDigest", false);
                }
                case "scopeId" -> {
                    if (scopeIdSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property scopeId");
                    }
                    scopeIdSeen = true;
                    scopeId = CanonicalHrisJson.readUuid(parser, context, "scopeId", false);
                }
                case "sourceDigest" -> {
                    if (sourceDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon009TimePeriodClosedV1.class,
                                "duplicate property sourceDigest");
                    }
                    sourceDigestSeen = true;
                    sourceDigest = CanonicalHrisJson.readString(parser, context, "sourceDigest", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon009TimePeriodClosedV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!closePeriodIdSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property closePeriodId");
            }
            if (!closeRevisionSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property closeRevision");
            }
            if (!ledgerRevisionSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property ledgerRevision");
            }
            if (!periodEndSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property periodEnd");
            }
            if (!periodStartSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property periodStart");
            }
            if (!ruleDigestSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property ruleDigest");
            }
            if (!scopeIdSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property scopeId");
            }
            if (!sourceDigestSeen) {
                return context.reportInputMismatch(Xcon009TimePeriodClosedV1.class,
                        "missing required property sourceDigest");
            }
            return new Xcon009TimePeriodClosedV1(
                    closePeriodId,
                    closeRevision,
                    ledgerRevision,
                    periodEnd,
                    periodStart,
                    ruleDigest,
                    scopeId,
                    sourceDigest);
        }
    }
}
