/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_018
 * Normalized schema SHA-256: 1110fc408227d41696687df8fce2d80e4ee98ccb6cdba830bc9279f0fe69355e
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon018WorkerTaxIdentitySnapshotV1.Deserializer.class)
public record Xcon018WorkerTaxIdentitySnapshotV1(
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
        String payloadDigest,
        String residencyStatus,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion,
        String taxIdentifierToken,
        String taxJurisdictionCode,
        String workerClassification,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId) {

    public Xcon018WorkerTaxIdentitySnapshotV1 {
        Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(residencyStatus, "residencyStatus must not be null");
        if (!Set.of("RESIDENT", "NON_RESIDENT", "DUAL_RESIDENT", "UNKNOWN").contains(residencyStatus)) {
            throw new IllegalArgumentException("residencyStatus is not a canonical value");
        }
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        Objects.requireNonNull(taxIdentifierToken, "taxIdentifierToken must not be null");
        if (!Pattern.matches("^tok_[A-Za-z0-9_-]{24,160}$", taxIdentifierToken)) {
            throw new IllegalArgumentException("taxIdentifierToken does not match its canonical format");
        }
        Objects.requireNonNull(taxJurisdictionCode, "taxJurisdictionCode must not be null");
        if (!Pattern.matches("^[A-Z]{2}(?:-[A-Z0-9]{1,8})?$", taxJurisdictionCode)) {
            throw new IllegalArgumentException("taxJurisdictionCode does not match its canonical format");
        }
        Objects.requireNonNull(workerClassification, "workerClassification must not be null");
        if (!Set.of("EMPLOYEE", "CONTRACTOR", "DIRECTOR", "OTHER").contains(workerClassification)) {
            throw new IllegalArgumentException("workerClassification is not a canonical value");
        }
        Objects.requireNonNull(workerId, "workerId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon018WorkerTaxIdentitySnapshotV1> {

        @Override
        public Xcon018WorkerTaxIdentitySnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "Xcon018WorkerTaxIdentitySnapshotV1 must be encoded as a JSON object");
            }
            LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
            LocalDate effectiveTo = null; boolean effectiveToSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            String residencyStatus = null; boolean residencyStatusSeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            String taxIdentifierToken = null; boolean taxIdentifierTokenSeen = false;
            String taxJurisdictionCode = null; boolean taxJurisdictionCodeSeen = false;
            String workerClassification = null; boolean workerClassificationSeen = false;
            UUID workerId = null; boolean workerIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon018WorkerTaxIdentitySnapshotV1.class,
                            "Xcon018WorkerTaxIdentitySnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon018WorkerTaxIdentitySnapshotV1.class,
                            "Xcon018WorkerTaxIdentitySnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "effectiveFrom" -> {
                    if (effectiveFromSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property effectiveFrom");
                    }
                    effectiveFromSeen = true;
                    effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                }
                case "effectiveTo" -> {
                    if (effectiveToSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property effectiveTo");
                    }
                    effectiveToSeen = true;
                    effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "residencyStatus" -> {
                    if (residencyStatusSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property residencyStatus");
                    }
                    residencyStatusSeen = true;
                    residencyStatus = CanonicalHrisJson.readString(parser, context, "residencyStatus", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                case "taxIdentifierToken" -> {
                    if (taxIdentifierTokenSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property taxIdentifierToken");
                    }
                    taxIdentifierTokenSeen = true;
                    taxIdentifierToken = CanonicalHrisJson.readString(parser, context, "taxIdentifierToken", false);
                }
                case "taxJurisdictionCode" -> {
                    if (taxJurisdictionCodeSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property taxJurisdictionCode");
                    }
                    taxJurisdictionCodeSeen = true;
                    taxJurisdictionCode = CanonicalHrisJson.readString(parser, context, "taxJurisdictionCode", false);
                }
                case "workerClassification" -> {
                    if (workerClassificationSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property workerClassification");
                    }
                    workerClassificationSeen = true;
                    workerClassification = CanonicalHrisJson.readString(parser, context, "workerClassification", false);
                }
                case "workerId" -> {
                    if (workerIdSeen) {
                        return context.reportInputMismatch(
                                Xcon018WorkerTaxIdentitySnapshotV1.class,
                                "duplicate property workerId");
                    }
                    workerIdSeen = true;
                    workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon018WorkerTaxIdentitySnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!effectiveFromSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property effectiveFrom");
            }
            if (!effectiveToSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property effectiveTo");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!residencyStatusSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property residencyStatus");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property sourceVersion");
            }
            if (!taxIdentifierTokenSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property taxIdentifierToken");
            }
            if (!taxJurisdictionCodeSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property taxJurisdictionCode");
            }
            if (!workerClassificationSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property workerClassification");
            }
            if (!workerIdSeen) {
                return context.reportInputMismatch(Xcon018WorkerTaxIdentitySnapshotV1.class,
                        "missing required property workerId");
            }
            return new Xcon018WorkerTaxIdentitySnapshotV1(
                    effectiveFrom,
                    effectiveTo,
                    payloadDigest,
                    residencyStatus,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion,
                    taxIdentifierToken,
                    taxJurisdictionCode,
                    workerClassification,
                    workerId);
        }
    }
}
