/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_011
 * Normalized schema SHA-256: e7dfa8e9ad200f4934d6d75169e72557e310d616fe28ccc30cb02c24659aa2e3
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon011PayrollTimeHandoffReadyV1.Deserializer.class)
public record Xcon011PayrollTimeHandoffReadyV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closePeriodId,
        long closeRevision,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID closedTimeResultId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID handoffId,
        int lineCount,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payPeriodId,
        String payloadDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID payrollEntityId,
        String ruleDigest,
        String sourceDigest,
        int workerCount) {

    public Xcon011PayrollTimeHandoffReadyV1 {
        Objects.requireNonNull(closePeriodId, "closePeriodId must not be null");
        if (closeRevision < 1L) {
            throw new IllegalArgumentException("closeRevision is below its canonical minimum");
        }
        Objects.requireNonNull(closedTimeResultId, "closedTimeResultId must not be null");
        Objects.requireNonNull(handoffId, "handoffId must not be null");
        if (lineCount < 0L) {
            throw new IllegalArgumentException("lineCount is below its canonical minimum");
        }
        if (lineCount > 1000000L) {
            throw new IllegalArgumentException("lineCount exceeds its canonical maximum");
        }
        Objects.requireNonNull(payPeriodId, "payPeriodId must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(payrollEntityId, "payrollEntityId must not be null");
        Objects.requireNonNull(ruleDigest, "ruleDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", ruleDigest)) {
            throw new IllegalArgumentException("ruleDigest does not match its canonical format");
        }
        Objects.requireNonNull(sourceDigest, "sourceDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", sourceDigest)) {
            throw new IllegalArgumentException("sourceDigest does not match its canonical format");
        }
        if (workerCount < 0L) {
            throw new IllegalArgumentException("workerCount is below its canonical minimum");
        }
        if (workerCount > 1000000L) {
            throw new IllegalArgumentException("workerCount exceeds its canonical maximum");
        }
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon011PayrollTimeHandoffReadyV1> {

        @Override
        public Xcon011PayrollTimeHandoffReadyV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon011PayrollTimeHandoffReadyV1.class,
                        "Xcon011PayrollTimeHandoffReadyV1 must be encoded as a JSON object");
            }
            UUID closePeriodId = null; boolean closePeriodIdSeen = false;
            long closeRevision = 0L; boolean closeRevisionSeen = false;
            UUID closedTimeResultId = null; boolean closedTimeResultIdSeen = false;
            UUID handoffId = null; boolean handoffIdSeen = false;
            int lineCount = 0; boolean lineCountSeen = false;
            UUID payPeriodId = null; boolean payPeriodIdSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            UUID payrollEntityId = null; boolean payrollEntityIdSeen = false;
            String ruleDigest = null; boolean ruleDigestSeen = false;
            String sourceDigest = null; boolean sourceDigestSeen = false;
            int workerCount = 0; boolean workerCountSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon011PayrollTimeHandoffReadyV1.class,
                            "Xcon011PayrollTimeHandoffReadyV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon011PayrollTimeHandoffReadyV1.class,
                            "Xcon011PayrollTimeHandoffReadyV1 ends before a property value");
                }
                switch (propertyName) {
                case "closePeriodId" -> {
                    if (closePeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property closePeriodId");
                    }
                    closePeriodIdSeen = true;
                    closePeriodId = CanonicalHrisJson.readUuid(parser, context, "closePeriodId", false);
                }
                case "closeRevision" -> {
                    if (closeRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property closeRevision");
                    }
                    closeRevisionSeen = true;
                    closeRevision = CanonicalHrisJson.readLong(parser, context, "closeRevision", false);
                }
                case "closedTimeResultId" -> {
                    if (closedTimeResultIdSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property closedTimeResultId");
                    }
                    closedTimeResultIdSeen = true;
                    closedTimeResultId = CanonicalHrisJson.readUuid(parser, context, "closedTimeResultId", false);
                }
                case "handoffId" -> {
                    if (handoffIdSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property handoffId");
                    }
                    handoffIdSeen = true;
                    handoffId = CanonicalHrisJson.readUuid(parser, context, "handoffId", false);
                }
                case "lineCount" -> {
                    if (lineCountSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property lineCount");
                    }
                    lineCountSeen = true;
                    lineCount = CanonicalHrisJson.readInt(parser, context, "lineCount", false);
                }
                case "payPeriodId" -> {
                    if (payPeriodIdSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property payPeriodId");
                    }
                    payPeriodIdSeen = true;
                    payPeriodId = CanonicalHrisJson.readUuid(parser, context, "payPeriodId", false);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "payrollEntityId" -> {
                    if (payrollEntityIdSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property payrollEntityId");
                    }
                    payrollEntityIdSeen = true;
                    payrollEntityId = CanonicalHrisJson.readUuid(parser, context, "payrollEntityId", false);
                }
                case "ruleDigest" -> {
                    if (ruleDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property ruleDigest");
                    }
                    ruleDigestSeen = true;
                    ruleDigest = CanonicalHrisJson.readString(parser, context, "ruleDigest", false);
                }
                case "sourceDigest" -> {
                    if (sourceDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property sourceDigest");
                    }
                    sourceDigestSeen = true;
                    sourceDigest = CanonicalHrisJson.readString(parser, context, "sourceDigest", false);
                }
                case "workerCount" -> {
                    if (workerCountSeen) {
                        return context.reportInputMismatch(
                                Xcon011PayrollTimeHandoffReadyV1.class,
                                "duplicate property workerCount");
                    }
                    workerCountSeen = true;
                    workerCount = CanonicalHrisJson.readInt(parser, context, "workerCount", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon011PayrollTimeHandoffReadyV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!closePeriodIdSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property closePeriodId");
            }
            if (!closeRevisionSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property closeRevision");
            }
            if (!closedTimeResultIdSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property closedTimeResultId");
            }
            if (!handoffIdSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property handoffId");
            }
            if (!lineCountSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property lineCount");
            }
            if (!payPeriodIdSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property payPeriodId");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property payloadDigest");
            }
            if (!payrollEntityIdSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property payrollEntityId");
            }
            if (!ruleDigestSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property ruleDigest");
            }
            if (!sourceDigestSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property sourceDigest");
            }
            if (!workerCountSeen) {
                return context.reportInputMismatch(Xcon011PayrollTimeHandoffReadyV1.class,
                        "missing required property workerCount");
            }
            return new Xcon011PayrollTimeHandoffReadyV1(
                    closePeriodId,
                    closeRevision,
                    closedTimeResultId,
                    handoffId,
                    lineCount,
                    payPeriodId,
                    payloadDigest,
                    payrollEntityId,
                    ruleDigest,
                    sourceDigest,
                    workerCount);
        }
    }
}
