/*
 * Generated by scripts/generate-hris-contracts.py --write.
 * Source: contracts/hris/canonical/schemas/cross-module-canonical-schemas.v1.json#/$defs/XCON_016
 * Normalized schema SHA-256: bf2a2537ab4b2d9c1c1d9482508a62e510a1e3c1efabb8474822f59e2d99d1a4
 * Do not edit by hand.
 */
package com.dwp.contracts.hris.xcon.v1;

import com.dwp.platform.contracts.hris.generated.CanonicalHrisJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/** Immutable Java binding for the canonical HRIS schema. */
@JsonInclude(JsonInclude.Include.ALWAYS)
@JsonDeserialize(using = Xcon016WorkplaceAssignmentSnapshotV1.Deserializer.class)
public record Xcon016WorkplaceAssignmentSnapshotV1(
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID assignmentId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID calendarId,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveFrom,
        @JsonSerialize(using = CanonicalHrisJson.LocalDateSerializer.class) LocalDate effectiveTo,
        String payloadDigest,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID snapshotId,
        long snapshotRevision,
        long sourceVersion,
        String timeZone,
        String workLocationCode,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workerId,
        @JsonSerialize(using = CanonicalHrisJson.UuidSerializer.class) UUID workplaceId) {

    public Xcon016WorkplaceAssignmentSnapshotV1 {
        Objects.requireNonNull(assignmentId, "assignmentId must not be null");
        Objects.requireNonNull(calendarId, "calendarId must not be null");
        Objects.requireNonNull(effectiveFrom, "effectiveFrom must not be null");
        Objects.requireNonNull(payloadDigest, "payloadDigest must not be null");
        if (!Pattern.matches("^[0-9a-f]{64}$", payloadDigest)) {
            throw new IllegalArgumentException("payloadDigest does not match its canonical format");
        }
        Objects.requireNonNull(snapshotId, "snapshotId must not be null");
        if (snapshotRevision < 1L) {
            throw new IllegalArgumentException("snapshotRevision is below its canonical minimum");
        }
        if (sourceVersion < 1L) {
            throw new IllegalArgumentException("sourceVersion is below its canonical minimum");
        }
        Objects.requireNonNull(timeZone, "timeZone must not be null");
        if (timeZone.length() > 80) {
            throw new IllegalArgumentException("timeZone is longer than 80");
        }
        if (!Pattern.matches("^[A-Za-z_]+(?:/[A-Za-z0-9_+.-]+)+$", timeZone)) {
            throw new IllegalArgumentException("timeZone does not match its canonical format");
        }
        Objects.requireNonNull(workLocationCode, "workLocationCode must not be null");
        if (workLocationCode.length() < 1) {
            throw new IllegalArgumentException("workLocationCode is shorter than 1");
        }
        if (workLocationCode.length() > 80) {
            throw new IllegalArgumentException("workLocationCode is longer than 80");
        }
        Objects.requireNonNull(workerId, "workerId must not be null");
        Objects.requireNonNull(workplaceId, "workplaceId must not be null");
    }

    public static final class Deserializer
            extends JsonDeserializer<Xcon016WorkplaceAssignmentSnapshotV1> {

        @Override
        public Xcon016WorkplaceAssignmentSnapshotV1 deserialize(
                JsonParser parser,
                DeserializationContext context) throws IOException {
            if (!parser.isExpectedStartObjectToken()) {
                return context.reportInputMismatch(
                        Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "Xcon016WorkplaceAssignmentSnapshotV1 must be encoded as a JSON object");
            }
            UUID assignmentId = null; boolean assignmentIdSeen = false;
            UUID calendarId = null; boolean calendarIdSeen = false;
            LocalDate effectiveFrom = null; boolean effectiveFromSeen = false;
            LocalDate effectiveTo = null; boolean effectiveToSeen = false;
            String payloadDigest = null; boolean payloadDigestSeen = false;
            UUID snapshotId = null; boolean snapshotIdSeen = false;
            long snapshotRevision = 0L; boolean snapshotRevisionSeen = false;
            long sourceVersion = 0L; boolean sourceVersionSeen = false;
            String timeZone = null; boolean timeZoneSeen = false;
            String workLocationCode = null; boolean workLocationCodeSeen = false;
            UUID workerId = null; boolean workerIdSeen = false;
            UUID workplaceId = null; boolean workplaceIdSeen = false;
            while (parser.nextToken() != JsonToken.END_OBJECT) {
                if (!parser.hasToken(JsonToken.FIELD_NAME)) {
                    return context.reportInputMismatch(
                            Xcon016WorkplaceAssignmentSnapshotV1.class,
                            "Xcon016WorkplaceAssignmentSnapshotV1 contains a non-field token");
                }
                String propertyName = parser.currentName();
                if (parser.nextToken() == null) {
                    return context.reportInputMismatch(
                            Xcon016WorkplaceAssignmentSnapshotV1.class,
                            "Xcon016WorkplaceAssignmentSnapshotV1 ends before a property value");
                }
                switch (propertyName) {
                case "assignmentId" -> {
                    if (assignmentIdSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property assignmentId");
                    }
                    assignmentIdSeen = true;
                    assignmentId = CanonicalHrisJson.readUuid(parser, context, "assignmentId", false);
                }
                case "calendarId" -> {
                    if (calendarIdSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property calendarId");
                    }
                    calendarIdSeen = true;
                    calendarId = CanonicalHrisJson.readUuid(parser, context, "calendarId", false);
                }
                case "effectiveFrom" -> {
                    if (effectiveFromSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property effectiveFrom");
                    }
                    effectiveFromSeen = true;
                    effectiveFrom = CanonicalHrisJson.readDate(parser, context, "effectiveFrom", false);
                }
                case "effectiveTo" -> {
                    if (effectiveToSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property effectiveTo");
                    }
                    effectiveToSeen = true;
                    effectiveTo = CanonicalHrisJson.readDate(parser, context, "effectiveTo", true);
                }
                case "payloadDigest" -> {
                    if (payloadDigestSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property payloadDigest");
                    }
                    payloadDigestSeen = true;
                    payloadDigest = CanonicalHrisJson.readString(parser, context, "payloadDigest", false);
                }
                case "snapshotId" -> {
                    if (snapshotIdSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property snapshotId");
                    }
                    snapshotIdSeen = true;
                    snapshotId = CanonicalHrisJson.readUuid(parser, context, "snapshotId", false);
                }
                case "snapshotRevision" -> {
                    if (snapshotRevisionSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property snapshotRevision");
                    }
                    snapshotRevisionSeen = true;
                    snapshotRevision = CanonicalHrisJson.readLong(parser, context, "snapshotRevision", false);
                }
                case "sourceVersion" -> {
                    if (sourceVersionSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property sourceVersion");
                    }
                    sourceVersionSeen = true;
                    sourceVersion = CanonicalHrisJson.readLong(parser, context, "sourceVersion", false);
                }
                case "timeZone" -> {
                    if (timeZoneSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property timeZone");
                    }
                    timeZoneSeen = true;
                    timeZone = CanonicalHrisJson.readString(parser, context, "timeZone", false);
                }
                case "workLocationCode" -> {
                    if (workLocationCodeSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property workLocationCode");
                    }
                    workLocationCodeSeen = true;
                    workLocationCode = CanonicalHrisJson.readString(parser, context, "workLocationCode", false);
                }
                case "workerId" -> {
                    if (workerIdSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property workerId");
                    }
                    workerIdSeen = true;
                    workerId = CanonicalHrisJson.readUuid(parser, context, "workerId", false);
                }
                case "workplaceId" -> {
                    if (workplaceIdSeen) {
                        return context.reportInputMismatch(
                                Xcon016WorkplaceAssignmentSnapshotV1.class,
                                "duplicate property workplaceId");
                    }
                    workplaceIdSeen = true;
                    workplaceId = CanonicalHrisJson.readUuid(parser, context, "workplaceId", false);
                }
                default -> {
                    return context.reportInputMismatch(
                            Xcon016WorkplaceAssignmentSnapshotV1.class,
                            "unknown property %s", propertyName);
                }
                }
            }
            if (!assignmentIdSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property assignmentId");
            }
            if (!calendarIdSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property calendarId");
            }
            if (!effectiveFromSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property effectiveFrom");
            }
            if (!effectiveToSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property effectiveTo");
            }
            if (!payloadDigestSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property payloadDigest");
            }
            if (!snapshotIdSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property snapshotId");
            }
            if (!snapshotRevisionSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property snapshotRevision");
            }
            if (!sourceVersionSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property sourceVersion");
            }
            if (!timeZoneSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property timeZone");
            }
            if (!workLocationCodeSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property workLocationCode");
            }
            if (!workerIdSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property workerId");
            }
            if (!workplaceIdSeen) {
                return context.reportInputMismatch(Xcon016WorkplaceAssignmentSnapshotV1.class,
                        "missing required property workplaceId");
            }
            return new Xcon016WorkplaceAssignmentSnapshotV1(
                    assignmentId,
                    calendarId,
                    effectiveFrom,
                    effectiveTo,
                    payloadDigest,
                    snapshotId,
                    snapshotRevision,
                    sourceVersion,
                    timeZone,
                    workLocationCode,
                    workerId,
                    workplaceId);
        }
    }
}
