-- CORE-006 product-scoped capability enforcement controls. The legacy tenant-wide
-- control remains registered for compatibility; each product axis is default-off
-- until its exact authorization contract and rollout revision are approved.

INSERT INTO prv_feature_flags (
    feature_flag_id, feature_key, display_name, description, owner_service,
    value_type, default_value, configuration_schema, risk_tier,
    lifecycle_state, created_by, updated_by)
VALUES
    ('6d63f117-cf23-4b26-961a-b15a5847b201',
     'access.product-surfaces.capability-enforcement.approvals.v1',
     'Approvals product capability enforcement',
     'Enforces approved exact capability and policy decisions for Approvals.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b202',
     'access.product-surfaces.capability-enforcement.calendar.v1',
     'Calendar product capability enforcement',
     'Enforces approved exact capability and policy decisions for Calendar.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b203',
     'access.product-surfaces.capability-enforcement.communications.v1',
     'Communications product capability enforcement',
     'Enforces approved exact capability and policy decisions for Communications.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b204',
     'access.product-surfaces.capability-enforcement.dwaion.v1',
     'DWAI ON product capability enforcement',
     'Enforces approved exact capability and policy decisions for DWAI ON.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b205',
     'access.product-surfaces.capability-enforcement.hcm.v1',
     'HCM product capability enforcement',
     'Enforces approved exact capability and policy decisions for HCM.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b206',
     'access.product-surfaces.capability-enforcement.mail.v1',
     'Mail product capability enforcement',
     'Enforces approved exact capability and policy decisions for Mail.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b207',
     'access.product-surfaces.capability-enforcement.messaging.v1',
     'Messaging product capability enforcement',
     'Enforces approved exact capability and policy decisions for Messaging.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b208',
     'access.product-surfaces.capability-enforcement.notifications.v1',
     'Notifications product capability enforcement',
     'Enforces approved exact capability and policy decisions for Notifications.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b209',
     'access.product-surfaces.capability-enforcement.services.v1',
     'Services product capability enforcement',
     'Enforces approved exact capability and policy decisions for Services.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b210',
     'access.product-surfaces.capability-enforcement.spaces.v1',
     'Spaces product capability enforcement',
     'Enforces approved exact capability and policy decisions for Spaces.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0),
    ('6d63f117-cf23-4b26-961a-b15a5847b211',
     'access.product-surfaces.capability-enforcement.workplace.v1',
     'Workplace product capability enforcement',
     'Enforces approved exact capability and policy decisions for Workplace.',
     'identity-platform', 'BOOLEAN', 'false'::jsonb,
     '{"type":"boolean"}'::jsonb, 'L3', 'ACTIVE', 0, 0)
ON CONFLICT (feature_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    owner_service = EXCLUDED.owner_service,
    value_type = EXCLUDED.value_type,
    default_value = EXCLUDED.default_value,
    configuration_schema = EXCLUDED.configuration_schema,
    risk_tier = EXCLUDED.risk_tier,
    lifecycle_state = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO prv_feature_rollout_decision_revision (feature_flag_id, opaque_revision)
SELECT feature_flag_id, 0
  FROM prv_feature_flags
 WHERE feature_key IN (
    'access.product-surfaces.capability-enforcement.approvals.v1',
    'access.product-surfaces.capability-enforcement.calendar.v1',
    'access.product-surfaces.capability-enforcement.communications.v1',
    'access.product-surfaces.capability-enforcement.dwaion.v1',
    'access.product-surfaces.capability-enforcement.hcm.v1',
    'access.product-surfaces.capability-enforcement.mail.v1',
    'access.product-surfaces.capability-enforcement.messaging.v1',
    'access.product-surfaces.capability-enforcement.notifications.v1',
    'access.product-surfaces.capability-enforcement.services.v1',
    'access.product-surfaces.capability-enforcement.spaces.v1',
    'access.product-surfaces.capability-enforcement.workplace.v1')
ON CONFLICT (feature_flag_id) DO NOTHING;
