configurations.all {
    // Spring Cloud Gateway는 Reactor Netty만 사용합니다.
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
    exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-core'
}

dependencies {
    implementation project(':dwp-observability')
    // Spring Cloud Gateway (Reactor Netty)
    implementation('org.springframework.cloud:spring-cloud-starter-gateway-server-webflux') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos::osx-aarch_64'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
